export const mockQuizzes = [
    {
        id: "de_1_dgnl",
        title: "Đề 1 (120/120 câu)",
        description: "Phần 1: Tiếng Việt, Tiếng Anh (60 câu) & Phần 2: Toán (30 câu) & Phần 3: Tư duy KH (30 câu)",
        questions: [
            // Questions 1-20
            { id: "q1", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 1: Thị Phương là nhân vật trong vở chèo Trương Viên. Thời bình, nàng động viên chồng học hành thi cử. Thời chiến, nàng chăm sóc, bảo vệ mẹ chồng và lặn lội tìm chồng.\n“Thị Phương:\nMẹ ơi, giặc đã kéo đến đây\nCon xin dắt mẹ vào ngay trong rừng\nKẻo con chút phận má hồng\nNữa gặp gian hùng, lỗi đạo tào khang.\nTrước là thất tiết cùng chàng\nSau con bỏ mẹ giữa đàng ai nuôi”.\n(Trần Việt Ngữ sưu tầm, Trương Viên chèo cổ)\nNhân vật Thị Phương là loại nhân vật gì?", options: ["A. Kép.", "B. Lão.", "C. Đào lẳng.", "D. Đào thương."], correctIndex: 3 },
            { id: "q2", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 2: “Bị cướp vợ và chiến đấu giành lại vợ” là mô típ (motif) phổ biến trong thể loại nào của văn học dân gian Việt Nam?", options: ["A. Thần thoại.", "B. Sử thi.", "C. Tuồng, chèo.", "D. Truyện thơ."], correctIndex: 1 },
            { id: "q3", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 3: “Sau đó vài tháng, Hà Nhân tiếp được tin nhà gửi đến kinh đô, nói cha mẹ ở nhà đã hỏi vợ cho, giục Sinh nên về mau để làm lễ cưới. Sinh bối rối quanh co, lòng rất không nỡ, hai nàng đoán biết được tình ý, bảo Sinh rằng:\n- Bọn chúng em thân bồ vóc liễu, không thể cáng đáng được việc tần tảo ở gia đình. Vả ngôi chủ phụ trong nhà, tất phải là người trong nền nếp trâm anh như Tống Tử, Tề Khương, chúng em đâu dám chòi mòi đến. Chỉ mong chàng sau buổi về quê, tình cũ sẽ vấn vương không dứt, sớm dẹp lòng quyến luyến hương thổ để lại tính kế tìm hoa.”\n(Nguyễn Dữ, Chuyện kỳ ngộ ở Trại Tây)\nDòng nào sau đây nêu không đúng đặc điểm của lời nhân vật trong đoạn trích trên?", options: ["A. Sử dụng lối nói chuộng ngôn từ hoa mỹ.", "B. Sử dụng lối nói dùng nhiều điển tích, điển cố.", "C. Sử dụng lối nói dùng hình ảnh so sánh, ẩn dụ.", "D. Sử dụng lối nói gần với lời ăn tiếng nói hằng ngày."], correctIndex: 3 },
            { id: "q4", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 4:\n“Khắc khoải sầu đưa giọng lửng lơ,\nẤy hồn Thục đế thác bao giờ?\nNăm canh máu chảy đêm hè vắng,\nSáu khắc hồn tan bóng nguyệt mờ.\nCó phải tiếc xuân mà đứng gọi,\nHay là nhớ nước vẫn nằm mơ?\nThâu đêm ròng rã kêu ai đó,\nGiục khách giang hồ dạ ngẩn ngơ”.\n(Nguyễn Khuyến, Cuốc kêu cảm hứng)\nBài thơ thể hiện nỗi niềm gì của chủ thể trữ tình?", options: ["A. Thương tiếc mùa xuân trôi qua mất.", "B. Thương tiếc nước mất vào tay giặc.", "C. Thương tiếc máu xương của người yêu nước.", "D. Thương tiếc nước bị chia cắt."], correctIndex: 1 },
            { id: "q5", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 5: Khi Thúy Kiều lại một lần nữa bị lừa bán vào lầu xanh, Nguyễn Du đã viết:\n“Nghĩ đời mà ngán cho đời\nTài tình chi lắm, cho trời đất ghen.\nTiếc thay nước đã đánh phèn\nMà cho bùn lại vẩn lên mấy lần!\nHồng quân với khách hồng quần\nĐã xoay đến thế, còn vần chưa tha”.\n(Nguyễn Du, Truyện Kiều)\nHai từ “hồng quân” và “hồng quần” có ý nghĩa:", options: ["A. Người lính trong quân đội và người con gái đẹp.", "B. Vị vua anh minh with người tì thiếp đẹp.", "C. Đấng tạo hóa with người ca kỹ đẹp.", "D. Đấng tạo hóa and người con gái đẹp."], correctIndex: 3 },
            { id: "q6", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 6: “Cuộc xua đuổi đã kéo dài hàng tiếng đồng hồ. Lão Khúng đã mệt nhoài nhưng vẫn chưa chịu cho vật dừng lại. Nó phải đi thật xa, phải bắt nó vào thật sâu giữa rừng thẳm, để không còn lối nào trở lại with lão. Rồi thì mai đây khi trở về nhà, lão nghĩ, lão sẽ nói thật with mụ Huệ, lão đã không đem xuống chợ Giát để bán mà trên dọc đường đã giải thoát cho nó, trả lại cho nó cuộc đời tự do, lão đã xua nó vào rừng, vào giữa giang sơn của một bầy bò hoang... Chắc hẳn mụ Huệ cũng không mè nheo lão. Mụ sẽ thông cảm with lão, with việc làm của lão”.\n(Nguyễn Minh Châu, Phiên chợ Giát)\nHành động xua con vật đi thật xa vào rừng thẳm thể hiện điều gì?", options: ["A. Sự mệt nhoài của lão khi đem con vật xuống chợ Giát để bán.", "B. Sự quyết tâm giải thoát con vật, trả lại cho nó cuộc đời tự do.", "C. Sự mong mỏi được trở về nhà và được vợ của lão cảm thông.", "D. Sự cảm thông with con vật và sự tự dằn vặt bản thân ở lão."], correctIndex: 1 },
            { id: "q7", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 7: “Tôi hát bài hát về cố hương tôi\nTrong ánh sáng đèn dầu\nNgọn đèn đó ông bà tôi để lại\nĐẹp và buồn hơn tất cả những ngọn đèn\nThuở tôi vừa sinh ra\nMẹ đã đặt ngọn đèn trước mặt tôi\nĐể tôi nhìn mặt đèn mà biết buồn, biết yêu và biết khóc”.\n(Nguyễn Quang Thiều, Bài hát về cố hương)\nDòng nào dưới đây không thể hiện ý nghĩa biểu đạt của hình ảnh “ánh sáng đèn dầu” trong đoạn thơ trên?", options: ["A. Ánh sáng của không gian ấu thơ.", "B. Ánh sáng của không gian gia đình.", "C. Ánh sáng của thời gian ký ức.", "D. Ánh sáng của quá khứ đau thương, mất mát."], correctIndex: 3 },
            { id: "q8", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 8:\nTrung tá Nam hồi tưởng về cuộc trò chuyện with hạ sĩ Lãm:\n“Trong đầu anh bỗng hiện lên hình ảnh người hạ sĩ quê ở Hà Nội có cái nhìn lì lợm ngày nào…\nLãm! - Này, bây giờ ta nói chuyện tình anh em, đừng trên dưới gì hết - Vâng, tôi cũng nghĩ như thế -\nNghe nói thời kỳ chốt chặn ở biên giới, cậu là một tay súng tốt? - Vâng, thưa thủ trưởng, cũng có lẽ như thế - Nhưng chỉ im tiếng súng có mấy tháng thôi, người ta phản ảnh with tôi cậu đã không còn giữ được phẩm chất ấy nữa? - Vâng, nếu gọi như thế là phẩm chất - Tôi yêu cầu cậu chuyện trò with tôi chân thành và dễ hiểu hơn một chút, và trước hết là xin cậu hãy bỏ giúp đẫn mía trên tay kia đi cho tôi nhờ - Dạ… Thưa, tôi vẫn luôn luôn chân thành và dễ hiểu đấy chứ ạ!”\n(Chu Lai, Phố)\nĐoạn hội thoại trên cho thấy điều gì về hạ sĩ Lãm?", options: ["A. Có tài và ngang tàng.", "B. Bất tài và ngang ngược.", "C. Có tài và khiêm cung.", "D. Bất tài và chân thành."], correctIndex: 0 },
            { id: "q9", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 9: LÊ TƯƠNG DỰC - Vua cần đến thì thần nhân phải xả thân làm việc kỳ đến chết thì thôi.\nVŨ NHƯ TÔ - Nhưng xử đãi thế thì ai muốn trau dồi nghề nghiệp? Kính sĩ mới đắc sĩ...\nLÊ TƯƠNG DỰC - Kính sĩ đắc sĩ, mi là sĩ đấy ư: Mi dám tự phụ là sĩ thảo nào mi không sợ chết.\nVŨ NHƯ TÔ - Sĩ mà không có chân tài thì tiện nhân không bàn. Anh em tiện nhân còn có những nguyện vọng sâu xa hơn đối with nước. Hoàng thượng quá nhầm về chữ sĩ. Một ông quan trị dân, with một người thợ giỏi, xây những lâu đài tráng quan, điểm xuyết cho đất nước, tiện nhân chưa biết người nào mới đáng gọi là sĩ.\n(Nguyễn Huy Tưởng, Vũ Như Tô)\nÝ nào phù hợp with tính cách Vũ Như Tô được thể hiện trong đoạn trích?", options: ["A. Không bao giờ bằng lòng with thực tại, khát khó sự sáng tạo.", "B. Trọng danh dự, muốn đem tài năng phụng sự đất nước.", "C. Coi thường vương quyền, muốn có những kẻ sĩ chân tài.", "D. Trọng danh dự, muốn có những kẻ sĩ chân tài."], correctIndex: 1 },
            { id: "q10", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 10: “Năm 1975, khi tấm lưng của bà Chắt Chu đã bắt đầu còng xuống thì o Nhị - Lê Thị Nhị - con gái bà mới trở về. Lúc đó, o đã 29 tuổi. Phụ nữ làng chài thường lấy chồng rất sớm. Cái tuổi của o khi đó, làng đã toan gọi… gái già. O cứ ở vậy, gánh cá, gánh tấp đốt thuyền thuê, rồi làm nghề dệt thảm len ngoài Hợp tác xã Hải Đằng nuôi mẹ mà không chịu lấy chồng. Ai hỏi thì o cười, nửa thật nửa đùa, rằng “nỏ có ai chịu lấy”.\nNăm 1967, đang là một vận động viên bóng chuyền, o Nhị xung phong nhập ngũ, vào Thanh niên xung phong lấp hố bom, bạt núi mở đường, làm cọc tiêu dẫn xe, qua ngầm, vượt hố trong những đêm trời tối không đèn. Đi qua chiến tranh, sức khỏe và nhan sắc của o gửi hết ở chiến trường. Dệt thảm khá nhanh tay, lành nghề, nhưng tấm thảm đời o thì cứ rối nùi, chẳng biết đâu mà gỡ.[…]\nĐùng một cái, cả xã Thạch Kim sôi sục. Chẳng hiểu từ đâu báo chí bỗng phát hiện ra, o Lê Thị Nhị chính là nguyên mẫu của cô thanh niên xung phong trong bài thơ “Gửi em, cô Thanh niên xung phong” của nhà thơ Phạm Tiến Duật”.\n(Nguyễn Hồng Lam, Vu vơ sợi khói đốt thuyền)\nĐoạn trích có chứa đựng yếu tố:", options: ["A. Hư cấu.", "B. Phi hư cấu.", "C. Tự truyện.", "D. Tự thuật."], correctIndex: 1 },
            { id: "q11", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 11:\nTình thiên\n“Sự vật tuần hoàn nguyên hữu định,\nVũ thiên chi hậu tất tình thiên;\nPhiến thì vũ trụ giải lâm phục,\nVạn lý sơn hà sái cẩm chiên;\nNhật noãn phong thanh hoa đới tiếu,\nThụ cao chi nhuận điểu tranh ngôn;\nNhân hòa vạn vật đô hưng phấn,\nKhổ tận cam lai, lý tự nhiên”.\n(Hồ Chí Minh, Nhật ký trong tù)\nTrời hửng\n“Sự vật vần xoay đà định sẵn,\nHết mưa là nắng hửng lên thôi;\nĐất trời một thoáng thu màn ướt,\nSông núi muôn trùng trải gấm phơi;\nTrời ấm, hoa cười chào gió nhẹ,\nCây cao, chim hót rộn cành tươi;\nNgười cùng vạn vật đều phơi phới,\nHết khổ là vui vốn lẽ đời”.\n(Nam Trân dịch)\nBài thơ “Tình thiên” thể hiện đặc điểm nổi bật nào trong phong cách sáng tác của Hồ Chí Minh?", options: ["A. Sử dụng hình ảnh thiên nhiên để ẩn dụ cho tình cảm và tâm tư của con người.", "B. Thể hiện sâu sắc tư tưởng phương Tây bằng lối diễn đạt gần gũi, giản dị.", "C. Miêu tả cảnh vật thiên nhiên thuần túy, không mang thông điệp triết lý.", "D. Đề cao hình mẫu cá nhân, khẳng định cá tính độc đáo của nhân vật trữ tình."], correctIndex: 0 },
            { id: "q12", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 12: “Thi pháp _____ đề cao sự đổi mới, sáng tạo của cá tính nghệ sĩ, tôn vinh “cái riêng biệt”, “cái mới lạ”, theo xu hướng vượt ra khỏi mô hình chung, ký ức thể loại. Trong khi đó, thi pháp _____ chấp nhận “cái quen thuộc”, “cái lặp lại” đã trở thành sở hữu chung của mỗi thành viên trong cộng đồng, và hơn thế nó đã trở thành kỷ niệm riêng của cả một dân tộc”.\n(Vũ Anh Tuấn, Vai trò thể loại trong khoa học văn học dân gian và vấn đề phân tích tác phẩm văn học dân gian từ góc nhìn thể loại)\nChọn cụm từ phù hợp để điền vào các chỗ trống:", options: ["A. văn học trung đại - văn học hiện đại.", "B. văn học dân gian - văn học viết.", "C. văn học viết - văn học dân gian.", "D. văn học hiện đại - văn học viết."], correctIndex: 2 },
            { id: "q13", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 13: Trường hợp nào sau đây viết đúng chính tả?", options: ["A. Sỗ sàng, súc tích, trau chuốt.", "B. Sỗ sàng, xúc tích, trau chuốt.", "C. Sỗ sàng, súc tích, trao chuốt.", "D. Sổ sàng, súc tích, trau chuốt."], correctIndex: 0 },
            { id: "q14", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 14: Câu nào sau đây viết đúng?", options: ["A. Trong gia đình, nó là đứa bị đối xử khắc khe nhất.", "B. Gió làm cây cối trong vườn xào xạc suốt đêm.", "C. Có gì đâu mà suốt ngày cứ dành giật with nhau.", "D. Kết quả chuẩn đoán của tôi không đáng lo."], correctIndex: 1 },
            { id: "q15", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 15: “Anh ấy không nói gì, vô hình trung, tôi bị những người đứng quanh đó hiểu lầm”.\n“Vô hình trung” trong câu trên có nghĩa gì?", options: ["A. Vô tình, không ý thức được cảm xúc của người khác.", "B. Có chủ ý mang đến kết quả từ hành động của chủ thể.", "C. Tuy không có chủ định, không cố tình nhưng lại thành ra như vậy.", "D. Vì thiếu suy nghĩ nên đôi khi tạo ra ảnh hưởng tiêu cực."], correctIndex: 2 },
            { id: "q16", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 16: Từ “mỗi” trong câu nào được dùng with nghĩa nhấn mạnh số lượng ít của sự vật?", options: ["A. Ngày xưa, thường cũng chỉ học một thầy, cùng lắm là vài ba thầy, chứ không như ngày nay, mỗi năm một lớp rồi mỗi môn một thầy.", "B. Mỗi người nghĩ một phách, mỗi người làm một nẻo, mạnh ai người nấy lo, còn thì “sống chết mặc bay”.", "C. Các cuộc thi bơi được tiến hành trong bể bơi có 6-10 đường bơi, mỗi một đường bơi rộng 2-2.5 m, được ngăn cách bằng dây phao.", "D. Thiết kế đặc biệt ở đây khiến ta dù nhắm tịt mắt hay giương to mắt thì cũng như nhau, bởi chỉ nhìn thấy có mỗi một màu đen."], correctIndex: 3 },
            { id: "q17", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 17: “Sống có nghị lực mạnh mẽ sẽ giúp chúng ta vượt qua mọi thử thách, mọi trở ngại của hoàn cảnh và đạt được điều chúng ta mong ước; bởi vậy do đó, mỗi người cần giữ vững tinh thần, luôn hướng đến mục tiêu và nỗ lực hoàn thành mục tiêu”.\nCâu trên mắc lỗi gì?", options: ["A. Thiếu thành phần vị ngữ.", "B. Dùng sai từ ngữ liên kết.", "C. Thiếu thành phần chủ ngữ.", "D. Dùng từ sai về từ loại."], correctIndex: 1 },
            { id: "q18", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 18:\nCâu “Nhờ kinh nghiệm nghiên cứu khoa học từ thời còn là sinh viên của Minh đã gây ấn tượng tốt with hội đồng đánh giá.” là câu sai, nên được sửa thành câu nào sau đây?", options: ["A. Nhờ kinh nghiệm nghiên cứu khoa học từ thời còn là sinh viên, Minh đã gây ấn tượng tốt with hội đồng đánh giá.", "B. Từ thời còn là sinh viên, nhờ kinh nghiệm nghiên cứu khoa học của Minh đã gây ấn tượng tốt with hội đồng đánh giá.", "C. Nhờ kinh nghiệm nghiên cứu khoa học từ thời còn là sinh viên, hội đồng đánh giá đã có ấn tượng tốt with Minh.", "D. Từ lúc còn là sinh viên, hội đồng đánh giá đã có ấn tượng tốt về kinh nghiệm nghiên cứu khoa học của Minh."], correctIndex: 0 },
            { id: "q19", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 19: Câu nào sau đây thể hiện phong cách ngôn ngữ sinh hoạt?", options: ["A. Về công tác đào tạo đội ngũ làm báo, Chủ tịch Hồ Chí Minh luôn nhấn mạnh đến tầm quan trọng của việc giáo dục đạo đức, bồi dưỡng tài năng.", "B. Từ điển tiếng Việt giải nghĩa “diễn đàn là nơi để nhiều người có thể phát biểu ý kiến một cách công khai và rộng rãi”.", "C. Xem lại những quan điểm mà tôi đã trình bày trong báo cáo hơn 20 trang in đó, thì thấy cơ bản đến nay vẫn đúng.", "D. Trong xã hội hiện đại, báo chí là kênh truyền thông hữu hiệu, kết nối mọi thành viên trong cộng đồng."], correctIndex: 2 },
            { id: "q20", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 20: “Thằng em thì hay hỏi\nKhông kể chuyện như anh\n(Tuy con, má chẳng sinh\nCon vẫn quen gọi má)\n- Má ơi ai sinh cá\nAi làm ra cái kem\nĐêm sao lại màu đen\nBan ngày sao màu trắng?…”.\n(Xuân Quỳnh, Cắt nghĩa)\nTại sao nhà thơ lại lựa chọn sử dụng cụm từ chêm xen thay vì viết dưới dạng một câu riêng biệt?", options: ["A. Để làm gián đoạn mạch kể chuyện chính.", "B. Để làm nổi bật tầm quan trọng của mối quan hệ giữa má và con.", "C. Để thể hiện triết lý sống đề cao tính nhân văn.", "D. Để bổ sung thông tin và tạo cảm giác tự nhiên, gần gũi."], correctIndex: 3 },

            // Reading Group 1
            {
                id: "reading_21_25",
                section: "SỬ DỤNG NGÔN NGỮ",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời câu từ 21 đến 25</strong><br><br>(1) Chạy dọc theo kênh Tàu Hủ, bến Bình Đông xưa, nhờ giao thông thủy lộ thuận tiện, cộng with cư dân bản địa và làng Minh Hương phát triển sầm uất, đã thành nơi tụ hội ghe thuyền từ khắp các tỉnh miền Tây và cả Nam Bộ, khiến khu vực này dần cực thịnh trong buôn bán và xuất khẩu lúa gạo.<br><br>(2) Dựa theo những ghi chép thì tên gọi kênh Tàu Hủ có khá nhiều lý giải. “Ký ức lịch sử về Sài Gòn và vùng phụ cận” của Trương Vĩnh Ký (Nguyễn Đình Đầu dịch, NXB Trẻ) có đoạn: “Hai bên bờ rạch Chợ Lớn là hai dãy phố lớn bằng gạch gọi là Tàu khậu, để cho người Hoa từ Trung Quốc hằng năm đi ghe biển tới thuê. Họ đem hàng hóa chứa trong các phố đó, hoặc để bán sỉ, bán lẻ khi lưu trú tại Sài Gòn”. “Tàu khậu” ở đây là ngữ âm của người Triều Châu, nghĩa là “nhà gạch” (thổ khố), phương ngữ “tàu khậu” bị biến âm dần trở thành “tàu hủ”. Một lý giải khác bắt nguồn từ hình dáng của dòng kênh, do có những đoạn thắt như cổ hũ, đọc lâu dần trại ra thành âm “tàu hũ, tàu hủ” như ngày nay.<br><br>(3) Nhắc đến bến Bình Đông, không thể không đề cập đến các kho, vựa - chành (phương ngữ của người Triều Châu, nghĩa là bến, bãi), nhà máy tên tuổi như kho Hữu Thành with sáu cửa, nhà máy xay lúa Phong Thạnh with công suất lên đến 500 tấn/ngày.<br><br>(4) Còn về diện mạo phố xá, kiến trúc nhà ở đặc trưng ở bến Bình Đông mang hình thái thuộc địa with các chi tiết trang trí chạy chỉ nổi thạch cao, lan can sắt mỹ nghệ, ngói tây, cửa lá sách… có công năng dùng để buôn bán (tầng trệt) và cư ngụ (tầng trên). Với sự phát triển của nhịp sống đô thị, cả bến Bình Đông hiện chỉ còn sót lại lác đác dãy nhà cổ liên kế gồm từng cụm ba gian, năm gian, bảy gian… nằm cách nhau một khoảng trống bằng with bề ngang của từng gian nhà gần chân cầu Máy Rượu.<br><br>(5) Qua thời gian, những cư dân gốc của dãy phố này cũng lần lượt ra đi. Những khoảng trống giữa các dãy nhà được người đến sau tận dụng, xây nối thành những căn nhà phố mới with kiến trúc “phá bĩnh” - giữa các dãy nhà ngói đỏ điểm xuyết một “gạch nối” là căn nhà hiện đại, mái đúc - chẳng ăn nhập gì with những căn nhà vốn mang nét cổ kính từ hàng trăm năm nay.<br><i>(Nguyễn Đình, Chuyện nhỏ ở Chợ Lớn)</i>",
                subQuestions: [
                    { id: "q21", text: "Câu 21: Thông tin của đoạn (2) được tổ chức theo kiểu gì?", options: ["A. Theo trật tự thời gian.", "B. Theo trật tự không gian.", "C. Theo kiểu quan hệ nhân quả.", "D. Theo kiểu liệt kê đối tượng."], correctIndex: 3 },
                    { id: "q22", text: "Câu 22: Việc đề cập đến các kho, vựa, nhà máy tên tuổi ở đoạn (3) có vai trò gì trong việc thể hiện nội dung chính của văn bản?", options: ["A. Góp phần làm rõ đặc trưng của hoạt động sản xuất ở bến Bình Đông.", "B. Góp phần làm rõ đặc trưng của hoạt động kinh tế ở bến Bình Đông.", "C. Góp phần làm rõ đặc trưng của hoạt động giao thông ở bến Bình Đông.", "D. Góp phần làm rõ đặc trưng của hoạt động nghề nghiệp của người dân ở bến Bình Đông."], correctIndex: 1 },
                    { id: "q23", text: "Câu 23: Thái độ của tác giả thể hiện trong đoạn (5) là gì?", options: ["A. Tỏ ra khách quan vì những giá trị xưa, cũ sẽ dần bị thay thế theo thời gian.", "B. Tiếc nuối vì sự mai một của những kiến trúc cổ theo thời gian.", "C. Thích thú vì những căn nhà hiện đại là sự điểm xuyết cho kiến trúc cổ.", "D. Tiếc nhớ những cư dân gốc của dãy phố ở bến Bình Đông."], correctIndex: 1 },
                    { id: "q24", text: "Câu 24: Nhận định nào sau đây là phù hợp khi nói về chủ đề của văn bản trên?", options: ["A. Vai trò của bến Bình Đông trong không gian Chợ Lớn.", "B. Nguồn gốc hình thành bến Bình Đông trong lịch sử.", "C. Đặc điểm của bến Bình Đông trong quá khứ.", "D. Vị trí địa lý giúp bến Bình Đông thành nơi mua bán lúa gạo sầm uất."], correctIndex: 0 },
                    { id: "q25", text: "Câu 25: Dòng nào dưới đây không trình bày tác động mà văn bản có thể mang đến cho người đọc?", options: ["A. Nhận thức rõ hơn về giá trị văn hóa, lịch sử của bến Bình Đông.", "B. Trân trọng những giá trị di sản mà cha ông đã để lại.", "C. Hoài niệm, tiếc nuối with những giá trị xưa cũ đang dần mai một.", "D. Hiểu rõ hơn về những thách thức của công tác bảo tồn văn hóa."], correctIndex: 3 }
                ]
            },

            // Reading Group 2
            {
                id: "reading_26_30",
                section: "SỬ DỤNG NGÔN NGỮ",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời câu từ 26 đến 30</strong><br><br>(1) Học văn là học tha nhân mà cũng đồng thời là học bản thân ta. Ta học bảng tuần hoàn Mendeleev là học tri thức do nhà bác học cung cấp. Còn ta học tác phẩm của L. Tolstoi là vừa học những tâm hồn Nga yêu chuộng hòa bình, chán ghét chiến tranh, vừa học tiếng vang của nó vào tâm hồn ta, xem cách ta bắt lấy và đón nhận tín hiệu từ tác phẩm đó. Nếu ta chỉ thâu nhận nội dung và các thủ pháp nghệ thuật trong tiểu thuyết như các nguyên tố hóa học của bảng tuần hoàn thì mãi mãi ta không hiểu gì văn học mà cũng không hiểu gì bản thân ta.<br><br>(2) Học văn là học kinh nghiệm làm người ở đời để chính mình tự quyết lấy cuộc đời mình. Vì không ai có thể thay ta đưa ra lời giải bài toán cuộc đời ta. Người học văn vì tiếp xúc with nhiều cuộc đời trong sách vở nên có thể lúng túng, lưỡng lự, phân vân và băn khoăn khi va chạm with cuộc đời thực tế. Ta tham khảo từ những cuộc đời đó để rồi đưa ra giải pháp của riêng ta.<br><br>(3) Học văn là học cách ứng xử with quá khứ, đối mặt with hiện tại và dự báo cho tương lai. Vì vậy mà chúng ta cần cả văn chương dấn thân lẫn văn chương viễn mơ, cần cả tiểu thuyết lịch sử, tiểu thuyết hiện thực lẫn tiểu thuyết viễn tưởng. Học văn là để mở rộng chiều kích cuộc đời ta, để ta không biến thành “con người một chiều kích” như Herbert Marcuse cảnh báo từ những năm 60 thế kỷ trước.<br><br>(4) Học văn là học sống ở đời giữa muôn người cũng đồng thời là học làm người tự do lựa chọn. Theo tinh thần của Jean-Paul Sartre, con người bị buộc phải tự do, có tự do mới có lựa chọn. Lựa chọn chỉ có ý nghĩa khi lựa chọn trong tự do. Nhưng tự do của ta không đối lập with tự do của người khác, tự do của ta chỉ có ý nghĩa khi hiện hữu cùng tự do của người khác.<br><i>(Huỳnh Như Phương, Hồi âm từ phương Nam)</i>",
                subQuestions: [
                    { id: "q26", text: "Câu 26: Trong đoạn (2), câu nào chứa luận điểm?", options: ["A. Học văn là học kinh nghiệm làm người ở đời để chính mình tự quyết lấy cuộc đời mình.", "B. Vì không ai có thể thay ta đưa ra lời giải bài toán cuộc đời ta.", "C. Người học văn vì tiếp xúc with nhiều cuộc đời trong sách vở nên có thể lúng túng, lưỡng lự, phân vân và băn khoăn khi va chạm with cuộc đời thực tế.", "D. Ta tham khảo từ những cuộc đời đó để rồi đưa ra giải pháp của riêng ta."], correctIndex: 0 },
                    { id: "q27", text: "Câu 27: Trong đoạn (3), cụm từ “con người một chiều kích” được sử dụng theo biện pháp tu từ nào?", options: ["A. Nhân hóa.", "B. So sánh.", "C. Ẩn dụ.", "D. Nói quá."], correctIndex: 2 },
                    { id: "q28", text: "Câu 28: Việc tác giả nhắc đến các tên tuổi “L. Tolstoi, Herbert Marcuse” ở đoạn (1) và đoạn (3) nhằm mục đích gì?", options: ["A. Giới thiệu vấn đề.", "B. Giải thích vấn đề.", "C. Chứng minh vấn đề.", "D. Phản biện vấn đề."], correctIndex: 2 },
                    { id: "q29", text: "Câu 29: Tác giả thể hiện quan điểm nào trong bài viết?", options: ["A. Việc học môn văn cũng giống như việc học môn hóa, bồi đắp lòng hiếu tri nơi người học.", "B. Sự lúng túng, lưỡng lự và băn khoăn của người học văn khi va chạm with cuộc đời là điều cần tránh.", "C. Hình mẫu “con người một chiều kích” là đối tượng siêu việt mà người học văn cần trở thành.", "D. Học văn là hành trình kết hợp giữa tri nhận, phản tư và điều chỉnh để hoàn thiện con người."], correctIndex: 3 },
                    { id: "q30", text: "Câu 30: Ý nghĩa nào của việc học văn không được đề cập trong văn bản?", options: ["A. Mở ra cho con người một hành trình tự hiểu biết bản thân và người khác.", "B. Bồi đắp con người sự hiểu biết và mẫn tiệp của tâm hồn phong phú.", "C. Giữ vai trò như một nghi lễ bắt buộc, đánh dấu sự trưởng thành của con người.", "D. Hướng đến sự hình thành ý thức tự do của mỗi người."], correctIndex: 2 }
                ]
            },
            // Questions 31-45
            { id: "q31", section: "1.2. TIẾNG ANH", text: "Câu 31: Jane was careful. She didn't start the test until she _____ all the instructions.", options: ["A. read", "B. reads", "C. had read", "D. had been reading"], correctIndex: 2 },
            { id: "q32", section: "1.2. TIẾNG ANH", text: "Câu 32: The organizers had to call _____ the concert because of insufficient attendance.", options: ["A. on", "B. off", "C. out", "D. in"], correctIndex: 1 },
            { id: "q33", section: "1.2. TIẾNG ANH", text: "Câu 33: Typhoon Yagi slammed Asia in August 2024 with _____ rain, causing severe flooding.", options: ["A. too much", "B. too many", "C. plentiful of", "D. a large number of"], correctIndex: 0 },
            { id: "q34", section: "1.2. TIẾNG ANH", text: "Câu 34: The weather today is _____ than yesterday, so you should wear a jacket if you go out.", options: ["A. cold", "B. much cold", "C. more cold", "D. colder"], correctIndex: 3 },
            { id: "q35", section: "1.2. TIẾNG ANH", text: "Câu 35: We need more _____ teachers to improve the quality of education.", options: ["A. qualify", "B. qualified", "C. qualifying", "D. qualification"], correctIndex: 1 },
            { id: "q36", section: "1.2. TIẾNG ANH", text: "Câu 36: Each of the following sentences has one error (A, B, C, or D). Find it.\nMathematics, <u>which</u> many students believe <u>is</u> too difficult, actually <u>require</u> logical thinking <u>rather than</u> memorization.", options: ["A. which", "B. is", "C. require", "D. rather than"], correctIndex: 2 },
            { id: "q37", section: "1.2. TIẾNG ANH", text: "Câu 37: My class visited <u>the</u> museum in Paris <u>which</u> is famous <u>for</u> its <u>collection</u> of ancient paintings.", options: ["A. the", "B. which", "C. for", "D. collection"], correctIndex: 1 },
            { id: "q38", section: "1.2. TIẾNG ANH", text: "Câu 38: Ms. Brown <u>is worried</u> <u>about</u> her <u>students's</u> ability to pass the <u>coming</u> graduation exams.", options: ["A. is worried", "B. about", "C. students's", "D. coming"], correctIndex: 0 },
            { id: "q39", section: "1.2. TIẾNG ANH", text: "Câu 39: Elephants, <u>that</u> <u>are</u> my niece's favorite animal, are <u>among</u> the <u>smartest</u> animals.", options: ["A. that", "B. are", "C. among", "D. smartest"], correctIndex: 0 },
            { id: "q40", section: "1.2. TIẾNG ANH", text: "Câu 40: Jane <u>said</u> that her parents wanted <u>hers</u> to marry someone <u>that</u> they <u>trusted</u>.", options: ["A. said", "B. hers", "C. that", "D. trusted"], correctIndex: 1 },
            { id: "q41", section: "1.2. TIẾNG ANH", text: "Câu 41: Which of the following best restates each of the given sentences?\nThe shop is currently crowded possibly because its new products are very popular.", options: ["A. The shop's large number of customers is definitely the result of its new products.", "B. It is certain that customers always love the shop's new and popular products.", "C. The popularity of the shop's new products might be attracting many customers.", "D. Customers visit the shop because it is always filled with popular products."], correctIndex: 2 },
            { id: "q42", section: "1.2. TIẾNG ANH", text: "Câu 42: The meeting was delayed because the marketing manager arrived late.", options: ["A. The meeting would not be rescheduled if the marketing manager had not arrived late.", "B. The meeting would have been delayed if the marketing manager had not arrived on time.", "C. Unless the marketing manager arrived late, the meeting would not have been postponed.", "D. The meeting would have started on time if the marketing manager had not been late."], correctIndex: 3 },
            { id: "q43", section: "1.2. TIẾNG ANH", text: "Câu 43: This film is interesting, but the other two films are much more interesting.", options: ["A. This is the least interesting film out of the three.", "B. Of the three films, this film is the most interesting.", "C. This film is more boring than the other two films.", "D. The other two films are less boring than this one."], correctIndex: 0 },
            { id: "q44", section: "1.2. TIẾNG ANH", text: "Câu 44: Close the windows to prevent the documents from being blown away.", options: ["A. The documents would be blown away if the windows had not been closed.", "B. If you don't close the windows, you cannot find the blown documents.", "C. The windows should be closed so that the documents are not blown away.", "D. By closing the windows, the documents will not be blown away slowly."], correctIndex: 2 },
            { id: "q45", section: "1.2. TIẾNG ANH", text: "Câu 45: Jane said to her husband, \"Don't forget to lock the door before you go to bed.\"", options: ["A. Jane's husband asked her not to forget to lock the door before going to bed.", "B. Jane reminded her husband to lock the door before he went to bed.", "C. Jane said to her husband that he must lock the door before going to bed.", "D. Jane told her husband not to leave the door locked before he went to bed."], correctIndex: 1 },
            {
                id: "reading_46_52",
                section: "1.2. TIẾNG ANH",
                type: "reading_group",
                passage: "<strong>Questions 46-52: Read the passage carefully.</strong><br><br>1 A former teacher, Butler, wanted a change in her life. After many years of working in the U.S., she dreamed of living somewhere quiet, peaceful, and affordable. She discovered Latronico, a small mountain village in southern Italy's Basilicata region. <b>There</b>, she was able to buy a charming old house at a very low price compared to what she would pay in a big city. For her, this was the beginning of a new chapter filled with hope and peace.<br>2 Buying the house was easier than she had expected. Latronico has a special program called “La Tua Casa a Latronico” (Your Home in Latronico). The program helps people purchase and restore empty houses that once belonged to families who moved away. This made the process simple and welcoming for newcomers. It is part of a wider trend across Italy, where small towns invite people to settle and stop villages from becoming empty.<br>3 After moving in, Butler began to work on her house. Many of these old houses need improvements, and hers was no different. She <b>fixed</b> the floors, painted the walls, and hired local workers to upgrade the kitchen and bathrooms. With each improvement, the house felt more like home. She enjoyed the process because it allowed her to be creative while also supporting local workers. In this way, she was not just fixing her house but also joining the community.<br>4 Life in Latronico soon became more than just home renovations. She loved walking through the quiet streets, greeting neighbors, and visiting small shops. People in the village were warm and friendly, making her feel part of the community very quickly. Simple moments – like buying bread at the bakery or sitting in the town square – became joyful experiences. She felt that her new life was slower, healthier, and more connected compared to her old stressful, fast-paced city life. Her story shows how affordable housing programs can give people a second chance.",
                subQuestions: [
                    { id: "q46", text: "Câu 46: What is the passage mainly about?", options: ["A. A former teacher's new life in an Italian village", "B. “La Tua Casa a Latronico,” a housing program", "C. How to fix old houses in an Italian village", "D. Life in Latronico for Italians who love peace"], correctIndex: 0 },
                    { id: "q47", text: "Câu 47: According to paragraph 1, what does the word <b>There</b> refer to?", options: ["A. mountain", "B. Italy", "C. Latronico", "D. southern Basilicata"], correctIndex: 2 },
                    { id: "q48", text: "Câu 48: In paragraph 2, which of the following is NOT a characteristic of “La Tua Casa a Latronico”?", options: ["A. It sells the houses that are no longer resided in.", "B. It provides easy opportunities for newcomers.", "C. It started a new housing trend all over Italy.", "D. It keeps some villages from being deserted."], correctIndex: 2 },
                    { id: "q49", text: "Câu 49: What word can best replace <b>fixed</b> as used in paragraph 3?", options: ["A. strengthened", "B. repaired", "C. changed", "D. polished"], correctIndex: 1 },
                    { id: "q50", text: "Câu 50: In paragraph 3, what can be inferred about the way Butler supported local workers?", options: ["A. She helped them to be creative.", "B. She joined their local community.", "C. She created repair jobs for them.", "D. She improved their building skills."], correctIndex: 2 },
                    { id: "q51", text: "Câu 51: In paragraph 4, what is stated about people in Latronico?", options: ["A. They were kind and welcoming.", "B. They were quiet but friendly.", "C. They loved greeting their neighbors.", "D. They were quick at making friends."], correctIndex: 0 },
                    { id: "q52", text: "Câu 52: In paragraph 4, what did Butler say about her life before she came to Latronico?", options: ["A. It was totally carefree.", "B. It was quick-moving.", "C. It suited old people more.", "D. It had nothing but stress."], correctIndex: 1 }
                ]
            },
            {
                id: "reading_53_60",
                section: "1.2. TIẾNG ANH",
                type: "reading_group",
                passage: "<strong>Questions 53-60: Read the passage carefully.</strong><br><br>1. Climate change is making the world's weather more extreme. Scientists say that regions with hotter air can hold more water, and warmer seas give storms extra strength. This means storms today are often stronger, wetter, and more dangerous than <b>those</b> in the past. These changes are not just predictions for the future - they are already happening and affecting millions of people.<br>2. One big effect is the increase in rainfall and flooding. Typhoons no longer bring only strong winds; they now <b>dump</b> record amounts of water. In 2023, Typhoon Haikui hit Taiwan and later Hong Kong, where it caused the heaviest rainfall in 140 years. Streets, subways, and homes were flooded, and daily life was stopped for many people. This shows how climate change turns storms into water disasters, especially in crowded cities that do not have strong drainage systems.<br>3. Another effect is that typhoons now cause more economic damage. The bigger and more developed cities are, the more expensive it is to repair. Typhoon Doksuri in 2023 is a clear example. It flooded Beijing and other parts of China, destroying homes and farmland. The cost reached more than 28 billion dollars, making it the most expensive typhoon in China's history. Climate change makes such storms more frequent, and urban growth makes the damage higher, a dangerous mix for modern societies.<br>4. A third effect is that storms are stronger than they would be due to climate change. In 2024, <b>scientists</b> studied Typhoon Gaemi and found that its winds were about 9 mph stronger and rainfall 14% heavier because of hotter oceans. They also said climate change made storms like Gaemi 30% more likely. This proves climate change is not just a background factor; it directly increases the power of storms.<br>5. Finally, climate change is making typhoons intensify faster, which gives people less time to prepare. In 2025, Typhoon Kajiki grew very quickly before striking Vietnam. Nearly 600,000 people had to evacuate, and many cities, including Hanoi, were badly flooded. This rapid growth shows how climate change makes storms more dangerous by reducing warning time.<br>6. Countries now need stronger plans, better evacuation systems, and more climate action to protect people in the years ahead.",
                subQuestions: [
                    { id: "q53", text: "Câu 53: The best title of the passage can be _____.", options: ["A. How Typhoons Are Increasing Climate Change", "B. Climate Change and the Rising Power of Storms", "C. Rising Seas, Rising Typhoons: Only in Asia", "D. How the World Is Suffering from Extreme Weathers"], correctIndex: 1 },
                    { id: "q54", text: "Câu 54: The word <b>those</b> in paragraph 1 refers to _____.", options: ["A. scientists", "B. regions", "C. seas", "D. storms"], correctIndex: 3 },
                    { id: "q55", text: "Câu 55: In paragraph 2, the word <b>dump</b> is closest in meaning to _____.", options: ["A. throw away as garbage", "B. drop or release suddenly", "C. pour now and again", "D. sell at a cheap price"], correctIndex: 1 },
                    { id: "q56", text: "Câu 56: According to paragraph 2, crowded cities without strong drainage systems _____.", options: ["A. cause many water disasters for their populations", "B. can develop storms into deadly typhoons", "C. may be the most vulnerable to climate change", "D. suffer from serious flooding caused by storms"], correctIndex: 3 },
                    { id: "q57", text: "Câu 57: In paragraph 3, it is NOT mentioned that _____.", options: ["A. Typhoon Doksuri flooded the entire mainland China", "B. Typhoon Doksuri caused huge economic losses to China", "C. storms similar to Typhoon Doksuri occur more often now", "D. storms are more damaging due to increased urbanization"], correctIndex: 0 },
                    { id: "q58", text: "Câu 58: In paragraph 4, the author mentions <b>scientists</b> in order to _____.", options: ["A. confirm another viewpoint", "B. present two perspectives", "C. validate his/her claim", "D. illustrate a public opinion"], correctIndex: 2 },
                    { id: "q59", text: "Câu 59: It can be inferred from paragraph 4 that Typhoon Gaemi and similar storms _____.", options: ["A. pose higher risks of flooding", "B. are more serious in desert areas", "C. cause huge shortages of power", "D. are a factor of global warming"], correctIndex: 0 },
                    { id: "q60", text: "Câu 60: Paragraphs 2, 3, 4, and 5 present _____ respectively as changes to storms due to climate change.", options: ["A. higher economic losses, serious floods, greater intensity, and higher speed", "B. higher speed, serious floods, higher economic losses, and greater intensity", "C. serious floods, higher economic losses, greater intensity, and higher speed", "D. serious floods, higher speed, higher economic losses, and greater intensity"], correctIndex: 2 }
                ]
            },
            // Questions 61-90
            { id: "q61", section: "PHẦN 2. TOÁN HỌC", text: "Câu 61: Một hình chữ nhật và một hình vuông có cùng chu vi là 24 (đơn vị dài). Biết rằng diện tích hình vuông lớn hơn diện tích hình chữ nhật là 4 (đơn vị diện tích). Hiệu giữa chiều dài và chiều rộng của hình chữ nhật là:", options: ["A. 2.", "B. 4.", "C. 6.", "D. 8."], correctIndex: 1 },
            { id: "q62", section: "PHẦN 2. TOÁN HỌC", text: "Câu 62: Cho phương trình \\(\\sqrt{-x^2+mx} = 2x-1\\) with \\(m\\) là tham số thực. Tập hợp tất cả giá trị của \\(m\\) để phương trình trên vô nghiệm là:", options: ["A. \\(\\left( \\frac{1}{2}; \\infty \\right)\\).", "B. \\(\\left( \\frac{1}{2}; 2 \\right]\\).", "C. \\(\\left( -\\infty; \\frac{1}{2} \\right)\\).", "D. \\((-\\infty; 2)\\)."], correctIndex: 2 },
            { id: "q63", section: "PHẦN 2. TOÁN HỌC", text: "Câu 63: Anh Hùng muốn gửi tiết kiệm để sau 3 năm có 800 triệu đồng mua xe. Biết lãi suất hàng tháng là 0,6%, tiền lãi sinh ra hàng tháng được nhập vào tiền vốn, số tiền gửi hàng tháng là như nhau. Anh Hùng phải gửi ngân hàng mỗi tháng số tiền gần nhất with số tiền nào sau đây:", options: ["A. 19.785.000 đồng.", "B. 19.895.000 đồng.", "C. 19.975.000 đồng.", "D. 19.665.000 đồng."], correctIndex: 1 },
            { id: "q64", section: "PHẦN 2. TOÁN HỌC", text: "Câu 64: Cho \\(a = \\log_2 5\\), \\(b = \\log_5 3\\). Biết \\(\\log_{24} 15 = \\frac{ma+ab}{n+ab}\\) with \\(m\\), \\(n\\) là các số nguyên. Giá trị \\(S = m^2+n^2\\) là:", options: ["A. 2.", "B. 5.", "C. 13.", "D. 10."], correctIndex: 3 },
            { id: "q65", section: "PHẦN 2. TOÁN HỌC", text: "Câu 65: Có 6 thị trấn A, B, C, D, E và F được kết nối with nhau bởi một số tuyến đường. Độ dài tính bằng kilômét của các tuyến đường kết nối giữa các thị trấn được cho kèm theo bảng sau.<br><table class=\"table table-bordered text-center\" style=\"width:auto; margin:10px auto\"><tr><td></td><td>A</td><td>B</td><td>C</td><td>D</td><td>E</td><td>F</td></tr><tr><td>A</td><td>0</td><td>1</td><td>0</td><td>8</td><td>4</td><td>1</td></tr><tr><td>B</td><td>1</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td></tr><tr><td>C</td><td>0</td><td>2</td><td>0</td><td>3</td><td>0</td><td>0</td></tr><tr><td>D</td><td>8</td><td>0</td><td>3</td><td>0</td><td>5</td><td>0</td></tr><tr><td>E</td><td>4</td><td>0</td><td>0</td><td>5</td><td>0</td><td>1</td></tr><tr><td>F</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td></tr></table>Tổng số tuyến đường kết nối các thị trấn with nhau là:", options: ["A. 8.", "B. 6.", "C. 10.", "D. 9."], correctIndex: 3 },
            { id: "q66", section: "PHẦN 2. TOÁN HỌC", text: "Câu 66: Một công ty viễn thông đang lên kế hoạch mở rộng mạng lưới dịch vụ của mình tại một khu vực gồm sáu thị trấn: A, B, C, D, E và F. Để cung cấp dịch vụ internet và điện thoại đến từng thị trấn, công ty cần phải kéo cáp ngầm nối các thị trấn with nhau. Mỗi đoạn cáp nối hai thị trấn có một chi phí nhất định, tùy thuộc vào khoảng cách địa lý và điều kiện địa hình. Sơ đồ dưới đây thể hiện các tuyến cáp có thể xây dựng, cùng with chi phí đi kèm (tính bằng nghìn đô la) cho từng tuyến.<br><br><b>Sơ đồ tuyến cáp (thị trấn: chi phí nghìn đô la):<img src=\"https://i.ibb.co/twSqV6SV/Screenshot-2026-05-14-223438.png\"></b><br>Chi phí tối thiểu (nghìn đô la) mà công ty phải bỏ ra để xây dựng hệ thống cáp sao cho tất cả sáu thị trấn đều được kết nối with nhau là:", options: ["A. 780.", "B. 820.", "C. 760.", "D. 800."], correctIndex: 0 },
            { id: "q67", section: "PHẦN 2. TOÁN HỌC", text: "Câu 67: Tập nghiệm của phương trình \\(\\cos 2x + 3 \\sin x - 2 = 0\\) là:", options: ["A. \\(S = \\left\\{ \\frac{\\pi}{2} + k2\\pi; \\frac{\\pi}{6} + k2\\pi; \\frac{5\\pi}{6} + k2\\pi, k \\in \\mathbb{Z} \\right\\}\\).", "B. \\(S = \\left\\{ \\frac{\\pi}{6} + k2\\pi; \\frac{5\\pi}{6} + k2\\pi, k \\in \\mathbb{Z} \\right\\}\\).", "C. \\(S = \\left\\{ \\frac{\\pi}{2} + k2\\pi; \\frac{\\pi}{3} + k2\\pi; \\frac{2\\pi}{3} + k2\\pi, k \\in \\mathbb{Z} \\right\\}\\).", "D. \\(S = \\left\\{ \\frac{\\pi}{3} + k2\\pi; \\frac{2\\pi}{3} + k2\\pi, k \\in \\mathbb{Z} \\right\\}\\)."], correctIndex: 0 },
            { id: "q68", section: "PHẦN 2. TOÁN HỌC", text: "Câu 68: Cho tam giác ABC có a, b, c lần lượt là độ dài các cạnh đối diện with các đỉnh A, B, C. Biết \\(b(b^2-a^2)=c(a^2-c^2)\\), khi đó số đo của góc A bằng:", options: ["A. \\(30^\\circ\\).", "B. \\(45^\\circ\\).", "C. \\(60^\\circ\\).", "D. \\(120^\\circ\\)."], correctIndex: 2 },
            { id: "q69", section: "PHẦN 2. TOÁN HỌC", text: "Câu 69: Cho hàm số \\(f(x) = \\begin{cases} \\frac{x^2-4}{x-2}, & x \\neq 2 \\\\ m+1, & x = 2 \\end{cases}\\) with m là tham số thực. Giá trị của m để hàm số liên tục tại \\(x_0 = 2\\) là:", options: ["A. \\(m=3\\).", "B. \\(m=2\\).", "C. \\(m=4\\).", "D. \\(m=1\\)."], correctIndex: 0 },
            { id: "q70", section: "PHẦN 2. TOÁN HỌC", text: "Câu 70: Cho hàm số \\(y = x.e^x\\). Tập nghiệm của bất phương trình \\(y'' - y' - y > 0\\) là:", options: ["A. \\((-1; +\\infty)\\).", "B. \\((-\\infty; 1)\\).", "C. \\((1; +\\infty)\\).", "D. \\((-\\infty; -1)\\)."], correctIndex: 1 },
            { id: "q71", section: "PHẦN 2. TOÁN HỌC", text: "Câu 71: Cho hàm số \\(f(x)\\) liên tục trên \\([0; 2]\\) và thoả mãn \\(\\int_{0}^{2} f(x)dx = 7\\). Tính giá trị \\(\\int_{0}^{2} (f(x)-x)dx\\).", options: ["A. 5.", "B. -5.", "C. -3.", "D. 3."], correctIndex: 1 },
            { id: "q72", section: "PHẦN 2. TOÁN HỌC", text: "Câu 72: Xét hàm số \\(y = f(x)\\) có \\(f'(x) = 3x(x-2)\\) và đồ thị \\((C)\\) của nó thì đi qua gốc tọa độ. Tính diện tích phần hình phẳng giới hạn bởi \\((C)\\) và trục hoành.", options: ["A. 0.", "B. \\(-\\frac{27}{4}\\).", "C. 4.", "D. \\(\\frac{27}{4}\\)."], correctIndex: 3 },
            {
                id: "reading_73_74",
                section: "PHẦN 2. TOÁN HỌC",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 73 đến 74</strong><br><br>Để sản xuất mỗi cái bánh loại A cần 200 g bột và 25 g thịt, để sản xuất mỗi bánh loại B cần 100 g bột và 50 g thịt. Số nguyên liệu có sẵn gồm 5 kg bột và 1 kg thịt.",
                subQuestions: [
                    { id: "q73", text: "Câu 73: Gọi \\(x\\) là số bánh loại A và \\(y\\) là số bánh loại B. Hệ bất phương trình biểu diễn các ràng buộc nguyên liệu là:", options: ["A. \\(\\begin{cases} 200x + 100y \\le 5000 \\\\ 25x + 50y \\le 1000 \\\\ x, y \\ge 0 \\end{cases}\\)", "B. \\(\\begin{cases} 200x + 100y \\le 1000 \\\\ 25x + 50y \\le 5000 \\\\ x, y \\ge 0 \\end{cases}\\)", "C. \\(\\begin{cases} 200x + 25y \\le 5000 \\\\ 100x + 50y \\le 1000 \\\\ x, y \\ge 0 \\end{cases}\\)", "D. \\(\\begin{cases} 200x + 25y \\le 1000 \\\\ 100x + 50y \\le 5000 \\\\ x, y \\ge 0 \\end{cases}\\)"], correctIndex: 0 },
                    { id: "q74", text: "Câu 74: Giả sử lợi nhuận thu được từ mỗi chiếc bánh loại A là 10 nghìn đồng và từ loại B là 15 nghìn đồng. Lợi nhuận tối đa (nghìn đồng) có thể thu được là:", options: ["A. 250.", "B. 300.", "C. 350.", "D. 400."], correctIndex: 2 }
                ]
            },
            {
                id: "reading_75_76",
                section: "PHẦN 2. TOÁN HỌC",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 75 đến 76</strong><br><br>Cho cấp số cộng \\((u_n)\\) xác định bởi:<br>\\(\\begin{cases} u_1 + u_5 = 12 \\\\ u_2 + u_6 = 16 \\end{cases}\\)",
                subQuestions: [
                    { id: "q75", text: "Câu 75: Công sai \\(d\\) của cấp số cộng \\((u_n)\\) là:", options: ["A. \\(d=1\\).", "B. \\(d=2\\).", "C. \\(d=3\\).", "D. \\(d=4\\)."], correctIndex: 1 },
                    { id: "q76", text: "Câu 76: Tính giá trị giới hạn \\(\\lim_{n \\to +\\infty} \\frac{5u_n - 3}{n + 2}\\).", options: ["A. 0.", "B. 5.", "C. 10.", "D. \\(+\\infty\\)."], correctIndex: 2 }
                ]
            },
            {
                id: "reading_77_78",
                section: "PHẦN 2. TOÁN HỌC",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 77 đến 78</strong><br><br>Trong không gian tọa độ \\(Oxyz\\), cho điểm \\(A(2; 2; -3)\\) và hai mặt phẳng \\((P): 2x + y - 2z = 0\\), \\((Q): 2x - y + z = 0\\).",
                subQuestions: [
                    { id: "q77", text: "Câu 77: Khoảng cách từ điểm A đến mặt phẳng (P) bằng:", options: ["A. 3.", "B. 4.", "C. 2.", "D. 6."], correctIndex: 1 },
                    { id: "q78", text: "Câu 78: Mặt phẳng đi qua A và vuông góc with (P) và (Q) có phương trình:", options: ["A. \\(x + 6y + 4z - 2 = 0\\).", "B. \\(x - 6y - 4z - 2 = 0\\).", "C. \\(x - 6y + 4z + 22 = 0\\).", "D. \\(x + 6y - 4z - 26 = 0\\)."], correctIndex: 0 }
                ]
            },
            {
                id: "reading_79_81",
                section: "PHẦN 2. TOÁN HỌC",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 79 đến 81</strong><br><br>Cho hàm số \\(y = x^3 - 3x + m\\).",
                subQuestions: [
                    { id: "q79", text: "Câu 79: Với \\(m = 1\\), giá trị lớn của hàm số trên đoạn \\([-2; 2]\\) là:", options: ["A. 4.", "B. 3.", "C. 2.", "D. 1."], correctIndex: 1 },
                    { id: "q80", text: "Câu 80: Tất cả giá trị của \\(m\\) để hàm số nghịch biến trên tập xác định là:", options: ["A. \\(m \\in [-1; 3]\\).", "B. \\(m = 1\\).", "C. \\(m \\in \\left[-\\frac{1}{2}; 4\\right]\\).", "D. \\(m \\in \\varnothing\\)."], correctIndex: 3 },
                    { id: "q81", text: "Câu 81: Tính tổng tất cả giá trị nguyên của tham số \\(m\\) sao cho phương trình \\(-x^3 + 3x = m\\) có 3 nghiệm thực phân biệt.", options: ["A. -1.", "B. 2.", "C. 1.", "D. 0."], correctIndex: 3 }
                ]
            },
            {
                id: "reading_82_84",
                section: "PHẦN 2. TOÁN HỌC",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 82 đến 84</strong><br><br>Một nhà máy có hai lô hàng cần kiểm tra. Lô A có 10 sản phẩm, trong đó có 7 sản phẩm tốt và 3 sản phẩm lỗi. Lô B có 15 sản phẩm, trong đó có 10 sản phẩm tốt và 5 sản phẩm lỗi.",
                subQuestions: [
                    { id: "q82", text: "Câu 82: Từ lô hàng A chọn ngẫu nhiên đồng thời 2 sản phẩm, xác suất để người đó lấy được 2 sản phẩm tốt là:", options: ["A. \\(\\frac{7}{15}\\).", "B. \\(\\frac{1}{5}\\).", "C. \\(\\frac{7}{30}\\).", "D. \\(\\frac{11}{90}\\)."], correctIndex: 0 },
                    { id: "q83", text: "Câu 83: Chọn ngẫu nhiên một lô hàng, rồi từ lô hàng đó chọn ra 2 sản phẩm. Xác suất để lấy được 2 sản phẩm tốt là:", options: ["A. \\(\\frac{94}{105}\\).", "B. \\(\\frac{23}{94}\\).", "C. \\(\\frac{47}{105}\\).", "D. \\(\\frac{49}{94}\\)."], correctIndex: 2 },
                    { id: "q84", text: "Câu 84: Chọn ngẫu nhiên một lô hàng, rồi từ lô hàng đó chọn ra 1 sản phẩm. Biết sản phẩm được chọn là sản phẩm lỗi. Xác suất để lô được chọn là lô B là:", options: ["A. \\(\\frac{9}{19}\\).", "B. \\(\\frac{10}{19}\\).", "C. \\(\\frac{1}{2}\\).", "D. \\(\\frac{3}{5}\\)."], correctIndex: 1 }
                ]
            },
            {
                id: "reading_85_87",
                section: "PHẦN 2. TOÁN HỌC",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 85 đến 87</strong><br><br>Trong mặt phẳng tọa độ \\(Oxy\\), cho tam giác \\(ABC\\) có tọa độ các đỉnh lần lượt là \\(A(-5; 1)\\), \\(B(1; 5)\\), \\(C(7; -3)\\).",
                subQuestions: [
                    { id: "q85", text: "Câu 85: Gọi \\(G\\) là trọng tâm của tam giác \\(ABC\\). Khoảng cách \\(OG\\) là:", options: ["A. \\(\\sqrt{2}\\).", "B. \\(\\sqrt{3}\\).", "C. 1.", "D. 2."], correctIndex: 0 },
                    { id: "q86", text: "Câu 86: Gọi \\(M\\) là trung điểm cạnh \\(AC\\). Gọi \\(N\\) là điểm sao cho \\(BMCN\\) là hình bình hành. Tổng hoành độ và tung độ của \\(N\\) bằng:", options: ["A. 7.", "B. 8.", "C. 9.", "D. 10."], correctIndex: 3 },
                    { id: "q87", text: "Câu 87: Gọi \\(D\\) là điểm nằm trên cạnh \\(BC\\) sao cho đường tròn đường kính \\(DB\\) tiếp xúc trục tung. Hiệu hoành độ và tung độ của \\(D\\) là:", options: ["A. 2.", "B. 2,5.", "C. 3.", "D. 3,5."], correctIndex: 2 }
                ]
            },
            {
                id: "reading_88_90",
                section: "PHẦN 2. TOÁN HỌC",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 88 đến 90</strong><br><br>Cho hình chóp \\(S.ABCD\\) có đáy là hình vuông cạnh \\(a\\). Hình chiếu vuông góc \\(H\\) của \\(S\\) lên mặt đáy \\((ABCD)\\) là trung điểm của \\(AB\\). Biết \\(SH = a\\).",
                subQuestions: [
                    { id: "q88", text: "Câu 88: Thể tích hình chóp \\(S.BHD\\) là:", options: ["A. \\(\\frac{1}{6}a^3\\).", "B. \\(\\frac{1}{12}a^3\\).", "C. \\(\\frac{\\sqrt{2}}{12}a^3\\).", "D. \\(\\frac{\\sqrt{3}}{12}a^3\\)."], correctIndex: 1 },
                    { id: "q89", text: "Câu 89: Chu vi tam giác \\(SBD\\) là:", options: ["A. \\(\\frac{2\\sqrt{2}+3+\\sqrt{5}}{2}a\\).", "B. \\(\\frac{2\\sqrt{2}+\\sqrt{3}+\\sqrt{5}}{2}a\\).", "C. \\(\\frac{2\\sqrt{2}+2\\sqrt{5}}{2}a\\).", "D. \\(\\frac{2\\sqrt{2}+\\sqrt{3}+5}{2}a\\)."], correctIndex: 0 },
                    { id: "q90", text: "Câu 90: Khoảng cách từ \\(H\\) đến mặt phẳng \\((SBD)\\) xấp xỉ:", options: ["A. 0,5a.", "B. 0,66a.", "C. 0,33a.", "D. 0,25a."], correctIndex: 2 }
                ]
            },
            // Questions 91-120
            {
                id: "reading_91_93",
                section: "PHẦN 3. TƯ DUY KHOA HỌC",
                type: "reading_group",
                passage: "<strong>3.1. LOGIC, PHÂN TÍCH SỐ LIỆU</strong><br><strong>Dựa vào thông tin dưới đây để trả lời các câu từ 91 đến 93</strong><br><br>Nhân dịp tổ chức buổi lễ 20/11, đội văn nghệ của trường định sẽ biểu diễn 5 tiết mục là: đơn ca nam, đơn ca nữ, song ca nam nữ, tốp ca học sinh và tốp ca giáo viên. Thứ tự các tiết mục tuân theo các ràng buộc sau đây:<br>- Song ca nam nữ phải được biểu diễn trước đơn ca nữ.<br>- Tốp ca học sinh phải được biểu diễn trước tốp ca giáo viên.<br>- Đơn ca nam và tốp ca học sinh phải được biểu diễn liền kề nhau.",
                subQuestions: [
                    { id: "q91", text: "Câu 91: Có bao nhiêu tiết mục có thể biểu diễn ở vị trí thứ hai?", options: ["A. năm.", "B. bốn.", "C. ba.", "D. hai."], correctIndex: 2 },
                    { id: "q92", text: "Câu 92: Nếu tốp ca giáo viên được biểu diễn trước đơn ca nữ thì điều nào sau đây không đúng?", options: ["A. Đơn ca nam được biểu diễn ở vị trí thứ hai.", "B. Đơn ca nữ được biểu diễn ở vị trí thứ tư.", "C. Song ca nam nữ được biểu diễn đầu tiên.", "D. Tốp ca học sinh được biểu diễn đầu tiên."], correctIndex: 1 },
                    { id: "q93", text: "Câu 93: Nếu đơn ca nữ và tốp ca giáo viên không được biểu diễn kề nhau thì điều nào sau đây có thể đúng?", options: ["A. Đơn ca nam được biểu diễn cuối cùng.", "B. Đơn ca nữ được biểu diễn thứ tư.", "C. Song ca nam nữ biểu diễn thứ ba.", "D. Tốp ca học sinh biểu diễn thứ hai."], correctIndex: 3 }
                ]
            },
            {
                id: "reading_94_96",
                section: "PHẦN 3. TƯ DUY KHOA HỌC",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 94 đến 96</strong><br><br>Ban cán sự của lớp sẽ được thành lập gồm đúng năm đại diện, trong đó có một người giữ vai trò lớp trưởng. Các thành viên này được lựa chọn từ hai nhóm: nhóm học sinh nam gồm F, G, J, K, M và nhóm học sinh nữ gồm P, Q, R, S. Các điều kiện lựa chọn ban cán sự phải được thỏa mãn như sau:<br>- Trong mỗi nhóm (nam và nữ) phải có ít nhất 2 đại diện.<br>- Lớp trưởng phải thuộc nhóm có đúng 2 đại diện trong ban cán sự.<br>- Nếu F được chọn thì Q cũng phải được chọn.<br>- Nếu G được chọn thì K cũng phải được chọn.<br>- Nếu J hoặc M được chọn thì người kia cũng phải được chọn.<br>- M và P không thể cùng được chọn.",
                subQuestions: [
                    { id: "q94", text: "Câu 94: Trong số các lựa chọn dưới đây, tổ hợp nào là một lựa chọn hợp lệ các đại diện cho ban cán sự lớp?", options: ["A. F, G, Q, R, S.", "B. F, P, Q, R, S.", "C. J, K, M, Q, S.", "D. J, M, P, Q, S."], correctIndex: 2 },
                    { id: "q95", text: "Câu 95: Nếu cả F lẫn K đều không được chọn, thì điều nào sau đây có thể đúng?", options: ["A. G được chọn.", "B. P được chọn.", "C. J là lớp trưởng.", "D. Q là lớp trưởng."], correctIndex: 2 },
                    { id: "q96", text: "Câu 96: Nếu lớp trưởng là một nữ sinh, thì điều nào sau đây phải đúng?", options: ["A. Nếu G được chọn thì Q cũng được chọn.", "B. Nếu G được chọn thì R cũng được chọn.", "C. Nếu J được chọn thì F cũng được chọn.", "D. Nếu J được chọn thì Q cũng được chọn."], correctIndex: 0 }
                ]
            },
            {
                id: "reading_97_99",
                section: "PHẦN 3. TƯ DUY KHOA HỌC",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 97 đến 99</strong><br><br>Hai biểu đồ tròn dưới đây cung cấp thông tin về thị phần điện thoại của công ty X và Y trong các năm 2015 và 2025.<br><br><b>Biểu đồ 1 (2015):</b> X: 38%, Y: 20%, Khác: 42%<br><b>Biểu đồ 2 (2025):</b> X: 66%, Y: 28%, Khác: 6%<br><br>Biết rằng tổng số điện thoại bán ra năm 2015 là 50 triệu sản phẩm và năm 2025 là 95 triệu sản phẩm.",
                subQuestions: [
                    { id: "q97", text: "Câu 97: Số lượng điện thoại công ty X bán ra năm 2025 tăng bao nhiêu phần trăm so with năm 2015?", options: ["A. 180%.", "B. 205%.", "C. 230%.", "D. 250%."], correctIndex: 2 },
                    { id: "q98", text: "Câu 98: Giả sử số lượng điện thoại công ty X bán ra tăng theo tốc độ tăng trưởng kép hằng năm (CAGR) không đổi trong giai đoạn 2015-2025. Biết công thức CAGR là \\(CAGR = \\left(\\frac{\\text{Giá trị cuối kỳ}}{\\text{Giá trị đầu kỳ}}\\right)^{\\frac{1}{n}} - 1\\) with n là số năm. CAGR của công ty X xấp xỉ:", options: ["A. 10,3%/năm.", "B. 11,7%/năm.", "C. 12,7%/năm.", "D. 14,1%/năm."], correctIndex: 2 },
                    { id: "q99", text: "Câu 99: Giả sử từ năm 2024 đến năm 2025, tổng số điện thoại bán ra trên thị trường tăng 11%, và số lượng điện thoại công ty Y bán ra tăng 5%. Thị phần công ty Y trong năm 2024 bằng xấp xỉ bao nhiêu phần trăm:", options: ["A. 26,4%.", "B. 29,6%.", "C. 31,1%.", "D. 36,4%."], correctIndex: 1 }
                ]
            },
            {
                id: "reading_100_102",
                section: "PHẦN 3. TƯ DUY KHOA HỌC",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 100 đến 102</strong><br><br>Bảng tần số cân nặng khi sinh (đơn vị kilôgam) của 1.500 trẻ sơ sinh được cho như sau:<br><table class=\"table table-bordered text-center\" style=\"width:auto; margin:10px auto\"><tr><th>Khoảng cân nặng (kg)</th><th>Tần số f</th></tr><tr><td>0,0-1,0</td><td>1</td></tr><tr><td>1,0-2,0</td><td>6</td></tr><tr><td>2,0-2,5</td><td>60</td></tr><tr><td>2,5-3,0</td><td>280</td></tr><tr><td>3,0-3,5</td><td>820</td></tr><tr><td>3,5-4,0</td><td>320</td></tr><tr><td>4,0-5,0</td><td>10</td></tr><tr><td>5,0-6,0</td><td>3</td></tr></table>",
                subQuestions: [
                    { id: "q100", text: "Câu 100: Khoảng chứa trung vị là:", options: ["A. 2,0-2,5.", "B. 2,5-3,0.", "C. 3,0-3,5.", "D. 3,5-4,0."], correctIndex: 2 },
                    { id: "q101", text: "Câu 101: Trung vị cân nặng (kg) của 1.500 trẻ sơ sinh xấp xỉ:", options: ["A. 3,18.", "B. 3,23.", "C. 3,25.", "D. 3,30."], correctIndex: 2 },
                    { id: "q102", text: "Câu 102: Cho \\(\\overline{x}\\) và \\(s\\) lần lượt là trung bình mẫu và độ lệch chuẩn mẫu của cân nặng 1.500 trẻ sơ sinh. Giá trị (kg) của \\(\\overline{x} - s\\) xấp xỉ:", options: ["A. 2,80.", "B. 2,90.", "C. 3,00.", "D. 3,10."], correctIndex: 0 }
                ]
            },
            {
                id: "reading_103_105",
                section: "PHẦN 3. TƯ DUY KHOA HỌC",
                type: "reading_group",
                passage: "<strong>3.2. SUY LUẬN KHOA HỌC</strong><br><strong>Dựa vào thông tin dưới đây để trả lời các câu từ 103 đến 105</strong><br><br>Áp suất hơi bão hòa của chất lỏng dễ bay hơi là áp suất hơi của nó khi tốc độ bay hơi của chất lỏng bằng tốc độ ngưng tụ của hơi ở nhiệt độ nhất định. Chất càng dễ bay hơi thì áp suất hơi bão hòa cao và khi nhiệt độ tăng, áp suất hơi bão hòa cũng tăng. Liên hệ giữa áp suất hơi bão hòa của dung dịch (\\(P_A\\)) và áp suất hơi bão hòa của dung môi tinh chất \\(P_A^0\\) như sau:<br>\\(P_A = P_A^0 \\times \\frac{n_A}{n_A + n_B}\\)<br>Trong đó \\(n_A\\) và \\(n_B\\) lần lượt là số mol của dung môi A và chất tan B.<br>Hòa tan 24 gam urea \\((NH_2)_2CO\\) vào 200 gam nước được dung dịch X. Biết urea là chất tan không bay hơi và khối lượng phân tử của urea là 60 g/mol. Khối lượng phân tử của nước (\\(H_2O\\)) là 18 g/mol. Áp suất hơi bão hòa của nước nguyên chất ở \\(25^\\circ C\\) là 23,8 mmHg.",
                subQuestions: [
                    { id: "q103", text: "Câu 103: Nhận xét nào sau đây sai?", options: ["A. Áp suất hơi bão hòa của dung dịch X thấp hơn 23,52 mmHg.", "B. Khi nhiệt độ tăng, áp suất hơi bão hòa của dung dịch X tăng.", "C. Khi tăng nồng độ urea thì áp suất hơi bão hòa của dung dịch tăng.", "D. Áp suất hơi bão hòa của nước luôn lớn hơn áp suất hơi bão hòa của dung dịch X."], correctIndex: 2 },
                    { id: "q104", text: "Câu 104: Có bốn dung dịch \\(X_1, X_2, X_3\\) và \\(X_4\\) được điều chế bằng cách hòa tan cùng một khối lượng lần lượt các chất tan: saccharose (\\(C_{12}H_{22}O_{11}\\)), maltose (\\(C_{12}H_{22}O_{11}\\)), glycerol (\\(C_3H_8O_3\\)) và sorbitol (\\(C_6H_{14}O_6\\)) vào cùng một lượng nước. Gọi \\(P_1, P_2, P_3\\) và \\(P_4\\) lần lượt là áp suất hơi bão hòa của các dung dịch \\(X_1, X_2, X_3\\) và \\(X_4\\). Hãy chọn nhận xét đúng về mối quan hệ giữa \\(P_1, P_2, P_3\\) và \\(P_4\\).", options: ["A. \\(P_1 = P_2 < P_3 < P_4\\).", "B. \\(P_1 > P_2 > P_3 = P_4\\).", "C. \\(P_1 = P_2 = P_3 = P_4\\).", "D. \\(P_1 = P_2 > P_4 > P_3\\)."], correctIndex: 3 },
                    { id: "q105", text: "Câu 105: Cần hòa tan bao nhiêu gam glucose (\\(C_6H_{12}O_6\\)) vào 200 g nước để tạo thành dung dịch có áp suất hơi bão hòa bằng with áp suất hơi bão hòa của dung dịch X? Glucose là chất tan không bay hơi và khối lượng phân tử là 180 g/mol.", options: ["A. 8 gam.", "B. 24 gam.", "C. 36 gam.", "D. 72 gam."], correctIndex: 3 }
                ]
            },
            {
                id: "reading_106_108",
                section: "PHẦN 3. TƯ DUY KHOA HỌC",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 106 đến 108</strong><br><br>Trong thế kỷ XIX, nhiều nhà khoa học cho rằng ánh sáng cần một môi trường đặc biệt để lan truyền, gọi là ê-te (ether). Tuy nhiên, nhiều thí nghiệm, đặc biệt là thí nghiệm Michelson - Morley (1887) không xác nhận sự tồn tại của môi trường này. Theo lý thuyết trường điện từ Maxwell, ánh sáng có bản chất là sóng điện từ with tốc độ lan truyền trong chân không là \\(c = 3.10^8\\) m/s. Ngoài ra, thí nghiệm hiện tượng quang điện cho thấy ánh sáng còn mang tính hạt, with các hạt ánh sáng gọi là photon. Ngày nay, người ta thừa nhận ánh sáng có lưỡng tính sóng - hạt.<br>Mỗi ngày, Mặt Trời gửi đến Trái Đất nhiều loại bức xạ điện từ: ánh sáng khả kiến giúp chúng ta quan sát, tia cực tím có thể gây bỏng da (with bước sóng ngắn hơn 320 nm) nhưng cũng hỗ trợ tổng hợp vitamin D, tia hồng ngoại (bước sóng dài hơn 760 nm) giúp giữ ấm Trái Đất. Việc hiểu bản chất ánh sáng còn giúp khám phá vũ trụ nhờ các kính thiên văn hiện đại. Ví dụ, kính thiên văn James Webb thu nhận bức xạ có bước sóng trong chân không từ 0,60 \\(\\mu m\\) (màu da cam) đến 28,5 \\(\\mu m\\) (hồng ngoại trung), cho phép mở rộng khả năng quan sát vũ trụ.<br>Cho biết năng lượng của một photon ánh sáng \\(\\varepsilon\\) (J) được tính theo công thức:<br>\\(\\varepsilon = hf = \\frac{hc}{\\lambda}\\)<br>with \\(f\\) (Hz) và \\(\\lambda\\) (m) lần lượt là tần số và bước sóng của ánh sáng, \\(h = 6,625.10^{-34}\\) J.s được gọi là hằng số Planck, \\(1 eV = 1,6.10^{-19}\\) J.",
                subQuestions: [
                    { id: "q106", text: "Câu 106: Phát biểu nào sau đây đúng?", options: ["A. Ở thế kỷ XIX, các nhà khoa học cho rằng ánh sáng lan truyền trong môi trường ê-te.", "B. Thí nghiệm Michelson - Morley (1887) giúp khẳng định sự tồn tại của môi trường ê-te.", "C. Thí nghiệm Michelson - Morley (1887) giúp khẳng định ánh sáng có tính chất hạt.", "D. Ngay từ đầu các nhà khoa học đã khẳng định sóng ánh sáng có thể lan truyền trong môi trường chân không."], correctIndex: 0 },
                    { id: "q107", text: "Câu 107: Tần số ánh sáng nhỏ nhất mà kính thiên văn James Webb có thể thu được gần đúng là:", options: ["A. \\(1,1.10^{13}\\) Hz.", "B. \\(5,0.10^{14}\\) Hz.", "C. \\(9,4.10^{14}\\) Hz.", "D. \\(3,9.10^{14}\\) Hz."], correctIndex: 0 },
                    { id: "q108", text: "Câu 108: Cho các phát biểu sau:<br>(1) Năng lượng của mỗi photon tia cực tím có thể gây bỏng da chủ yếu lớn hơn 3,88 eV.<br>(2) Tia cực tím luôn có hại.<br>(3) Kính thiên văn James Webb chỉ quan sát ánh sáng trong vùng hồng ngoại.<br>(4) Ánh sáng là một dạng của sóng điện từ.<br>Các phát biểu đúng là:", options: ["A. (1), (4).", "B. (1), (3).", "C. (4).", "D. (2), (3), (4).."], correctIndex: 0 }
                ]
            },
            {
                id: "reading_109_111",
                section: "PHẦN 3. TƯ DUY KHOA HỌC",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 109 đến 111</strong><br><br>Để đánh giá ảnh hưởng của nước thải sinh hoạt đến tính thấm của màng tế bào sinh vật, sinh viên sử dụng 5 mẫu mô rễ củ cải đường giống nhau (có chứa sắc tố tím betacyanin) làm vật liệu thí nghiệm. Mỗi mẫu mô được rửa sạch và ngâm vào một ống nghiệm chứa 5 mL dung dịch tương ứng with một nghiệm thức. Nước thải sinh hoạt được pha loãng bằng nước máy sinh hoạt theo các tỷ lệ quy định trong bảng. Sau khi ủ trong 15 phút ở \\(25^\\circ C\\), độ hấp thụ của dung dịch được đo tại bước sóng 460 nm (A460). Giá trị độ hấp thụ ánh sáng phản ánh mức độ khuếch tán betacyanin qua màng tế bào, từ đó xác định sự thay đổi tính thấm của màng tế bào. Thí nghiệm được lặp lại 5 lần, số liệu thu được là giá trị trung bình của 5 lần đo.<br><table class=\"table table-bordered text-center\" style=\"width:auto; margin:10px auto\"><tr><th>Nghiệm thức (NT)</th><th>Dung dịch xử lý</th><th>Độ hấp thụ ánh sáng</th></tr><tr><td>NT 1</td><td>Nước máy sinh hoạt</td><td>0,090 \\(\\pm\\) 0,006</td></tr><tr><td>NT 2</td><td>Nước thải pha loãng 25%</td><td>0,150 \\(\\pm\\) 0,020</td></tr><tr><td>NT 3</td><td>Nước thải không pha loãng</td><td>0,400 \\(\\pm\\) 0,105</td></tr><tr><td>NT 4</td><td>Nước thải pha loãng 50% + than hoạt tính</td><td>0,130 \\(\\pm\\) 0,012</td></tr><tr><td>NT 5</td><td>Chất tẩy rửa 0,1%</td><td>0,520 \\(\\pm\\) 0,040</td></tr></table>",
                subQuestions: [
                    { id: "q109", text: "Câu 109: Dung dịch trong ống nghiệm có nồng độ betacyanin cao nhất ở nghiệm thức nào?", options: ["A. NT 1.", "B. NT 2.", "C. NT 3.", "D. NT 5."], correctIndex: 3 },
                    { id: "q110", text: "Câu 110: Từ kết quả thí nghiệm, giải pháp nào sau đây nên được ưu tiên sử dụng để xử lý nước thải sinh hoạt, đồng thời giảm thiểu tổn thương màng tế bào sinh vật?", options: ["A. Nước thải sinh hoạt có thể được xả trực tiếp mà không ảnh hưởng đến sinh vật.", "B. Pha loãng 25% thể tích nước thải with 75% thể tích nước máy sinh hoạt.", "C. Pha loãng 50% nước thải sinh hoạt with 50% nước máy và lọc qua than hoạt tính.", "D. Thêm dung dịch tẩy rửa 0,1% vào nước thải sinh hoạt theo tỷ lệ thể tích 1:1."], correctIndex: 2 },
                    { id: "q111", text: "Câu 111: Cho những nhận định sau:<br>I. Nước thải sinh hoạt không pha loãng làm giảm tính thấm màng tế bào.<br>II. Than hoạt tính làm tăng tính thấm của màng tế bào, đồng thời làm giảm mức độ khuếch tán sắc tố.<br>III. Kết quả ở nghiệm thức NT3 đáng tin cậy hơn nghiệm thức NT2 vì giá trị trung bình cao hơn.<br>IV. Khi tiến hành thí nghiệm ở \\(4^\\circ C\\), giá trị hấp thụ A460 của tất cả các nghiệm thức có thể thay đổi.<br>Những nhận định đúng là:", options: ["A. IV.", "B. I, II, IV.", "C. I, II, III, IV.", "D. III, IV."], correctIndex: 0 }
                ]
            },
            {
                id: "reading_112_114",
                section: "PHẦN 3. TƯ DUY KHOA HỌC",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 112 đến 114</strong><br><br>Báo The New York Times dẫn số liệu được Cục Thống kê dân số Hoa Kỳ công bố ngày 22/6/2023 cho thấy, độ tuổi trung vị (median age) của Hoa Kỳ trong năm 2022 đạt con số kỷ lục 38,9 tuổi. Tuổi trung vị là chỉ số quan trọng trong việc biểu thị sự phân bổ dân số theo độ tuổi (trên một đơn vị lãnh thổ), chia dân số thành hai nhóm with số lượng bằng nhau. Nói cách khác, with tuổi trung vị 38,9 thì Hoa Kỳ đang có số người dân trên 38,9 tuổi đúng bằng số người trẻ hơn mốc này.<br>Trong những năm qua, tuổi trung vị của Hoa Kỳ liên tục tăng. Năm 1980, chỉ số này chỉ dừng ở mức 30 tuổi. Đến năm 2000, tuổi trung vị của Hoa Kỳ đã tăng vọt lên 35. Tuổi trung vị gần 39 cho thấy, Hoa Kỳ đang có dân số già quá nhanh. Trong tương lai, điều này sẽ dẫn đến những thách thức to lớn with lực lượng lao động, nền kinh tế cũng như các chương trình xã hội.<br>Báo The New York Times dẫn nguồn nhiều chuyên gia khẳng định nguyên nhân chính dẫn đến sự gia tăng tuổi trung vị là tỷ lệ sinh thấp. Tại Hoa Kỳ, phụ nữ thuộc thế hệ Gen Y (sinh trong khoảng năm 1981-1996, phần lớn hiện nay trong độ tuổi sinh đẻ) có xu hướng ưu tiên học tập và làm việc khi còn trẻ. Điều này dẫn đến việc họ kết hôn muộn hơn và có ít con hơn. Yếu tố người nhập cư cũng góp phần làm tăng tuổi trung vị. Trước đây, hầu hết người nhập cư đến Hoa Kỳ là người trong độ tuổi lao động, thường có nhiều con hơn người đã ở Hoa Kỳ từ nhiều thế hệ. Tuy nhiên, từ năm 2016, số người nhập cư vào Hoa Kỳ đã giảm, thậm chí chạm đáy trong giai đoạn đại dịch COVID-19.<br><i>(Ngọc Đức, Vì sao dân số Mỹ già quá nhanh?)</i>",
                subQuestions: [
                    { id: "q112", text: "Câu 112: Nhận định nào sau đây phản ánh đúng về tuổi trung vị của dân số Hoa Kỳ?", options: ["A. Tuổi trung vị đạt mức kỷ lục tính đến năm 2022 phản ánh Hoa Kỳ có cơ cấu dân số già.", "B. Tuổi trung vị năm 2022 cho thấy số dân dưới 38,9 tuổi nhiều hơn số dân trên tuổi này.", "C. Tuổi trung vị năm 2000 có xu hướng giảm so with năm 1980.", "D. Tuổi trung vị chia dân số Hoa Kỳ thành hai nhóm with số lượng bằng nhau."], correctIndex: 0 },
                    { id: "q113", text: "Câu 113: Nhận định nào sau đây không phải là thách thức đối with Hoa Kỳ khi tuổi trung vị ngày càng gia tăng?", options: ["A. Sự suy giảm số người trong độ tuổi lao động.", "B. Sự già hóa dân số đang diễn ra.", "C. Sự gia tăng chi phí an sinh xã hội.", "D. Sự mất cân bằng về giới tính khi sinh."], correctIndex: 3 },
                    { id: "q114", text: "Câu 114: Yếu tố nào sau đây có ảnh hưởng sâu sắc đến sự gia tăng tuổi trung vị ở Hoa Kỳ?", options: ["A. Sự ưu tiên học tập và làm việc của phụ nữ thế hệ Gen Y dẫn đến kết hôn muộn và có ít con hơn.", "B. Tỷ lệ sinh giảm ở phụ nữ trước thế hệ Gen Y khiến cho dân số trẻ giảm dần.", "C. Sự gia tăng của các dịch vụ y tế giúp kéo dài tuổi thọ của người dân.", "D. Mức độ di cư từ các quốc gia phát triển vào Hoa Kỳ ngày càng tăng."], correctIndex: 0 }
                ]
            },
            {
                id: "reading_115_117",
                section: "PHẦN 3. TƯ DUY KHOA HỌC",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 115 đến 117</strong><br><br>Văn hóa Tây Âu thế kỷ V-X dựa trên nền tảng nền kinh tế tự cung tự cấp, sự giao lưu trao đổi rất hạn chế, văn hóa vì vậy cũng phát triển không đáng kể. Tới thế kỷ XIV, with sự phát triển kinh tế công thương ở các thành thị, quan hệ sản xuất tư bản chủ nghĩa dần dần hình thành và ngày càng lớn mạnh. Các nhà tư tưởng của giai cấp tư sản không còn chịu chấp nhận những giáo lí phong kiến lỗi thời, họ vận động khôi phục lại sự huy hoàng của văn hóa Tây Âu thời cổ đại. Họ tìm thấy trong nền văn hóa cổ đại những yếu tố phù hợp with mình, có lợi cho mình để đấu tranh chống lại những trói buộc của nền văn hóa trung cổ. Phong trào Văn hóa Phục hưng xuất hiện đầu tiên ở Ý, vì ở đây đã xuất hiện các thành thị tự do như những quốc gia nhỏ. Quan hệ sản xuất tư bản đã chiếm địa vị chi phối đời sống văn hóa. Ý lại là trung tâm của đế quốc Rôma cổ đại, vì vậy ở đây còn giữ lại nhiều di sản văn hóa cổ đại của Hy Lạp - Rôma. Hơn ai hết, các nhà văn hóa Ý có điều kiện khôi phục lại nền văn hóa trước tiên khi có điều kiện. Từ Ý, phong trào lan sang Anh, Pháp, Tây Ban Nha, Đức...<br><i>(Vũ Dương Ninh, Lịch sử văn minh thế giới)</i>",
                subQuestions: [
                    { id: "q115", text: "Câu 115: Phong trào Văn hóa Phục hưng ở Tây Âu thời trung đại ra đời trong bối cảnh nào?", options: ["A. Quan hệ sản xuất tư bản chủ nghĩa hình thành ở các nước Tây Âu.", "B. Các chính quyền phong kiến tìm cách đổi mới về văn hóa, tư tưởng.", "C. Những thành tựu văn hóa Hy Lạp - Rôma cổ đại được đề cao.", "D. Giai cấp tư sản đã nắm chính quyền ở hầu hết các nước châu Âu."], correctIndex: 0 },
                    { id: "q116", text: "Câu 116: Phong trào Văn hóa Phục hưng do giai cấp nào lãnh đạo?", options: ["A. Tư sản.", "B. Vô sản.", "C. Quý tộc.", "D. Tăng lữ."], correctIndex: 0 },
                    { id: "q117", text: "Câu 117: Vì sao phong trào Văn hóa Phục hưng ở châu Âu vừa mang tính “kế thừa” vừa mang tính “cách mạng”?", options: ["A. Vì nó khôi phục toàn bộ văn hóa Hy Lạp - Rôma cổ đại, phát triển lên một tầm cao mới.", "B. Vì nó kế thừa tinh hoa văn hóa Hy Lạp - Rôma cổ đại, phát triển lên một tầm cao mới.", "C. Vì nó khôi phục toàn bộ văn hóa thế giới cổ đại, phát triển lên một tầm cao mới.", "D. Vì nó kế thừa tinh hoa văn hóa thế giới cổ đại, phát triển lên một tầm cao mới."], correctIndex: 1 }
                ]
            },
            {
                id: "reading_118_120",
                section: "PHẦN 3. TƯ DUY KHOA HỌC",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 118 đến 120</strong><br><br>An và Khang quyết định khởi nghiệp with ý tưởng mở một cửa hàng bánh ngọt kết hợp quán cà phê. Sau khi lên ý tưởng, họ đã thiết kế thực đơn bao gồm nhiều loại bánh ngọt và đồ uống đa dạng, with giá cả phù hợp cho nhóm khách hàng mục tiêu là giới trẻ. Trong quá trình chuẩn bị, An đảm nhận việc quảng bá và tuyển dụng nhân sự, trong khi Khang lo phần tài chính và quản lý nguồn nguyên liệu. Họ dự định sử dụng bao bì và vật dụng thân thiện with môi trường như túi giấy và ống hút tre như là một hành động bảo vệ môi trường. With niềm tin vào ý tưởng độc đáo và lượng khách hàng tiềm năng, An và Khang tin rằng họ sẽ dễ dàng nhận được nguồn vốn vay từ ngân hàng để thực hiện hoạt động kinh doanh.",
                subQuestions: [
                    { id: "q118", text: "Câu 118: Việc sử dụng túi giấy và ống hút tre là biểu hiện của trách nhiệm xã hội nào?", options: ["A. Trách nhiệm pháp lý.", "B. Trách nhiệm đạo đức.", "C. Trách nhiệm kinh tế.", "D. Trách nhiệm nhân văn."], correctIndex: 1 },
                    { id: "q119", text: "Câu 119: Yếu tố nào quan trọng nhất để ngân hàng đồng ý cấp tín dụng cho dự án khởi nghiệp của An và Khang?", options: ["A. Ý tưởng kinh doanh độc đáo sẽ thu hút sự quan tâm của ngân hàng.", "B. Quy mô cửa hàng và số lượng khách tiềm năng.", "C. Kế hoạch kinh doanh chi tiết khả thi, đáp ứng các yêu cầu của ngân hàng.", "D. Quan hệ đối tác uy tín giúp tăng độ tin cậy của dự án."], correctIndex: 2 },
                    { id: "q120", text: "Câu 120: Theo tình huống trên, bước nào trong quá trình lập kế hoạch kinh doanh đã được An và Khang thực hiện?", options: ["A. Xác định mục tiêu và chiến lược kinh doanh.", "B. Đánh giá cơ hội, rủi ro và biện pháp xử lý kinh doanh.", "C. Phân tích điều kiện thực hiện ý tưởng kinh doanh.", "D. Tóm tắt tổng kết kế hoạch kinh doanh."], correctIndex: 0 }
                ]
            }
        ]
    }
];
