const fs = require('fs');
const path = require('path');

const dataJsPath = path.join(__dirname, '../js/data.js');
let data = fs.readFileSync(dataJsPath, 'utf8');

const newQuiz = `    ,
    {
        id: "de_1_dgnl",
        title: "Đề 1 (Phần 1: 30/120 câu)",
        description: "Phần 1: Sử dụng ngôn ngữ (Tiếng Việt) - Sẽ cập nhật thêm",
        questions: [
            // Questions 1-20
            { id: "q1", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 1: Thị Phương là nhân vật trong vở chèo Trương Viên. Thời bình, nàng động viên chồng học hành thi cử. Thời chiến, nàng chăm sóc, bảo vệ mẹ chồng và lặn lội tìm chồng.\\n“Thị Phương:\\nMẹ ơi, giặc đã kéo đến đây\\nCon xin dắt mẹ vào ngay trong rừng\\nKẻo con chút phận má hồng\\nNữa gặp gian hùng, lỗi đạo tào khang.\\nTrước là thất tiết cùng chàng\\nSau con bỏ mẹ giữa đàng ai nuôi”.\\n(Trần Việt Ngữ sưu tầm, Trương Viên chèo cổ)\\nNhân vật Thị Phương là loại nhân vật gì?", options: ["A. Kép.", "B. Lão.", "C. Đào lẳng.", "D. Đào thương."], correctIndex: 3 },
            { id: "q2", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 2: “Bị cướp vợ và chiến đấu giành lại vợ” là mô típ (motif) phổ biến trong thể loại nào của văn học dân gian Việt Nam?", options: ["A. Thần thoại.", "B. Sử thi.", "C. Tuồng, chèo.", "D. Truyện thơ."], correctIndex: 1 },
            { id: "q3", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 3: “Sau đó vài tháng, Hà Nhân tiếp được tin nhà gửi đến kinh đô, nói cha mẹ ở nhà đã hỏi vợ cho, giục Sinh nên về mau để làm lễ cưới. Sinh bối rối quanh co, lòng rất không nỡ, hai nàng đoán biết được tình ý, bảo Sinh rằng:\\n- Bọn chúng em thân bồ vóc liễu, không thể cáng đáng được việc tần tảo ở gia đình. Vả ngôi chủ phụ trong nhà, tất phải là người trong nền nếp trâm anh như Tống Tử, Tề Khương, chúng em đâu dám chòi mòi đến. Chỉ mong chàng sau buổi về quê, tình cũ sẽ vấn vương không dứt, sớm dẹp lòng quyến luyến hương thổ để lại tính kế tìm hoa.”\\n(Nguyễn Dữ, Chuyện kỳ ngộ ở Trại Tây)\\nDòng nào sau đây nêu không đúng đặc điểm của lời nhân vật trong đoạn trích trên?", options: ["A. Sử dụng lối nói chuộng ngôn từ hoa mỹ.", "B. Sử dụng lối nói dùng nhiều điển tích, điển cố.", "C. Sử dụng lối nói dùng hình ảnh so sánh, ẩn dụ.", "D. Sử dụng lối nói gần với lời ăn tiếng nói hằng ngày."], correctIndex: 3 },
            { id: "q4", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 4:\\n“Khắc khoải sầu đưa giọng lửng lơ,\\nẤy hồn Thục đế thác bao giờ?\\nNăm canh máu chảy đêm hè vắng,\\nSáu khắc hồn tan bóng nguyệt mờ.\\nCó phải tiếc xuân mà đứng gọi,\\nHay là nhớ nước vẫn nằm mơ?\\nThâu đêm ròng rã kêu ai đó,\\nGiục khách giang hồ dạ ngẩn ngơ”.\\n(Nguyễn Khuyến, Cuốc kêu cảm hứng)\\nBài thơ thể hiện nỗi niềm gì của chủ thể trữ tình?", options: ["A. Thương tiếc mùa xuân trôi qua mất.", "B. Thương tiếc nước mất vào tay giặc.", "C. Thương tiếc máu xương của người yêu nước.", "D. Thương tiếc nước bị chia cắt."], correctIndex: 1 },
            { id: "q5", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 5: Khi Thúy Kiều lại một lần nữa bị lừa bán vào lầu xanh, Nguyễn Du đã viết:\\n“Nghĩ đời mà ngán cho đời\\nTài tình chi lắm, cho trời đất ghen.\\nTiếc thay nước đã đánh phèn\\nMà cho bùn lại vẩn lên mấy lần!\\nHồng quân với khách hồng quần\\nĐã xoay đến thế, còn vần chưa tha”.\\n(Nguyễn Du, Truyện Kiều)\\nHai từ “hồng quân” và “hồng quần” có ý nghĩa:", options: ["A. Người lính trong quân đội và người con gái đẹp.", "B. Vị vua anh minh với người tì thiếp đẹp.", "C. Đấng tạo hóa với người ca kỹ đẹp.", "D. Đấng tạo hóa và người con gái đẹp."], correctIndex: 3 },
            { id: "q6", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 6: “Cuộc xua đuổi đã kéo dài hàng tiếng đồng hồ. Lão Khúng đã mệt nhoài nhưng vẫn chưa chịu cho vật dừng lại. Nó phải đi thật xa, phải bắt nó vào thật sâu giữa rừng thẳm, để không còn lối nào trở lại với lão. Rồi thì mai đây khi trở về nhà, lão nghĩ, lão sẽ nói thật với mụ Huệ, lão đã không đem xuống chợ Giát để bán mà trên dọc đường đã giải thoát cho nó, trả lại cho nó cuộc đời tự do, lão đã xua nó vào rừng, vào giữa giang sơn của một bầy bò hoang... Chắc hẳn mụ Huệ cũng không mè nheo lão. Mụ sẽ thông cảm với lão, với việc làm của lão”.\\n(Nguyễn Minh Châu, Phiên chợ Giát)\\nHành động xua con vật đi thật xa vào rừng thẳm thể hiện điều gì?", options: ["A. Sự mệt nhoài của lão khi đem con vật xuống chợ Giát để bán.", "B. Sự quyết tâm giải thoát con vật, trả lại cho nó cuộc đời tự do.", "C. Sự mong mỏi được trở về nhà và được vợ của lão cảm thông.", "D. Sự cảm thông với con vật và sự tự dằn vặt bản thân ở lão."], correctIndex: 1 },
            { id: "q7", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 7: “Tôi hát bài hát về cố hương tôi\\nTrong ánh sáng đèn dầu\\nNgọn đèn đó ông bà tôi để lại\\nĐẹp và buồn hơn tất cả những ngọn đèn\\nThuở tôi vừa sinh ra\\nMẹ đã đặt ngọn đèn trước mặt tôi\\nĐể tôi nhìn mặt đèn mà biết buồn, biết yêu và biết khóc”.\\n(Nguyễn Quang Thiều, Bài hát về cố hương)\\nDòng nào dưới đây không thể hiện ý nghĩa biểu đạt của hình ảnh “ánh sáng đèn dầu” trong đoạn thơ trên?", options: ["A. Ánh sáng của không gian ấu thơ.", "B. Ánh sáng của không gian gia đình.", "C. Ánh sáng của thời gian ký ức.", "D. Ánh sáng của quá khứ đau thương, mất mát."], correctIndex: 3 },
            { id: "q8", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 8:\\nTrung tá Nam hồi tưởng về cuộc trò chuyện với hạ sĩ Lãm:\\n“Trong đầu anh bỗng hiện lên hình ảnh người hạ sĩ quê ở Hà Nội có cái nhìn lì lợm ngày nào…\\nLãm! - Này, bây giờ ta nói chuyện tình anh em, đừng trên dưới gì hết - Vâng, tôi cũng nghĩ như thế -\\nNghe nói thời kỳ chốt chặn ở biên giới, cậu là một tay súng tốt? - Vâng, thưa thủ trưởng, cũng có lẽ như thế - Nhưng chỉ im tiếng súng có mấy tháng thôi, người ta phản ảnh với tôi cậu đã không còn giữ được phẩm chất ấy nữa? - Vâng, nếu gọi như thế là phẩm chất - Tôi yêu cầu cậu chuyện trò với tôi chân thành và dễ hiểu hơn một chút, và trước hết là xin cậu hãy bỏ giúp đẫn mía trên tay kia đi cho tôi nhờ - Dạ… Thưa, tôi vẫn luôn luôn chân thành và dễ hiểu đấy chứ ạ!”\\n(Chu Lai, Phố)\\nĐoạn hội thoại trên cho thấy điều gì về hạ sĩ Lãm?", options: ["A. Có tài và ngang tàng.", "B. Bất tài và ngang ngược.", "C. Có tài và khiêm cung.", "D. Bất tài và chân thành."], correctIndex: 0 },
            { id: "q9", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 9: LÊ TƯƠNG DỰC - Vua cần đến thì thần nhân phải xả thân làm việc kỳ đến chết thì thôi.\\nVŨ NHƯ TÔ - Nhưng xử đãi thế thì ai muốn trau dồi nghề nghiệp? Kính sĩ mới đắc sĩ...\\nLÊ TƯƠNG DỰC - Kính sĩ đắc sĩ, mi là sĩ đấy ư: Mi dám tự phụ là sĩ thảo nào mi không sợ chết.\\nVŨ NHƯ TÔ - Sĩ mà không có chân tài thì tiện nhân không bàn. Anh em tiện nhân còn có những nguyện vọng sâu xa hơn đối với nước. Hoàng thượng quá nhầm về chữ sĩ. Một ông quan trị dân, với một người thợ giỏi, xây những lâu đài tráng quan, điểm xuyết cho đất nước, tiện nhân chưa biết người nào mới đáng gọi là sĩ.\\n(Nguyễn Huy Tưởng, Vũ Như Tô)\\nÝ nào phù hợp với tính cách Vũ Như Tô được thể hiện trong đoạn trích?", options: ["A. Không bao giờ bằng lòng với thực tại, khát khó sự sáng tạo.", "B. Trọng danh dự, muốn đem tài năng phụng sự đất nước.", "C. Coi thường vương quyền, muốn có những kẻ sĩ chân tài.", "D. Trọng danh dự, muốn có những kẻ sĩ chân tài."], correctIndex: 3 },
            { id: "q10", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 10: “Năm 1975, khi tấm lưng của bà Chắt Chu đã bắt đầu còng xuống thì o Nhị - Lê Thị Nhị - con gái bà mới trở về. Lúc đó, o đã 29 tuổi. Phụ nữ làng chài thường lấy chồng rất sớm. Cái tuổi của o khi đó, làng đã toan gọi… gái già. O cứ ở vậy, gánh cá, gánh tấp đốt thuyền thuê, rồi làm nghề dệt thảm len ngoài Hợp tác xã Hải Đằng nuôi mẹ mà không chịu lấy chồng. Ai hỏi thì o cười, nửa thật nửa đùa, rằng “nỏ có ai chịu lấy”.\\nNăm 1967, đang là một vận động viên bóng chuyền, o Nhị xung phong nhập ngũ, vào Thanh niên xung phong lấp hố bom, bạt núi mở đường, làm cọc tiêu dẫn xe, qua ngầm, vượt hố trong những đêm trời tối không đèn. Đi qua chiến tranh, sức khỏe và nhan sắc của o gửi hết ở chiến trường. Dệt thảm khá nhanh tay, lành nghề, nhưng tấm thảm đời o thì cứ rối nùi, chẳng biết đâu mà gỡ.[…]\\nĐùng một cái, cả xã Thạch Kim sôi sục. Chẳng hiểu từ đâu báo chí bỗng phát hiện ra, o Lê Thị Nhị chính là nguyên mẫu của cô thanh niên xung phong trong bài thơ “Gửi em, cô Thanh niên xung phong” của nhà thơ Phạm Tiến Duật”.\\n(Nguyễn Hồng Lam, Vu vơ sợi khói đốt thuyền)\\nĐoạn trích có chứa đựng yếu tố:", options: ["A. Hư cấu.", "B. Phi hư cấu.", "C. Tự truyện.", "D. Tự thuật."], correctIndex: 1 },
            { id: "q11", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 11:\\nTình thiên\\n“Sự vật tuần hoàn nguyên hữu định,\\nVũ thiên chi hậu tất tình thiên;\\nPhiến thì vũ trụ giải lâm phục,\\nVạn lý sơn hà sái cẩm chiên;\\nNhật noãn phong thanh hoa đới tiếu,\\nThụ cao chi nhuận điểu tranh ngôn;\\nNhân hòa vạn vật đô hưng phấn,\\nKhổ tận cam lai, lý tự nhiên”.\\n(Hồ Chí Minh, Nhật ký trong tù)\\nTrời hửng\\n“Sự vật vần xoay đà định sẵn,\\nHết mưa là nắng hửng lên thôi;\\nĐất trời một thoáng thu màn ướt,\\nSông núi muôn trùng trải gấm phơi;\\nTrời ấm, hoa cười chào gió nhẹ,\\nCây cao, chim hót rộn cành tươi;\\nNgười cùng vạn vật đều phơi phới,\\nHết khổ là vui vốn lẽ đời”.\\n(Nam Trân dịch)\\nBài thơ “Tình thiên” thể hiện đặc điểm nổi bật nào trong phong cách sáng tác của Hồ Chí Minh?", options: ["A. Sử dụng hình ảnh thiên nhiên để ẩn dụ cho tình cảm và tâm tư của con người.", "B. Thể hiện sâu sắc tư tưởng phương Tây bằng lối diễn đạt gần gũi, giản dị.", "C. Miêu tả cảnh vật thiên nhiên thuần túy, không mang thông điệp triết lý.", "D. Đề cao hình mẫu cá nhân, khẳng định cá tính độc đáo của nhân vật trữ tình."], correctIndex: 0 },
            { id: "q12", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 12: “Thi pháp _____ đề cao sự đổi mới, sáng tạo của cá tính nghệ sĩ, tôn vinh “cái riêng biệt”, “cái mới lạ”, theo xu hướng vượt ra khỏi mô hình chung, ký ức thể loại. Trong khi đó, thi pháp _____ chấp nhận “cái quen thuộc”, “cái lặp lại” đã trở thành sở hữu chung của mỗi thành viên trong cộng đồng, và hơn thế nó đã trở thành kỷ niệm riêng của cả một dân tộc”.\\n(Vũ Anh Tuấn, Vai trò thể loại trong khoa học văn học dân gian và vấn đề phân tích tác phẩm văn học dân gian từ góc nhìn thể loại)\\nChọn cụm từ phù hợp để điền vào các chỗ trống:", options: ["A. văn học trung đại - văn học hiện đại.", "B. văn học dân gian - văn học viết.", "C. văn học viết - văn học dân gian.", "D. văn học hiện đại - văn học viết."], correctIndex: 2 },
            { id: "q13", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 13: Trường hợp nào sau đây viết đúng chính tả?", options: ["A. Sỗ sàng, súc tích, trau chuốt.", "B. Sỗ sàng, xúc tích, trau chuốt.", "C. Sỗ sàng, súc tích, trao chuốt.", "D. Sổ sàng, súc tích, trau chuốt."], correctIndex: 0 },
            { id: "q14", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 14: Câu nào sau đây viết đúng?", options: ["A. Trong gia đình, nó là đứa bị đối xử khắc khe nhất.", "B. Gió làm cây cối trong vườn xào xạc suốt đêm.", "C. Có gì đâu mà suốt ngày cứ dành giật với nhau.", "D. Kết quả chuẩn đoán của tôi không đáng lo."], correctIndex: 1 },
            { id: "q15", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 15: “Anh ấy không nói gì, vô hình trung, tôi bị những người đứng quanh đó hiểu lầm”.\\n“Vô hình trung” trong câu trên có nghĩa gì?", options: ["A. Vô tình, không ý thức được cảm xúc của người khác.", "B. Có chủ ý mang đến kết quả từ hành động của chủ thể.", "C. Tuy không có chủ định, không cố tình nhưng lại thành ra như vậy.", "D. Vì thiếu suy nghĩ nên đôi khi tạo ra ảnh hưởng tiêu cực."], correctIndex: 2 },
            { id: "q16", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 16: Từ “mỗi” trong câu nào được dùng với nghĩa nhấn mạnh số lượng ít của sự vật?", options: ["A. Ngày xưa, thường cũng chỉ học một thầy, cùng lắm là vài ba thầy, chứ không như ngày nay, mỗi năm một lớp rồi mỗi môn một thầy.", "B. Mỗi người nghĩ một phách, mỗi người làm một nẻo, mạnh ai người nấy lo, còn thì “sống chết mặc bay”.", "C. Các cuộc thi bơi được tiến hành trong bể bơi có 6-10 đường bơi, mỗi một đường bơi rộng 2-2.5 m, được ngăn cách bằng dây phao.", "D. Thiết kế đặc biệt ở đây khiến ta dù nhắm tịt mắt hay giương to mắt thì cũng như nhau, bởi chỉ nhìn thấy có mỗi một màu đen."], correctIndex: 3 },
            { id: "q17", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 17: “Sống có nghị lực mạnh mẽ sẽ giúp chúng ta vượt qua mọi thử thách, mọi trở ngại của hoàn cảnh và đạt được điều chúng ta mong ước; bởi vậy do đó, mỗi người cần giữ vững tinh thần, luôn hướng đến mục tiêu và nỗ lực hoàn thành mục tiêu”.\\nCâu trên mắc lỗi gì?", options: ["A. Thiếu thành phần vị ngữ.", "B. Dùng sai từ ngữ liên kết.", "C. Thiếu thành phần chủ ngữ.", "D. Dùng từ sai về từ loại."], correctIndex: 1 },
            { id: "q18", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 18:\\nCâu “Nhờ kinh nghiệm nghiên cứu khoa học từ thời còn là sinh viên của Minh đã gây ấn tượng tốt với hội đồng đánh giá.” là câu sai, nên được sửa thành câu nào sau đây?", options: ["A. Nhờ kinh nghiệm nghiên cứu khoa học từ thời còn là sinh viên, Minh đã gây ấn tượng tốt với hội đồng đánh giá.", "B. Từ thời còn là sinh viên, nhờ kinh nghiệm nghiên cứu khoa học của Minh đã gây ấn tượng tốt với hội đồng đánh giá.", "C. Nhờ kinh nghiệm nghiên cứu khoa học từ thời còn là sinh viên, hội đồng đánh giá đã có ấn tượng tốt với Minh.", "D. Từ lúc còn là sinh viên, hội đồng đánh giá đã có ấn tượng tốt về kinh nghiệm nghiên cứu khoa học của Minh."], correctIndex: 0 },
            { id: "q19", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 19: Câu nào sau đây thể hiện phong cách ngôn ngữ sinh hoạt?", options: ["A. Về công tác đào tạo đội ngũ làm báo, Chủ tịch Hồ Chí Minh luôn nhấn mạnh đến tầm quan trọng của việc giáo dục đạo đức, bồi dưỡng tài năng.", "B. Từ điển tiếng Việt giải nghĩa “diễn đàn là nơi để nhiều người có thể phát biểu ý kiến một cách công khai và rộng rãi”.", "C. Xem lại những quan điểm mà tôi đã trình bày trong báo cáo hơn 20 trang in đó, thì thấy cơ bản đến nay vẫn đúng.", "D. Trong xã hội hiện đại, báo chí là kênh truyền thông hữu hiệu, kết nối mọi thành viên trong cộng đồng."], correctIndex: 2 },
            { id: "q20", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 20: “Thằng em thì hay hỏi\\nKhông kể chuyện như anh\\n(Tuy con, má chẳng sinh\\nCon vẫn quen gọi má)\\n- Má ơi ai sinh cá\\nAi làm ra cái kem\\nĐêm sao lại màu đen\\nBan ngày sao màu trắng?…”.\\n(Xuân Quỳnh, Cắt nghĩa)\\nTại sao nhà thơ lại lựa chọn sử dụng cụm từ chêm xen thay vì viết dưới dạng một câu riêng biệt?", options: ["A. Để làm gián đoạn mạch kể chuyện chính.", "B. Để làm nổi bật tầm quan trọng của mối quan hệ giữa má và con.", "C. Để thể hiện triết lý sống đề cao tính nhân văn.", "D. Để bổ sung thông tin và tạo cảm giác tự nhiên, gần gũi."], correctIndex: 3 },

            // Reading Group 1
            {
                id: "reading_21_25",
                section: "SỬ DỤNG NGÔN NGỮ",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời câu từ 21 đến 25</strong><br><br>(1) Chạy dọc theo kênh Tàu Hủ, bến Bình Đông xưa, nhờ giao thông thủy lộ thuận tiện, cộng với cư dân bản địa và làng Minh Hương phát triển sầm uất, đã thành nơi tụ hội ghe thuyền từ khắp các tỉnh miền Tây và cả Nam Bộ, khiến khu vực này dần cực thịnh trong buôn bán và xuất khẩu lúa gạo.<br><br>(2) Dựa theo những ghi chép thì tên gọi kênh Tàu Hủ có khá nhiều lý giải. “Ký ức lịch sử về Sài Gòn và vùng phụ cận” của Trương Vĩnh Ký (Nguyễn Đình Đầu dịch, NXB Trẻ) có đoạn: “Hai bên bờ rạch Chợ Lớn là hai dãy phố lớn bằng gạch gọi là Tàu khậu, để cho người Hoa từ Trung Quốc hằng năm đi ghe biển tới thuê. Họ đem hàng hóa chứa trong các phố đó, hoặc để bán sỉ, bán lẻ khi lưu trú tại Sài Gòn”. “Tàu khậu” ở đây là ngữ âm của người Triều Châu, nghĩa là “nhà gạch” (thổ khố), phương ngữ “tàu khậu” bị biến âm dần trở thành “tàu hủ”. Một lý giải khác bắt nguồn từ hình dáng của dòng kênh, do có những đoạn thắt như cổ hũ, đọc lâu dần trại ra thành âm “tàu hũ, tàu hủ” như ngày nay.<br><br>(3) Nhắc đến bến Bình Đông, không thể không đề cập đến các kho, vựa - chành (phương ngữ của người Triều Châu, nghĩa là bến, bãi), nhà máy tên tuổi như kho Hữu Thành với sáu cửa, nhà máy xay lúa Phong Thạnh với công suất lên đến 500 tấn/ngày.<br><br>(4) Còn về diện mạo phố xá, kiến trúc nhà ở đặc trưng ở bến Bình Đông mang hình thái thuộc địa với các chi tiết trang trí chạy chỉ nổi thạch cao, lan can sắt mỹ nghệ, ngói tây, cửa lá sách… có công năng dùng để buôn bán (tầng trệt) và cư ngụ (tầng trên). Với sự phát triển của nhịp sống đô thị, cả bến Bình Đông hiện chỉ còn sót lại lác đác dãy nhà cổ liên kế gồm từng cụm ba gian, năm gian, bảy gian… nằm cách nhau một khoảng trống bằng với bề ngang của từng gian nhà gần chân cầu Máy Rượu.<br><br>(5) Qua thời gian, những cư dân gốc của dãy phố này cũng lần lượt ra đi. Những khoảng trống giữa các dãy nhà được người đến sau tận dụng, xây nối thành những căn nhà phố mới với kiến trúc “phá bĩnh” - giữa các dãy nhà ngói đỏ điểm xuyết một “gạch nối” là căn nhà hiện đại, mái đúc - chẳng ăn nhập gì với những căn nhà vốn mang nét cổ kính từ hàng trăm năm nay.<br><i>(Nguyễn Đình, Chuyện nhỏ ở Chợ Lớn)</i>",
                subQuestions: [
                    { id: "q21", text: "Câu 21: Thông tin của đoạn (2) được tổ chức theo kiểu gì?", options: ["A. Theo trật tự thời gian.", "B. Theo trật tự không gian.", "C. Theo kiểu quan hệ nhân quả.", "D. Theo kiểu liệt kê đối tượng."], correctIndex: 3 },
                    { id: "q22", text: "Câu 22: Việc đề cập đến các kho, vựa, nhà máy tên tuổi ở đoạn (3) có vai trò gì trong việc thể hiện nội dung chính của văn bản?", options: ["A. Góp phần làm rõ đặc trưng của hoạt động sản xuất ở bến Bình Đông.", "B. Góp phần làm rõ đặc trưng của hoạt động kinh tế ở bến Bình Đông.", "C. Góp phần làm rõ đặc trưng của hoạt động giao thông ở bến Bình Đông.", "D. Góp phần làm rõ đặc trưng của hoạt động nghề nghiệp của người dân ở bến Bình Đông."], correctIndex: 1 },
                    { id: "q23", text: "Câu 23: Thái độ của tác giả thể hiện trong đoạn (5) là gì?", options: ["A. Tỏ ra khách quan vì những giá trị xưa, cũ sẽ dần bị thay thế theo thời gian.", "B. Tiếc nuối vì sự mai một của những kiến trúc cổ theo thời gian.", "C. Thích thú vì những căn nhà hiện đại là sự điểm xuyết cho kiến trúc cổ.", "D. Tiếc nhớ những cư dân gốc của dãy phố ở bến Bình Đông."], correctIndex: 1 },
                    { id: "q24", text: "Câu 24: Nhận định nào sau đây là phù hợp khi nói về chủ đề của văn bản trên?", options: ["A. Vai trò của bến Bình Đông trong không gian Chợ Lớn.", "B. Nguồn gốc hình thành bến Bình Đông trong lịch sử.", "C. Đặc điểm của bến Bình Đông trong quá khứ.", "D. Vị trí địa lý giúp bến Bình Đông thành nơi mua bán lúa gạo sầm uất."], correctIndex: 2 },
                    { id: "q25", text: "Câu 25: Dòng nào dưới đây không trình bày tác động mà văn bản có thể mang đến cho người đọc?", options: ["A. Nhận thức rõ hơn về giá trị văn hóa, lịch sử của bến Bình Đông.", "B. Trân trọng những giá trị di sản mà cha ông đã để lại.", "C. Hoài niệm, tiếc nuối với những giá trị xưa cũ đang dần mai một.", "D. Hiểu rõ hơn về những thách thức của công tác bảo tồn văn hóa."], correctIndex: 3 }
                ]
            },

            // Reading Group 2
            {
                id: "reading_26_30",
                section: "SỬ DỤNG NGÔN NGỮ",
                type: "reading_group",
                passage: "<strong>Dựa vào thông tin dưới đây để trả lời câu từ 26 đến 30</strong><br><br>(1) Học văn là học tha nhân mà cũng đồng thời là học bản thân ta. Ta học bảng tuần hoàn Mendeleev là học tri thức do nhà bác học cung cấp. Còn ta học tác phẩm của L. Tolstoi là vừa học những tâm hồn Nga yêu chuộng hòa bình, chán ghét chiến tranh, vừa học tiếng vang của nó vào tâm hồn ta, xem cách ta bắt lấy và đón nhận tín hiệu từ tác phẩm đó. Nếu ta chỉ thâu nhận nội dung và các thủ pháp nghệ thuật trong tiểu thuyết như các nguyên tố hóa học của bảng tuần hoàn thì mãi mãi ta không hiểu gì văn học mà cũng không hiểu gì bản thân ta.<br><br>(2) Học văn là học kinh nghiệm làm người ở đời để chính mình tự quyết lấy cuộc đời mình. Vì không ai có thể thay ta đưa ra lời giải bài toán cuộc đời ta. Người học văn vì tiếp xúc với nhiều cuộc đời trong sách vở nên có thể lúng túng, lưỡng lự, phân vân và băn khoăn khi va chạm với cuộc đời thực tế. Ta tham khảo từ những cuộc đời đó để rồi đưa ra giải pháp của riêng ta.<br><br>(3) Học văn là học cách ứng xử với quá khứ, đối mặt với hiện tại và dự báo cho tương lai. Vì vậy mà chúng ta cần cả văn chương dấn thân lẫn văn chương viễn mơ, cần cả tiểu thuyết lịch sử, tiểu thuyết hiện thực lẫn tiểu thuyết viễn tưởng. Học văn là để mở rộng chiều kích cuộc đời ta, để ta không biến thành “con người một chiều kích” như Herbert Marcuse cảnh báo từ những năm 60 thế kỷ trước.<br><br>(4) Học văn là học sống ở đời giữa muôn người cũng đồng thời là học làm người tự do lựa chọn. Theo tinh thần của Jean-Paul Sartre, con người bị buộc phải tự do, có tự do mới có lựa chọn. Lựa chọn chỉ có ý nghĩa khi lựa chọn trong tự do. Nhưng tự do của ta không đối lập với tự do của người khác, tự do của ta chỉ có ý nghĩa khi hiện hữu cùng tự do của người khác.<br><i>(Huỳnh Như Phương, Hồi âm từ phương Nam)</i>",
                subQuestions: [
                    { id: "q26", text: "Câu 26: Trong đoạn (2), câu nào chứa luận điểm?", options: ["A. Học văn là học kinh nghiệm làm người ở đời để chính mình tự quyết lấy cuộc đời mình.", "B. Vì không ai có thể thay ta đưa ra lời giải bài toán cuộc đời ta.", "C. Người học văn vì tiếp xúc với nhiều cuộc đời trong sách vở nên có thể lúng túng, lưỡng lự, phân vân và băn khoăn khi va chạm với cuộc đời thực tế.", "D. Ta tham khảo từ những cuộc đời đó để rồi đưa ra giải pháp của riêng ta."], correctIndex: 0 },
                    { id: "q27", text: "Câu 27: Trong đoạn (3), cụm từ “con người một chiều kích” được sử dụng theo biện pháp tu từ nào?", options: ["A. Nhân hóa.", "B. So sánh.", "C. Ẩn dụ.", "D. Nói quá."], correctIndex: 2 },
                    { id: "q28", text: "Câu 28: Việc tác giả nhắc đến các tên tuổi “L. Tolstoi, Herbert Marcuse” ở đoạn (1) và đoạn (3) nhằm mục đích gì?", options: ["A. Giới thiệu vấn đề.", "B. Giải thích vấn đề.", "C. Chứng minh vấn đề.", "D. Phản biện vấn đề."], correctIndex: 2 },
                    { id: "q29", text: "Câu 29: Tác giả thể hiện quan điểm nào trong bài viết?", options: ["A. Việc học môn văn cũng giống như việc học môn hóa, bồi đắp lòng hiếu tri nơi người học.", "B. Sự lúng túng, lưỡng lự và băn khoăn của người học văn khi va chạm với cuộc đời là điều cần tránh.", "C. Hình mẫu “con người một chiều kích” là đối tượng siêu việt mà người học văn cần trở thành.", "D. Học văn là hành trình kết hợp giữa tri nhận, phản tư và điều chỉnh để hoàn thiện con người."], correctIndex: 3 },
                    { id: "q30", text: "Câu 30: Ý nghĩa nào của việc học văn không được đề cập trong văn bản?", options: ["A. Mở ra cho con người một hành trình tự hiểu biết bản thân và người khác.", "B. Bồi đắp con người sự hiểu biết và mẫn tiệp của tâm hồn phong phú.", "C. Giữ vai trò như một nghi lễ bắt buộc, đánh dấu sự trưởng thành của con người.", "D. Hướng đến sự hình thành ý thức tự do của mỗi người."], correctIndex: 2 }
                ]
            }
        ]
    }
];
`;

data = data.replace(/\s*\];\s*$/, newQuiz);
fs.writeFileSync(dataJsPath, data);
console.log('Appended Quiz 1 to data.js');
