const fs = require('fs');
const path = require('path');

const quiz2 = {
    id: "de_2_dgnl",
    title: "Đề 2: Đề chính thức Đợt 1 - 2026 (Phục dựng)",
    description: "Phần 1: Ngôn ngữ (60 câu) & Phần 2: Toán học (30 câu) & Phần 3: Tư duy khoa học (30 câu)",
    questions: [
        // 1 - 20 (Tiếng Việt)
        { id: "q1", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 1: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] “Toàn thân nàng biến thành một thân cây, chân như cắm sâu xuống đất và các ngón chân vươn dài ra thành những rễ lớn rễ nhỏ. Mái tóc đẹp đẽ của nàng biến thành những lá cây. Apollon chạy đến nơi thì nàng trinh nữ xinh đẹp Daphné đã biến thành một cây nguyệt quế xanh tươi, tự nhiên như đã mọc lên từ ngàn xưa và từ ngàn xưa vốn tự nhiên và xanh tươi như vậy.”\n(Nguyễn Văn Khỏa, Thần thoại Hy Lạp)\nNgoại hình của nàng Daphné được miêu tả bởi những biện pháp tu từ nào?", options: ["A. Ẩn dụ, hoán dụ.", "B. Liệt kê, nhân hóa.", "C. Nhân hóa, hoán dụ.", "D. So sánh, liệt kê."], correctIndex: 3 },
        { id: "q2", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 2: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] “Ngày ấy thú vật hãy còn làm chủ mặt đất chưa có dấu tích con người. Một hôm có một cây si bị bão đổ xuống trong đó bay ra hai con chim lớn gọi là Áccác Ùaquê (hay Ay và Ua). Chúng đến làm tổ ở động Hào và đẻ trăm trứng trong đó có 3 cái to lớn dị thường. Nhờ được thần bày cho cách ấp, sau 50 ngày 97 trứng nở ra người: 50 người đi về mạn đồng bằng thành người Kinh, còn 47 người lần lên mạn ngược sau trở thành tổ tiên các dân Lào, Mường, Mán, Thổ,... Còn lại ba trứng ấp đủ 100 ngày nở ra ba người hai trai một gái. Đại ca, anh cả được tộc trưởng người Kinh và người Mường Mán rước về làm Lang, nhưng bị yêu tinh đón đường ăn thịt”.\n(Nguyễn Đổng Chi, Tác phẩm được tặng giải thưởng Hồ Chí Minh)\nĐoạn trích trên thuộc thể loại văn học dân gian nào?", options: ["A. Sử thi.", "B. Thần thoại.", "C. Truyền thuyết.", "D. Truyện truyền kỳ."], correctIndex: 1 },
        { id: "q3", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 3: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] \n“Tam nguyệt xuân thì trưởng đậu miêu,\nHoàng hồ phì mãn, bạch hồ kiêu.\nChủ nhân tại lữ bất quy khứ,\nKhả tích Hồng sơn thuộc vãn tiều”.\nDịch thơ:\n“Tiết tháng ba xuân đậu nảy đều,\nCầy vàng béo mập, trắng sinh kiêu.\nChủ nhân vắng mãi chưa về được,\nPhó thác Hồng sơn mặc chú tiều”.\n(Nguyễn Du, Ngẫu hứng I)\nCác câu thơ nào niêm với nhau trong bài thơ thất ngôn tứ tuyệt trên?", options: ["A. Câu 1 niêm với câu 3, câu 2 niêm với câu 4.", "B. Câu 1 niêm với câu 2, câu 3 niêm với câu 4.", "C. Câu 1 niêm với câu 4, câu 2 niêm với câu 3.", "D. Cả bốn câu đều không niêm với nhau."], correctIndex: 2 },
        { id: "q4", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 4: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] \n“Gõ cửa làm chi quấy cả ngày,\nHỏi ra mới biết lão ăn mày.\nĂn mày chớ có ăn tao nhé\nGạo kém, đồng khô thế mới rầy”.\n(Nguyễn Khuyến, Ăn mày)\nBiện pháp tu từ nào đã được tác giả sử dụng trong dòng thơ thứ ba?", options: ["A. Chêm xen.", "B. Nhân hóa.", "C. Liệt kê.", "D. Chơi chữ."], correctIndex: 3 },
        { id: "q5", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 5: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] \n“Yêu thay miền thôn tịch!\nCư xử dầu lòng, Ngao du mặc thích.\nKhéo chiều người mến cảnh yên hà;\nDễ mến khách vui miền tuyền thạch”.\n(Nguyễn Hàng, Tịch cư ninh thể phủ)\nNội dung chính được thể hiện trong đoạn trích trên là gì?", options: ["A. Khí phách ngang tàng của bậc anh hùng tráng sĩ giữa tự nhiên rộng lớn, mang chiều kích vũ trụ.", "B. Tình yêu và niềm vui thích của nhân vật trữ tình dành cho miền thôn quê u tịch, tiêu điều, nghèo khó.", "C. Đời sống cư dân thôn quê mang vẻ đẹp thanh bình, nhộn nhịp được miêu tả qua lối viết giàu nhạc tính.", "D. Lòng yêu thích sự tự do, không ràng buộc của kẻ ẩn sĩ giữa cảnh thôn dã thênh thang, rộng rãi."], correctIndex: 3 },
        { id: "q6", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 6: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026]\n“Những ngày hè, ngọn lửa rơm cứ táp vào mặt nóng hầm hập, để nấu xong nồi cơm như thể phải “đổ mồ hôi, sôi nước mắt”. Vậy nhưng chưa bao giờ tôi nghe người dân làng tôi than thở một lời về cái bếp rơm cực nhọc đấy. Ngược lại, chúng tôi đã quá thân quen với cái mùi rơm thơm nồng và cái ngọn khói no ấm này. Những năm mất mùa, rơm nhiều mà lúa ít, cái bếp ở góc sân hay sau hè nãy cứ lạnh tanh. Từ ngoài đồng nhìn vào làng, những mái nhà tranh vắng đi ngọn khói chiều của những bếp rơm, không thấy bụng đói cồn cào nữa mà chỉ thấy một nỗi buồn dâng lên từ bốn phía.”\n(Minh Tự, Củi lửa)\nNhận xét nào sau đây là phù hợp nhất khi nói về sự thể hiện cái “tôi” nhà văn trong đoạn trích trên?", options: ["A. Cái “tôi” nhà văn mang tính trung lập, đóng vai trò thu thập thông tin và ghi chép các tập quán và sự kiện diễn ra trong đời sống người Huế.", "B. Cái “tôi” nhà văn giàu trải nghiệm thể hiện sự gắn bó với làng quê, đồng cảm sâu sắc với nỗi buồn của con người xứ Huế.", "C. Cái “tôi” nhà văn đại diện cho tầng lớp trí thức, đóng vai trò nhân chứng nhằm phát hiện và ca ngợi vẻ đẹp của con người xứ Huế.", "D. Cái “tôi” nhà văn đã được hư cấu để tái hiện khách quan những sự kiện lịch sử đã qua của cộng đồng người dân xứ Huế."], correctIndex: 1 },
        { id: "q7", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 7: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026]\n“VŨ NHƯ TÔ - Xây Cửu Trùng Đài cho một tên bạo chúa, một tên thoán nghịch, cho một lũ gái dâm ô? Tôi không thể đem tài ra làm một việc ô uế, muôn năm làm bia miệng cho người đời được.\nĐAN THIỀM - Ông biết một mà không biết hai. Ông có tài, tài ấy phải đem cống hiến cho non sông, không nên để mục nát với cỏ cây. Ông không có tiền, ông không có thể dựng lấy một tòa đài như ý nguyện. Chấp kinh, phải tòng quyền. Đây là lúc ông nên mượn tay vua Hồng Thuận mà thực hành cái mộng lớn của ông... Ông khẽ tiếng. Đó là tiểu tiết. Ông cứ xây lấy một tòa đài cao cả. Vua Hồng Thuận và lũ cung nữ kia rồi mất đi nhưng sự nghiệp của ông còn lại về muôn đời. Dân ta nghìn thu được hãnh diện, không thẹn với những cung điện đẹp của nước ngoài, thế là đủ. Hậu thế sẽ xét công cho ông, và nhớ ơn ông mãi mãi. [...]”\n(Nguyễn Huy Tưởng, Vũ Như Tô)\nNhận xét nào sau đây phù hợp với nhân vật Đan Thiềm trong đoạn trích trên?", options: ["A. Đan Thiềm là người biết khích lệ người tài thực hiện những khát khao sáng tạo bị kìm nén.", "B. Đan Thiềm là một cung nữ tài sắc vẹn toàn, có lương tâm và trách nhiệm.", "C. Đan Thiềm là người có tài năng không thua kém Vũ Như Tô, xứng đáng được lưu danh.", "D. Đan Thiềm là người có sự trải đời, ý thức được những mánh khóe để tồn tại trong cung."], correctIndex: 0 },
        { id: "q8", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 8: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026]\n“rồi chúng ta sẽ trở thành những ông già và những bà già trong một thế giới trẻ trung luôn đổi khác\n[...] những người trẻ đi qua ta không hề quen biết họ cười nói râm ran trong ánh nắng tưng bừng lễ phép chào ta nhưng trong bụng xót thương “ai nói chuyện với người già lâu được”\n[...] họ lạ lùng thấy ta cam chịu những đau khổ ta mang, họ không còn hiểu được\nnhư lúa gặt, chỉ còn cuống rạ nằm im lìm dưới những đám mây bay tan vào trong quên lãng ngàn đời như con vờ, như que diêm vụt tắt như viên sỏi dưới hè, như giọt nắng trong bài ca bất tận của cuộc đời.”\n(Lưu Quang Vũ, Không đề)\nNhận định nào sau đây thể hiện khái quát giá trị nhận thức của việc xây dựng hình ảnh đối lập giữa hình ảnh tuổi già và tuổi trẻ trong đoạn thơ?", options: ["A. Tuổi già nhất định sẽ dẫn đến sự cô độc và mất giá trị trong thế giới hiện đại, chúng ta phải tìm cách chống lại bi kịch thời gian bằng cách sống hết mình với chiều kích tối đa của đời", "B. Con người rất mong manh, dù từng là chủ nhân huy hoàng của thời đại mình, đến một ngày rồi sẽ bị giảm giá trị, mọi thành tựu, dấu ấn rồi sẽ lùi lại trước bước đi của lịch sử.", "C. Người trẻ không nên lặp lại bi kịch của thế hệ trước bằng cách giữ vững những giá trị nhân văn và loại bỏ những yếu tố cũ kỹ, lạc hậu để đón nhận tất cả những giá trị và mất mát của đời sống mới.", "D. Mặc dù thân xác tan biến vào hư vô, nhưng con người vẫn có sự hòa nhập vĩnh viễn của linh hồn vào sự sống chung của vũ trụ trong từng khoảnh khắc."], correctIndex: 1 },
        { id: "q9", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 9: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026]\n“Nhưng tôi biết cái màu đỏ ấy\nCái màu đỏ như cái màu đỏ ấy\nSẽ là bông hoa chuối đỏ tươi\nTrên đỉnh dốc cao vẫy gọi đoàn người”.\n(Nguyễn Mỹ, Cuộc chia ly màu đỏ)\n“Ta về, mình có nhớ ta\nTa về, ta nhớ những hoa cùng người.\nRừng xanh hoa chuối đỏ tươi\nĐèo cao nắng ánh dao gài thắt lưng”.\n(Tố Hữu, Việt Bắc)\nHình ảnh “hoa chuối đỏ” trong hai đoạn thơ đều thể hiện:", options: ["A. Tinh thần kiên cường, quyết chiến đấu chống giặc ngoại xâm.", "B. Sức sống, vẻ đẹp của thiên nhiên trong những cuộc kháng chiến.", "C. Sự hy sinh thầm lặng của những người phụ nữ ở hậu phương.", "D. Màu máu và sự hy sinh của những người chiến sĩ nơi tiền tuyến."], correctIndex: 1 },
        { id: "q10", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 10: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026]\n“Chú mải mê nhìn nên không nghe thấy những tiếng gõ lanh canh trên đường tàu từ xa đã đến gần.\nPíp...rù...ù...ù.\nCậu bé giật mình quay lại: một người đàn ông trẻ, khỏe mạnh, trên môi còn rung rung vì hồi còi mồm. Bộ quần áo xanh thợ nham nhở những vết gỉ sắt vàng khè hơi chật so với đôi vai rất nở. Bàn tay to bè xách chiếc búa. Khuôn mặt cởi mở và đôi mắt nom chẳng có vẻ gì là nghiêm khắc khiến chú bé mạnh dạn hẳn lên:\nChào chú!\nChào bạn!- Người đàn ông đáp lại, giọng oang oang- Bạn làm gì ở đấy?”\n(Nguyễn Thị Như Trang, Cây cúc tần)\nDòng nào dưới đây chỉ chứa những từ tượng thanh, tượng hình xuất hiện trong đoạn trích trên?", options: ["A. lanh canh, chào chú, chào bạn.", "B. oang oang, gỉ sắt, nham nhở.", "C. lanh canh, rung rung, cởi mở.", "D. oang oang, rung rung, lanh canh."], correctIndex: 3 },
        { id: "q11", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 11: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026]\n“Một tối bầu trời đắm sắc mây,\nCây tìm nghiêng xuống nhánh hoa gầy,\nHoa nghiêng xuống cỏ, trong khi cỏ\nNghiêng xuống làn rêu, một tối đầy.\nNhững lời huyền bí tỏa lên trăng,\nNhững ý bao la rủ xuống trần,\nNhững tiếng ân tình hoa bảo gió,\nGió đào thỏ thẻ bảo hoa xuân”.\n(Xuân Diệu, Với bàn tay ấy...)\nNhững hình tượng trong hai khổ thơ trên bộc lộ:", options: ["A. Sự chia lìa, mất mát của vạn vật, gợi lên niềm cô đơn trong đêm vắng quạnh quẽ.", "B. Sự quấn quyện, đan hòa của vạn vật, gợi lên niềm khao khát tương giao.", "C. Sự đối lập, tách biệt của vạn vật, gợi lên nỗi tịch liêu và sự chia cắt.", "D. Sự bí ẩn, thâm u của vạn vật, gợi lên những dự cảm về sự mất mát, hoang tàn."], correctIndex: 1 },
        { id: "q12", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 12: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026]\n“Bạch Tuyết thấy chồng thương cảm, thừa dịp nói rằng:\n- Mình đừng kêu tôi bằng cô nữa chớ. Tiếng cô nghe vô tình quá.\n- Thì em cũng đừng kêu qua bằng thầy nữa.\n- Hai người cười với nhau rồi kề vai nằm ngủ”.\n(Hồ Biểu Chánh, Ai làm được)\nPhương ngữ Nam Bộ trong đoạn trích trên không thể hiện điều gì?", options: ["A. Bản sắc địa phương của ngôn ngữ tiểu thuyết.", "B. Tính chân thực trong nghệ thuật kể chuyện.", "C. Tình cảm và quan hệ giữa các nhân vật.", "D. Sự trào phúng, đả kích các nhân vật."], correctIndex: 3 },
        { id: "q13", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 13: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Một công ty quảng bá sản phẩm sử dụng từ “thanh toán không chạm” thay vì “contactless payment”. Cách làm này có tác dụng gì?", options: ["A. Thuật ngữ tiếng Việt làm nổi bật tính tiên phong của sản phẩm trong lĩnh vực công nghệ.", "B. Thuật ngữ tiếng Việt tạo cảm giác gần gũi, dễ hiểu cho người tiêu dùng trong nước.", "C. Thuật ngữ tiếng Việt phản ánh đầy đủ tính chất của hình thức thanh toán này.", "D. Thuật ngữ tiếng Việt tạo cảm giác hiện đại, mới mẻ cho người tiêu dùng trong nước."], correctIndex: 1 },
        { id: "q14", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 14: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Trong các câu sau, câu nào đúng ngữ pháp?", options: ["A. Trong khi quá vui sướng và bất ngờ vì món quà anh tặng bởi vì tôi không biết làm sao để bày tỏ lòng biết ơn.", "B. Ngày hôm qua, chị vừa về đến nhà thì nhìn thấy đôi chim sổ lồng, tung cánh bay vút lên bầu trời mênh mông, xanh biếc.", "C. Trên dòng sông có những cánh buồm trắng nên thơ, những con thuyền nằm mơ mộng về vùng trời khác lạ, những gợn sóng nhỏ lăn tăn ấy.", "D. Với chị vào những ngày hè gió thổi hây hẩy trên những vòm cây lá lao xao, ở miền quê ngoại có triền đê xanh mướt cỏ non trải dài tít tắp như chạm vào chân trời."], correctIndex: 1 },
        { id: "q15", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 15: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] “Bàn về cách nhìn nhận và đánh giá con người, cố nhân có câu “họa hổ họa bì nan họa cốt, tri nhân tri diện bất tri tâm”, nghĩa là vẽ hổ có thể vẽ được da, khó vẽ được xương; biết người chỉ biết mặt, khó biết lòng”.\nCâu trên mắc lỗi gì?", options: ["A. Sai ngữ pháp.", "B. Sai logic.", "C. Sai dùng từ.", "D. Sai phong cách."], correctIndex: 1 },
        { id: "q16", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 16: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Cụm từ nào sau đây viết đúng chính tả?", options: ["A. Quẩn trí, nghĩ quẫn, túng quẫn.", "B. Quẩn trí, nghĩ quẩn, túng quẫn.", "C. Quẫn trí, nghĩ quẩn, túng quẫn.", "D. Quẫn trí, nghĩ quẫn, túng quần."], correctIndex: 0 },
        { id: "q17", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 17: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Câu nào sau đây có từ sai chính tả?", options: ["A. Anh bàng hoàng, ngơ ngác nhìn quanh như vừa tỉnh giấc mộng.", "B. Treo cờ rũ là nghi thức đặc biệt, chỉ thực hiện khi có quốc tang.", "C. Các cầu thủ ủ rũ rời sân, cúi đầu bước chậm vào đường hầm sau trận đấu.", "D. Từ điển tiếng Việt giải nghĩa “bàn hoàn” là nghĩ quanh quẩn, không dứt ra được."], correctIndex: 1 },
        { id: "q18", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 18: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Từ “chịu” trong câu nào sau đây có thể được hiểu theo nghĩa “tiếp nhận một tác động từ bên ngoài”?", options: ["A. Việt Nam đứng thứ 6 trong số các quốc gia chịu ảnh hưởng nặng nề từ sự biến đổi khí hậu trên thế giới.", "B. Mua hàng không kiểm tra kỹ, nhận về sản phẩm lỗi thì đành bụng làm dạ chịu, không thể trách người bán.", "C. Khi các công ty tăng cường thực hiện chính sách bán chịu thì sẽ làm tăng khả năng sinh lợi của công ty.", "D. Cuộc tranh chấp bản quyền truyền hình vẫn chưa đi đến hồi kết, khi các bên đều cho rằng mình có lý và không ai chịu ai."], correctIndex: 0 },
        { id: "q19", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 19: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] “Lục” trong câu nào sau đây không cùng nghĩa với “lục” trong các câu còn lại?", options: ["A. Lục quân hai nước đã phối hợp chặt chẽ, thực hiện huấn luyện đúng kế hoạch, bảo đảm an toàn tuyệt đối.", "B. Diệp lục là hợp chất tự nhiên làm cho lá cây có màu xanh, đóng vai trò chính trong quá trình quang hợp.", "C. U23 Việt Nam đang tạo nên cơn địa chấn tại đấu trường châu lục sau khi giành trọn vẹn 6 điểm sau hai lượt trận mở màn.", "D. Khi phần lớn, thậm chí toàn bộ các khối đất liền trên hành tinh hợp thành một cấu trúc, siêu lục địa sẽ hình thành."], correctIndex: 2 },
        { id: "q20", section: "SỬ DỤNG NGÔN NGỮ", text: "Câu 20: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Câu nào sau đây có sử dụng biện pháp lặp cấu trúc?", options: ["A. Đắc nhân tâm là một cuốn sách kinh điển, một cuốn sách gối đầu giường.", "B. Đa nghĩa, đồng nghĩa, đồng âm là phương tiện tạo ra các nghĩa hình tượng.", "C. Ngôn từ thi ca khác văn xuôi bởi quan hệ đặc biệt giữa từ ngữ với tư duy.", "D. Gương mặt kịch nghệ không được vẽ ra (bằng cách đánh phấn), nó được viết."], correctIndex: 0 },

        // Reading Group 21-25
        {
            id: "reading_21_25_d2",
            section: "SỬ DỤNG NGÔN NGỮ",
            type: "reading_group",
            passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 21 đến 25</strong><br><br>“(1) Con người thường cảm thấy vui sướng khi nhận ra bản thân mình đang dần trưởng thành. Ví dụ trong một trò game có tính gây nghiện, những người thiết kế game đều phải cài đặt những bước “trưởng thành” cho game thủ ở những yếu tố quan trọng như level, rank,... để khiến họ càng đắm chìm hơn trong game.<br><br>(2) Nếu trong trò giải trí, trưởng thành là cội nguồn của niềm vui, thì trong công việc, điều này còn cần thiết hơn. Vì sự trưởng thành trong công việc sẽ khiến chúng ta thấy yêu thích công việc đó. Ví dụ khi làm thêm ở cửa hàng tiện lợi, cả ngày phải đứng quét mã vạch hàng hóa, chắc sẽ không ai định làm công việc này cả đời vì chẳng có gì thú vị, mà cũng chẳng kiếm được bao nhiêu. Vì vậy, đa số chỉ tranh thủ làm thêm để kiếm chút tiền công nhật. Nhưng nếu nghĩ khác đi thì công việc này mang lại nhiều giá trị hơn so với chỗ tiền công ấy. Chẳng hạn chúng ta có thể hiểu thêm về hành vi mua sắm của người tiêu dùng, nắm được đặc điểm vị trí của cửa hàng, học được phương pháp quản lý kho khi nhận hàng mới. Nhờ vậy, chúng ta có thể tận hưởng niềm vui “học hỏi và trưởng thành” mỗi ngày, và có thể điềm nhiên nói rằng mình yêu công việc đó. Rồi khi sự nghiệp của bản thân mở ra, quá trình trưởng thành trên sẽ là nền tảng dẫn dắt sự nghiệp đó đến thành công lớn. Điều quan trọng là tập trung vào điều mình quan tâm, và khát khao học hỏi, tích lũy kinh nghiệm từ những điều nhỏ nhất.<br><br>(3) Đương nhiên, tiền cũng là bằng chứng cho thấy giá trị công việc và sức lao động của mình. Nếu bạn kiếm tiền vì trách nhiệm với bản thân và gia đình, bạn sẽ thấy thiết tha với công việc và có động lực làm việc tốt hơn. Nhưng nếu bị giam hãm trong suy nghĩ phải kiếm thật nhiều tiền, chúng ta sẽ trở thành tù nhân của công việc. Điều thật sự quan trọng không phải là thu nhập nhiều hay ít, mà là niềm vui của sự trưởng thành và tình yêu trong công việc. Cứ thế, lúc bạn từng bước tiến gần hơn đến “hình ảnh hoàn thiện nhất” của bản thân, tiền sẽ tự nhiên đi theo bạn.”<br><i>(Theo Random Kim, Trưởng thành sau ngàn lần tranh đấu)</i>",
            subQuestions: [
                { id: "q21", text: "Câu 21: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Xác định bằng chứng được sử dụng trong văn bản trên.", options: ["A. Cách những người thiết kế game tạo ra niềm khao khát chinh phục ở người chơi.", "B. Cách mà đồng tiền chứng minh cho giá trị công việc và sức lao động của bản thân.", "C. Cách một người làm thêm ở cửa hàng tiện lợi tìm thấy niềm yêu thích trong công việc.", "D. Cách đồng tiền giam hãm chúng ta và biến chúng ta thành tù nhân của công việc."], correctIndex: 2 },
                { id: "q22", text: "Câu 22: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Dòng nào dưới đây nêu đúng cách sắp xếp, trình bày luận điểm, lý lẽ và bằng chứng trong văn bản?", options: ["A. Triển khai luận điểm thành các lý lẽ, bằng chứng, sau đó tổng hợp, mở rộng luận điểm.", "B. Nêu các lý lẽ, bằng chứng cụ thể, sau đó khái quát, tổng hợp thành luận điểm.", "C. Nêu luận điểm, sau đó triển khai thành các lý lẽ, bằng chứng cụ thể.", "D. Trình bày các lý lẽ, bằng chứng tương đối độc lập và hướng đến luận điểm ẩn."], correctIndex: 2 },
                { id: "q23", text: "Câu 23: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Dòng nào dưới đây có thể khái quát nhất tác động của văn bản đến quan niệm sống của người đọc?", options: ["A. Quan tâm nhiều hơn đến những giá trị mà chúng ta có thể nhận về từ những hoạt động quen thuộc.", "B. Nhận ra sự trưởng thành đem đến niềm vui cho con người trong cả công việc lẫn cuộc sống.", "C. Cần chuyên chú ngay từ những việc nhỏ nhặt vì nó giúp con người sống có mục tiêu cụ thể hơn.", "D. Tránh cái nhìn thờ ơ, đơn giản vì cuộc sống vốn phức tạp và chứa đựng nhiều cơ hội học tập."], correctIndex: 1 },
                { id: "q24", text: "Câu 24: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Câu chuyện về việc làm thêm tại cửa hàng tiện lợi có vai trò gì trong văn bản?", options: ["A. Nêu sự việc cho thấy cách nhìn nhận cuộc sống thay đổi có thể khiến công việc dễ thành công hơn.", "B. Nêu sự việc cho thấy quá trình học hỏi và trưởng thành có thể đến từ những việc bình thường nhất.", "C. Nêu sự việc cho thấy cách chúng ta có thể tạo dựng sự nghiệp thành công từ những việc nhỏ nhặt.", "D. Nêu sự việc cho thấy sự chuyên chú, thay đổi tư duy là yếu tố tiên quyết đưa đến sự thành công."], correctIndex: 1 },
                { id: "q25", text: "Câu 25: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Văn bản có đề cập đến quan điểm: Điều thật sự quan trọng không phải là thu nhập nhiều hay ít, mà là niềm vui của sự trưởng thành và tình yêu trong công việc.\nĐánh giá nào dưới đây thể hiện cách nhìn phê phán phù hợp đối với quan điểm trên?", options: ["A. Quan điểm trên hoàn toàn đúng vì trong mọi công việc, chúng ta cần đặt niềm vui và sự thoải mái lên hàng đầu, đó là nền tảng dẫn dắt sự nghiệp đến thành công.", "B. Quan điểm trên chưa phù hợp với thực tế vì trong công việc, mỗi người cần phải ưu tiên thu nhập trước để có thể hoàn thành trách nhiệm với bản thân và gia đình họ.", "C. Quan điểm trên còn phiến diện vì chỉ tập trung nhấn mạnh vào niềm vui của sự trưởng thành mà chưa quan tâm đến những khó khăn nảy sinh trong môi trường công việc.", "D. Quan điểm trên có ý nghĩa tích cực khi nhấn mạnh giá trị học hỏi do công việc mang lại, nhưng trên thực tế cần cân bằng giữa sự phát triển bản thân và giá trị thu nhập từ công việc."], correctIndex: 3 }
            ]
        },

        // Reading Group 26-30
        {
            id: "reading_26_30_d2",
            section: "SỬ DỤNG NGÔN NGỮ",
            type: "reading_group",
            passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 26 đến 30</strong><br><br>“(1) Dân trí tài chính là mức độ hiểu biết, kỹ năng, thái độ để đưa ra các quyết định tài chính đúng đắn và quản lý tài chính cá nhân hiệu quả. Nó có thể được đo qua: (i) mức độ hiểu biết kiến thức tài chính; (ii) khả năng quản lý tài chính cá nhân và ra quyết định tài chính; (iii) mức độ tiếp cận và sử dụng dịch vụ tài chính. Tại Việt Nam, cách thứ ba thường được sử dụng và cho thấy thực trạng dân trí tài chính còn khá thấp. Theo Ngân hàng Thế giới (2021), tỷ lệ người Việt Nam có tài khoản ngân hàng chỉ đạt 69%, thấp hơn các nước phát triển (80-100%). Hoặc theo Ủy ban Chứng khoán Nhà nước (2023), số lượng tài khoản chứng khoán tại Việt Nam chỉ chiếm hơn 7% quy mô dân số.<br><br>(2) Dân trí tài chính thấp có thể dẫn đến những hệ quả như mất tiền trong các vụ lừa đảo tài chính, đầu tư sai, mất vốn, khủng hoảng nợ cá nhân, thiếu chuẩn bị cho tương lai tài chính.<br><br>(3) Khảo sát của nhóm nghiên cứu cho thấy gần 75% số người được hỏi cho rằng giáo dục tài chính cho trẻ em là cần thiết. Điều này rất quan trọng vì: – Trẻ em và thanh thiếu niên thường tiếp xúc với gia đình, nhà trường, xã hội và các chính sách nhà nước, nên có cơ hội tiếp nhận sự giáo dục tài chính từ nhiều phía. – Khi được giáo dục tài chính sớm, kiến thức và thói quen tài chính tốt không chỉ ảnh hưởng đến các em mà còn có thể tạo ra những tác động tích cực, bền vững cho toàn xã hội. – Tuổi thiếu niên thuộc giai đoạn đầu của vòng đời tài chính, khi các em bắt đầu tiếp thu những kiến thức cơ bản về tài chính. Sau đó là giai đoạn tích lũy tài sản. Để tích lũy hiệu quả, các cá nhân cần có hiểu biết và kỹ năng để lập kế hoạch tài chính, đầu tư và quản lý nợ, chuẩn bị tốt hơn cho những giai đoạn tiếp theo của cuộc đời (bảo vệ tài sản và tiêu dùng trong hưu trí).<br><br>(4) Như vậy, giáo dục tài chính cho trẻ em là yêu cầu cấp bách, góp phần nâng cao dân trí tài chính, giảm thiểu rủi ro và cải thiện khả năng đạt các mục tiêu tài chính dài hạn.”<br><i>(Theo Phạm Thị Thành - Lê Hoàng Gia Bảo, trích Giáo dục tài chính cho trẻ em)</i>",
            subQuestions: [
                { id: "q26", text: "Câu 26: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Văn bản trên đã sử dụng những cách trình bày thông tin nào sau đây?", options: ["A. Liệt kê, vấn đề và cách giải quyết.", "B. Liệt kê, quan hệ nhân - quả.", "C. Liệt kê, phân loại đối tượng.", "D. Liệt kê, so sánh và đối chiếu."], correctIndex: 0 },
                { id: "q27", text: "Câu 27: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Việc trích dẫn số liệu của ngân hàng thế giới (2021) và Ủy ban Chứng khoán Nhà nước (2023) có tác dụng gì?", options: ["A. Cung cấp minh chứng cụ thể đáng tin cậy cho thấy biểu hiện của thực trạng dân dân trí tài chính ở Việt Nam giai đoạn 2021-2023.", "B. Cung cấp minh chứng cụ thể về tỉ lệ người Việt Nam được tiếp cận với các dịch vụ tài chính trong giai đoạn 2021-2023.", "C. Cung cấp minh chứng cụ thể cho thấy khả năng khai thác các dịch vụ tài chính ở Việt Nam còn thấp so với quy mô dân số.", "D. Cung cấp minh chứng củng cố cho nhận định về thực trạng dân trí tài chính ở Việt Nam và cách thức đo lường thực trạng ấy."], correctIndex: 3 },
                { id: "q28", text: "Câu 28: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Quan điểm chính của người viết được thể hiện qua văn bản là gì?", options: ["A. Cảnh báo thực trạng người Việt có hiểu biết kỹ năng và thái độ với lĩnh vực tài chính còn thấp và hệ quả.", "B. Khẳng định thực trạng dân trí tài chính của Việt Nam còn ở mức thấp và tính khách quan của các nhận định.", "C. Nhận định thực trạng dân trí tài chính ở Việt Nam của nước ta thấp và cần thiết giáo dục tài chính cho trẻ em.", "D. Khách quan cung cấp thông tin về cách đo lường dân trí tài chính và lý do cần giáo dục tài chính cho trẻ em."], correctIndex: 2 },
                { id: "q29", text: "Câu 29: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Việc mở đầu đoạn (3) bằng một kết quả khảo sát có tác dụng gì?", options: ["A. Cung cấp bằng chứng khách quan, khẳng định sự đồng thuận giữa ý kiến của tác giả với số đông.", "B. Cung cấp tín hiệu chuyển tiếp tự nhiên, gắn kết với thực tiễn từ phần nêu thực trạng đến đề xuất giải pháp.", "C. Cung cấp kết quả khảo sát thực tế, tạo hứng thú cho người đọc bằng một bằng chứng ấn tượng.", "D. Cung cấp kết quả khảo sát thực tế, tạo tính xác thực, khách quan cho lập luận và dẫn dắt vào những lý do tiếp theo."], correctIndex: 3 },
                { id: "q30", text: "Câu 30: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Dòng nào dưới đây không thể hiện ý nghĩa mà văn bản có thể đem đến cho người đọc?", options: ["A. Nhận thức đầy đủ, rõ ràng hơn về khái niệm dân trí tài chính và thực trạng ấy ở Việt Nam.", "B. Nâng cao nhận thức của người đọc về tầm quan trọng của việc giáo dục tài chính cho trẻ em.", "C. Trang bị cho người đọc hiểu biết về các kỹ năng tài chính và biểu hiện lừa đảo tài chính.", "D. Cần có hành động tích cực, tự chủ trong việc tìm hiểu kiến thức tài chính từ khi còn nhỏ."], correctIndex: 2 }
            ]
        },

        // 31 - 45 (Tiếng Anh)
        { id: "q31", section: "1.2. TIẾNG ANH", text: "Câu 31: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Business people look _______ selling as many of their products as possible.", options: ["A. ahead", "B. forward to", "C. out for", "D. into"], correctIndex: 2 },
        { id: "q32", section: "1.2. TIẾNG ANH", text: "Câu 32: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Being used in nearly all walks of life, QR codes bring us _______ convenience.", options: ["A. desirable", "B. desirability", "C. desire", "D. desirably"], correctIndex: 0 },
        { id: "q33", section: "1.2. TIẾNG ANH", text: "Câu 33: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Don’t rush. We still have _______ time to make an impressive presentation by the end of April.", options: ["A. a lot", "B. most", "C. many of", "D. plenty of"], correctIndex: 3 },
        { id: "q34", section: "1.2. TIẾNG ANH", text: "Câu 34: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Most employers look for critical thinking skills, so I _______ hard for them now that I’m in college.", options: ["A. was training", "B. trained", "C. would have trained", "D. am training"], correctIndex: 3 },
        { id: "q35", section: "1.2. TIẾNG ANH", text: "Câu 35: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Small handmade gifts are often considered _______ store-bought gifts or money gifts.", options: ["A. the most meaningful", "B. as meaningful", "C. more meaningful", "D. as meaningful as"], correctIndex: 2 },
        { id: "q36", section: "1.2. TIẾNG ANH", text: "Câu 36: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Find the error:\nWhen <u>my</u> friends and I <u>plan</u> a trip, our teacher always gives <u>them</u> useful advice about <u>staying safe</u>.", options: ["A. staying safe", "B. plan", "C. them", "D. my"], correctIndex: 2 },
        { id: "q37", section: "1.2. TIẾNG ANH", text: "Câu 37: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Find the error:\n<u>As a</u> professional dancer, Laura makes beautiful <u>moves</u>, but her singing <u>are</u> not <u>as attractive</u>.", options: ["A. as attractive", "B. are", "C. moves", "D. As a"], correctIndex: 1 },
        { id: "q38", section: "1.2. TIẾNG ANH", text: "Câu 38: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Find the error:\n<u>Mary’s picture’s</u> in <u>her</u> school brochure shows that <u>She</u> is leading a <u>group discussion</u>.", options: ["A. her", "B. Mary’s picture’s", "C. group discussion", "D. She"], correctIndex: 1 },
        { id: "q39", section: "1.2. TIẾNG ANH", text: "Câu 39: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Find the error:\nThe student, <u>who</u> hard work impressed <u>all the</u> teachers, <u>was</u> finally rewarded <u>with</u> some scholarships.", options: ["A. with", "B. was", "C. all the", "D. who"], correctIndex: 3 },
        { id: "q40", section: "1.2. TIẾNG ANH", text: "Câu 40: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Find the error:\nThere was <u>the football match</u> in <u>the neighborhood</u>, but <u>the event</u> attracted <u>too few</u> spectators.", options: ["A. the event", "B. too few", "C. the football match", "D. the neighborhood"], correctIndex: 2 },
        { id: "q41", section: "1.2. TIẾNG ANH", text: "Câu 41: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Which of the following best restates the given sentence?\nMini is obviously the cutest poodle on the puppy farm I’ve just visited.", options: ["A. As a cute poodle I’ve just visited, Mini is definitely the most beautiful of all the puppies.", "B. It is a matter of fact that no puppy is as cute as Mini on the poodle farm I’ve just visited.", "C. As the cutest puppy on the farm I’ve just visited, Mini is certainly a beautiful poodle.", "D. It is for sure that no other poodle on the puppy farm I’ve just visited is cuter than Mini."], correctIndex: 3 },
        { id: "q42", section: "1.2. TIẾNG ANH", text: "Câu 42: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Which of the following best restates the given sentence?\nThose who start first will come last.", options: ["A. Start first or you will come last.", "B. The first starters will be the last finishers.", "C. Unlike those who start first, you will come last.", "D. First, start with those who will come last."], correctIndex: 1 },
        { id: "q43", section: "1.2. TIẾNG ANH", text: "Câu 43: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Which of the following best restates the given sentence?\nI felt unhappy when Tim said some bad words last night.", options: ["A. Unless Tim said good words, I would feel unhappy.", "B. If Tim does not say bad words, I will feel very happy.", "C. If Tim had not said some bad words the night before, I would not have felt unhappy.", "D. If Tim did not say some bad words the night before, I would not feel unhappy."], correctIndex: 2 },
        { id: "q44", section: "1.2. TIẾNG ANH", text: "Câu 44: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Which of the following best restates the given sentence?\nA police officer said to a teenager, “Don’t walk alone down this street at night. It’s not safe!”", options: ["A. A police officer reminded a teenager not to walk alone down this street at night because it was not safe.", "B. A police officer said a teenager should not walk alone down this street at night because it wasn’t safe.", "C. A police officer told a teenager not to walk alone down that street at night because it was not safe.", "D. A police officer told a teenager don’t walk alone down that street at night because it was not safe."], correctIndex: 2 },
        { id: "q45", section: "1.2. TIẾNG ANH", text: "Câu 45: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Which of the following best restates the given sentence?\nFrequent meetings discourage the new manager considerably.", options: ["A. The new manager is considerably discouraged by frequent meetings.", "B. The new manager considerably discourages frequent meetings.", "C. The new manager’s frequent meetings are considerably discouraging.", "D. Frequent meetings are considered as a discouragement by the new manager."], correctIndex: 0 },

        // Reading Group 46-52
        {
            id: "reading_46_52_d2",
            section: "1.2. TIẾNG ANH",
            type: "reading_group",
            passage: "<strong>Question 46-52: Read the passage carefully.</strong><br><br>1. Renewable energy comes from natural sources like the sun, wind, and water. These sources can be replaced faster than they are used. Renewable energy, when produced and used responsibly, is an effective solution and a long-lasting strategy to fight climate change. It helps reduce pollution and create energy systems that can last. However, we still need new technology to make them work even better.<br>2. Solar power turns sunlight into electricity using solar panels. In the past 10 years, the cost of solar energy has dropped a lot, making it cheaper. New solar panels are lighter and can even work in low sunlight. Solar power is growing fast, and countries like India, Brazil, and the U.S. are planning to double their solar energy by 2028.<br>3. Wind power has been used for many years and is a clean way to make energy. Wind turbines, which can be on land or in the ocean, turn wind into electricity. Wind farms in the ocean catch stronger winds, making more energy. The US plans to add a lot of wind power by 2030, enough to power 10 million homes. Using new technology like artificial intelligence (AI) helps predict how much wind energy will be made, which makes power sources more reliable.<br>4. Hydropower uses moving water to spin turbines and make electricity. It is the largest renewable energy source today. New technology, like small hydropower systems, is helping bring energy to rural areas without hurting the environment. Better materials, like recyclable turbines, are also making hydropower more efficient and environmentally friendly.<br>5. Other renewable energy sources are geothermal energy and bioenergy. Geothermal energy uses heat from inside the Earth, and bioenergy is made from plants and other natural materials. New ideas and improved production methods are making bioenergy cleaner, more efficient, and better for the environment. Scientists are also developing ways to turn agricultural waste and food waste into energy, which helps reduce the amount of rubbish while producing electricity and fuel. bioenergy better for the environment. These energy sources are helping to create a cleaner and greener future.",
            subQuestions: [
                { id: "q46", text: "Câu 46: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] What is the passage mainly about?", options: ["A. Providing reasons renewable energy is good for users.", "B. Comparing traditional and renewable energy resources.", "C. Describing some types of efficient renewable energy.", "D. Listing some technologies used to produce green energy."], correctIndex: 2 },
                { id: "q47", text: "Câu 47: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] What does the word “It” in paragraph 1 refer to?", options: ["A. Solution", "B. Strategy", "C. Renewable energy", "D. Climate change"], correctIndex: 2 },
                { id: "q48", text: "Câu 48: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] In paragraph 2, what can be inferred about solar power?", options: ["A. It is the most efficient out of renewable energy.", "B. Its solar panels can be used to replace lighters.", "C. It needs a lot of investment in new technology.", "D. It was much more expensive ten years ago."], correctIndex: 3 },
                { id: "q49", text: "Câu 49: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] In paragraph 3, which of the following is NOT stated about the production of wind energy?", options: ["A. The US will be producing a lot of wind power.", "B. Wind energy is not a new type of renewable energy.", "C. The production is best controlled by AI applications.", "D. Wind farms in the ocean are more productive."], correctIndex: 2 },
                { id: "q50", text: "Câu 50: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] In paragraph 4, what is mentioned about hydropower?", options: ["A. Even small hydropower systems harm the environment.", "B. Its production is better in the ocean than in rivers.", "C. It is now the biggest supply of renewable energy.", "D. It turns water into electricity, which turns turbines."], correctIndex: 2 },
                { id: "q51", text: "Câu 51: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] What is the word “recyclable” in paragraph 4 closest in meaning to?", options: ["A. Reusable", "B. Moveable", "C. Savable", "D. Reducible"], correctIndex: 0 },
                { id: "q52", text: "Câu 52: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] In paragraph 5, what does the author say about bioenergy?", options: ["A. It is available in more places due to new ideas and inventions.", "B. It is the main source of energy for a cleaner and greener future.", "C. Its input materials include plants and other materials found in nature.", "D. It uses heat from inside the Earth; therefore, it is totally natural."], correctIndex: 2 }
            ]
        },

        // Reading Group 53-60
        {
            id: "reading_53_60_d2",
            section: "1.2. TIẾNG ANH",
            type: "reading_group",
            passage: "<strong>Question 53-60: Read the passage carefully.</strong><br><br>1. High-rise buildings are now central features of many urban landscapes, offering efficient use of land and convenient access to services. However, their height, density, and complex internal structures increase fire risks. As a result, it is essential to strengthen fire-prevention practices and redesign everyday habits to create safer living environments.<br>2. Reducing fire accidents starts inside each apartment. Electrical devices are a common cause of ignition when they are damaged, cheaply made, or used carelessly. Residents have a direct duty to check wires and plugs, stop overloading sockets, replace poor-quality chargers, and unplug appliances that are not in use. Kitchens require the same level of care. Cooking should be treated as focused work, with clear surfaces and full attention. When residents adopt these habits, they create the first and strongest barrier against fire.<br>3. Building infrastructure is the next layer of protection, and it is the clear responsibility of building management. Smoke alarms, extinguishers, and emergency lighting systems must be installed correctly and tested on a regular schedule. These systems exist in many high-rise buildings, but they lose their value when inspections are delayed or problems are ignored. Elevators may fail during a fire, so managers must ensure that stairwells stay open, well lit, and free of storage items. Management should also organise regular safety checks and drills so that evacuation procedures are practical and effective.<br>4. Local governments and fire authorities hold responsibility at a wider level. Regular inspections backed by real penalties push owners and managers to maintain safe conditions. Public information campaigns can teach residents how to prevent fires and respond safely when alarms sound. When authorities take this role seriously, they create a framework in which responsible residents and managers can truly protect their buildings.<br>5. Fires have devastating consequences, but they are also preventable. When residents commit to careful daily habits and insist on properly maintained safety systems, risks can be significantly reduced. Safer behavior in tall buildings is not an optional extra or a polite suggestion; it is a duty to oneself, one’s family, and every neighbor who shares the same walls, corridors, and stairwells.",
            subQuestions: [
                { id: "q53", text: "Câu 53: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] The best title of the passage can be _______.", options: ["A. Solutions to Safety Problems in High-Rise Buildings.", "B. Reducing Fire Risks in High-Rise Buildings.", "C. Common Causes of Fires in High-Rise Buildings.", "D. Why People Avoid Living in High-Rise Buildings."], correctIndex: 1 },
                { id: "q54", text: "Câu 54: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] The word their in paragraph 1 refers to _______.", options: ["A. buildings", "B. features", "C. services", "D. landscapes"], correctIndex: 0 },
                { id: "q55", text: "Câu 55: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] In paragraph 2, the word duty is closest in meaning to _______.", options: ["A. responsibility", "B. force", "C. permission", "D. tax"], correctIndex: 0 },
                { id: "q56", text: "Câu 56: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] According to paragraph 2, cooking is advised as an activity that _______.", options: ["A. requires full attention and unoccupied areas.", "B. needs protective equipment to ensure safety.", "C. can be left unattended if the heat is low.", "D. should be done quickly to avoid accidents."], correctIndex: 0 },
                { id: "q57", text: "Câu 57: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] In paragraph 3, it is NOT mentioned that _______.", options: ["A. stairwells need to remain unlocked and unblocked.", "B. emergency lighting must be checked on a regular basis.", "C. elevators must be upgraded to prevent fire damage.", "D. smoke alarms and extinguishers must be fixed properly."], correctIndex: 2 },
                { id: "q58", text: "Câu 58: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] In paragraph 3, the author uses the phrase so that in order to _______.", options: ["A. offer a solution", "B. confirm a cause", "C. indicate a result", "D. support a point"], correctIndex: 2 },
                { id: "q59", text: "Câu 59: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] It can be inferred from paragraph 4 that public information _______.", options: ["A. can completely replace the need for inspections and penalties.", "B. mainly benefits building managers rather than residents.", "C. can guarantee that destructive fires will never happen.", "D. helps residents become more proactive in preventing fires."], correctIndex: 3 },
                { id: "q60", text: "Câu 60: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Paragraphs 2, 3, and 4 present ________ respectively as the agents to prevent fires.", options: ["A. residents, building management, and local authorities.", "B. residents, building management, and security guards.", "C. building management, residents, and local authorities.", "D. building management, residents, and national fire fighters."], correctIndex: 0 }
            ]
        },

        // 61 - 72 (Toán)
        { id: "q61", section: "PHẦN 2. TOÁN HỌC", text: "Câu 61: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Tập nghiệm của bất phương trình |2x - 3| > x + 1 là:", options: ["A. R.", "B. (-∞; 4/3).", "C. (2; +∞).", "D. (-∞; 2/3) ∪ (4; +∞)."], correctIndex: 3 },
        { id: "q62", section: "PHẦN 2. TOÁN HỌC", text: "Câu 62: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Gọi S là tập nghiệm của bất phương trình (x² + x + 3)/(x² - 4) ≥ 1. Tìm S ∩ (-2; 2).", options: ["A. ∅.", "B. (-2; 1).", "C. (-2; 2).", "D. (1; 2)."], correctIndex: 0 },
        { id: "q63", section: "PHẦN 2. TOÁN HỌC", text: "Câu 63: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Cho số thực x, y ≥ 1, ta có: log_x (y^(5x)) = log_y (x^(8y)) = 20. Tích xy là:", options: ["A. 2.", "B. 4.", "C. 10.", "D. 40."], correctIndex: 2 },
        { id: "q64", section: "PHẦN 2. TOÁN HỌC", text: "Câu 64: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Tìm tham số m để bất phương trình log_(1/5) m > log_5 (2x + 3) có đúng 3 nghiệm nguyên.", options: ["A. 1/7 < m < 1/5.", "B. 0 < m < 1.", "C. 1/7 < m < 1/3.", "D. 7/5 < m < 1/3."], correctIndex: 0 },
        { id: "q65", section: "PHẦN 2. TOÁN HỌC", text: "Câu 65: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Có 6 đỉnh A, B, C, D, E, F được vẽ như hình. Một người xuất phát từ điểm E và đi qua các đỉnh rồi kết thúc ở F. Tìm số cách người đó đi được:", options: ["A. 1.", "B. 2.", "C. 3.", "D. 4."], correctIndex: 1 },
        { id: "q66", section: "PHẦN 2. TOÁN HỌC", text: "Câu 66: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Một phân tử gồm có 8 nguyên tử liên kết. Biết phân tử này có 8 liên kết. Các nhà khoa học đã tìm được số liên kết của 7 nguyên tử đầu tiên là 4;2;2;1;1;1;1. Số liên kết nguyên tử thứ 8 là:", options: ["A. 1.", "B. 2.", "C. 3.", "D. 4."], correctIndex: 3 },
        { id: "q67", section: "PHẦN 2. TOÁN HỌC", text: "Câu 67: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Cho tam giác ABC thỏa mãn tan B / tan C = sin² B / sin² C. Tam giác ABC là tam giác gì:", options: ["A. Tam giác vuông.", "B. Tam giác cân.", "C. Tam giác đều.", "D. Tam giác có thể vuông hoặc cân."], correctIndex: 1 },
        { id: "q68", section: "PHẦN 2. TOÁN HỌC", text: "Câu 68: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Cho tam giác có độ dài các cạnh là 5; 6; 7. Hỏi đường cao ứng với cạnh 6 có độ dài là bao nhiêu?", options: ["A. √2.", "B. 2√6.", "C. √6.", "D. 3."], correctIndex: 1 },
        { id: "q69", section: "PHẦN 2. TOÁN HỌC", text: "Câu 69: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Cho ∫₁³ [(m + 1)xᵐ + 1] dx = 28. Giá trị của tham số m là:", options: ["A. Không tồn tại.", "B. m ∈ [1; 3].", "C. m ∈ (-1; 2).", "D. m ∈ [-1; 2)."], correctIndex: 1 },
        { id: "q70", section: "PHẦN 2. TOÁN HỌC", text: "Câu 70: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Cho khu vườn có dạng hình cong giới hạn bởi 2 đường thẳng y = (1/2)x² và y = √(2x). Tính diện tích khu vườn.", options: ["A. 4/3.", "B. 2/3.", "C. 5/8.", "D. 2/7."], correctIndex: 0 },
        { id: "q71", section: "PHẦN 2. TOÁN HỌC", text: "Câu 71: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Cho hàm số y = (6 - 4x)/(2x + 3) có đồ thị (C) có 2 đường tiệm cận cắt các trục tọa độ tạo thành hình chữ nhật. Tính diện tích hình chữ nhật.", options: ["A. 2.", "B. 4/3.", "C. 5/8.", "D. 3."], correctIndex: 3 },
        { id: "q72", section: "PHẦN 2. TOÁN HỌC", text: "Câu 72: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Cho hàm số f(x) = √(x² - x + 5) - √(x² + 2x + 2), trong đó f(x) là hàm lợi nhuận của công ty, x là số năm. Nếu x tăng trưởng đến vô hạn thì lợi nhuận của công ty là:", options: ["A. Công ty thua lỗ.", "B. Công ty hòa vốn.", "C. Công ty lời.", "D. Không tính được."], correctIndex: 0 },

        // Reading Groups 73-90
        {
            id: "reading_73_74_d2",
            section: "PHẦN 2. TOÁN HỌC",
            type: "reading_group",
            passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 73 đến câu 74</strong><br><br>Một xưởng sử dụng 2 loại nguyên liệu X và Y để sản xuất các loại mỹ phẩm. Biết khối lượng nguyên liệu không vượt quá 8 tạ. Sản xuất mỗi tạ nguyên liệu loại X cần 20 ngày công và lời 3 tỷ đồng. Sản xuất mỗi tạ loại Y cần 30 ngày công và lời 4 tỷ đồng. Tổng số ngày công không vượt quá 180 ngày. Gọi x là khối lượng (tạ) nguyên liệu X, và y là khối lượng (tạ) nguyên liệu Y.",
            subQuestions: [
                { id: "q73", text: "Câu 73: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Bất phương trình thỏa mãn số ngày công là:", options: ["A. 2x + 3y ≤ 18.", "B. x + y ≤ 8.", "C. x + y ≥ 8.", "D. 2x + 3y ≥ 18."], correctIndex: 0 },
                { id: "q74", text: "Câu 74: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Số tiền mà công ty thu được cao nhất là:", options: ["A. 24 tỷ.", "B. 26 tỷ.", "C. 28 tỷ.", "D. 30 tỷ."], correctIndex: 1 }
            ]
        },
        {
            id: "reading_75_76_d2",
            section: "PHẦN 2. TOÁN HỌC",
            type: "reading_group",
            passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 75 đến câu 76</strong><br><br>Một quả bóng rơi xuống đất theo thanh ngang có độ cao 10m. Mỗi lần quả bóng rơi xuống chạm đất sẽ nảy lên độ cao bằng 3/4 độ cao trước đó.",
            subQuestions: [
                { id: "q75", text: "Câu 75: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Sau 5 lần chạm đất, độ cao của quả bóng là:", options: ["A. 1,78.", "B. 2,37.", "C. 3,72.", "D. 4,25."], correctIndex: 1 },
                { id: "q76", text: "Câu 76: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Tổng quãng đường quả bóng đi được cho đến khi dừng hẳn là:", options: ["A. 10.", "B. 40.", "C. 70.", "D. 80."], correctIndex: 2 }
            ]
        },
        {
            id: "reading_77_78_d2",
            section: "PHẦN 2. TOÁN HỌC",
            type: "reading_group",
            passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 77 đến câu 78</strong><br><br>Trong không gian Oxyz cho điểm A(1;1;1), B(2;0;2), C(-2;2;4).",
            subQuestions: [
                { id: "q77", text: "Câu 77: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Độ dài đoạn thẳng AB là:", options: ["A. √2.", "B. 2√6.", "C. 2.", "D. √3."], correctIndex: 3 },
                { id: "q78", text: "Câu 78: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Mặt phẳng (ABC) cắt trục Ox tại điểm có tọa độ là:", options: ["A. (1;0;0).", "B. (0;0;0).", "C. (3;0;0).", "D. (2;0;0)."], correctIndex: 2 }
            ]
        },
        {
            id: "reading_79_81_d2",
            section: "PHẦN 2. TOÁN HỌC",
            type: "reading_group",
            passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 79 đến câu 81</strong><br><br>Lớp A có 3 học sinh, B có 2 học sinh và lớp C có 1 học sinh. Xếp 6 học sinh ngẫu nhiên này vào 1 hàng ngang 6 ghế.",
            subQuestions: [
                { id: "q79", text: "Câu 79: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Số cách sắp xếp 6 học sinh là:", options: ["A. 6!.", "B. 6! - 1.", "C. C₆⁴.", "D. A₆⁴."], correctIndex: 0 },
                { id: "q80", text: "Câu 80: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Số cách sắp xếp 2 học sinh B luôn đứng đầu hàng là:", options: ["A. 48.", "B. 60.", "C. 70.", "D. 50."], correctIndex: 0 },
                { id: "q81", text: "Câu 81: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Xác suất để học sinh lớp C chỉ ngồi cạnh học sinh lớp B là:", options: ["A. 1/5.", "B. 1/6.", "C. 2/15.", "D. 3/30."], correctIndex: 0 }
            ]
        },
        {
            id: "reading_82_84_d2",
            section: "PHẦN 2. TOÁN HỌC",
            type: "reading_group",
            passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 82 đến câu 84</strong><br><br>Trong mặt phẳng Oxy, cho các điểm A(1;2), B(-1;1), C(3;-1).",
            subQuestions: [
                { id: "q82", text: "Câu 82: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Tọa độ điểm M trung điểm BC là:", options: ["A. (1;0).", "B. (0;1).", "C. (-1;0).", "D. (0; 3/2)."], correctIndex: 0 },
                { id: "q83", text: "Câu 83: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Phương trình tổng quát đường cao AH là:", options: ["A. 2x - y = 0.", "B. x + 2y - 5 = 0.", "C. 2x + y - 3 = 0.", "D. 2x - y - 5 = 0."], correctIndex: 0 },
                { id: "q84", text: "Câu 84: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Gọi I là tâm đường tròn ngoại tiếp tam giác ABC. Tổng hoành độ và tung độ điểm I là:", options: ["A. 3.", "B. 8.", "C. 5/8.", "D. 4/3."], correctIndex: 2 }
            ]
        },
        {
            id: "reading_85_87_d2",
            section: "PHẦN 2. TOÁN HỌC",
            type: "reading_group",
            passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 85 đến câu 87</strong><br><br>Cho hình chóp S.ABCD có ABCD là hình vuông cạnh a. Tam giác SAB đều và nằm trong mặt phẳng vuông góc với mặt phẳng đáy. Gọi O là giao điểm của AC và BD, H là trung điểm cạnh AB, N là trung điểm cạnh AD.",
            subQuestions: [
                { id: "q85", text: "Câu 85: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Hình chiếu vuông góc của S lên mặt phẳng đáy là:", options: ["A. O.", "B. A.", "C. H.", "D. N."], correctIndex: 2 },
                { id: "q86", text: "Câu 86: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Khẳng định nào sau đây là sai:", options: ["A. d(D, (SAC)) = d(H, (SAC)).", "B. d(D, (SAC)) = d(B, (SAC)).", "C. V_(S.ABCD) = a³√3 / 6.", "D. SH = a√3 / 2."], correctIndex: 0 },
                { id: "q87", text: "Câu 87: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Tính khoảng cách từ D đến mặt phẳng (SAC).", options: ["A. a√21 / 7.", "B. a√2 / 2.", "C. a√21 / 14.", "D. a√25 / 48."], correctIndex: 1 }
            ]
        },
        {
            id: "reading_88_90_d2",
            section: "PHẦN 2. TOÁN HỌC",
            type: "reading_group",
            passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 88 đến câu 90</strong><br><br>Cho hàm số y = (-mx + 1)/(x - m), với m là tham số.",
            subQuestions: [
                { id: "q88", text: "Câu 88: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Khi m = 2 hàm số có giá trị lớn nhất trên đoạn [3; 5] là:", options: ["A. 3.", "B. -3.", "C. 0.", "D. 2."], correctIndex: 1 },
                { id: "q89", text: "Câu 89: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Với giá trị nào của tham số m để hàm số luôn đồng biến trên từng khoảng xác định?", options: ["A. m < -1 hay m > 1.", "B. m ≤ -1 hay m ≥ 1.", "C. m ≤ -2 hay m > 1.", "D. m ≤ -2 hay m ≥ 1."], correctIndex: 0 },
                { id: "q90", text: "Câu 90: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Với giá trị của m luôn tăng trên (3; +∞), đồ thị hàm số luôn đi qua bao nhiêu điểm cố định?", options: ["A. 1 điểm cố định.", "B. 2 điểm cố định.", "C. Vô số điểm.", "D. Không có điểm nào cố định."], correctIndex: 1 }
            ]
        },

        // Reading Group 91-93
        {
            id: "reading_91_93_d2",
            section: "PHẦN 3. TƯ DUY KHOA HỌC",
            type: "reading_group",
            passage: "<strong>3.1 LOGIC, PHÂN TÍCH SỐ LIỆU</strong><br><strong>Dựa vào đoạn thông tin sau trả lời từ câu 91 đến câu 93</strong><br><br>Một biên tập viên sẽ biên tập 7 bài viết, mỗi lần một bài. Có ba bài viết là G, H, J thuộc chủ đề tài chính, ba bài viết Q, R, S thuộc chủ đề dinh dưỡng và Y là bài viết thuộc chủ đề động vật hoang dã. Thứ tự biên tập các bài viết phải tuân theo các điều kiện sau:<br>- Các bài viết liên tiếp không được thuộc cùng một chủ đề.<br>- S chỉ có thể được biên tập trước Q nếu Q là bài viết thứ ba được biên tập.<br>- S phải được biên tập trước Y.<br>- J phải được biên tập trước G và G phải được biên tập trước R.",
            subQuestions: [
                { id: "q91", text: "Câu 91: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Đâu có thể là thứ tự biên tập đúng?", options: ["A. Q, J, S, H, Y, G, R.", "B. Q, G, S, H, Y, J, R.", "C. J, Q, S, G, H, Y, R.", "D. Q, J, Y, H, S, G, R."], correctIndex: 0 },
                { id: "q92", text: "Câu 92: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Nếu G là bài viết thứ tư được biên tập, khẳng định nào dưới đây có thể đúng?", options: ["A. Y là bài viết thứ sáu được biên tập.", "B. Q là bài viết thứ hai được biên tập.", "C. S là bài viết thứ năm được biên tập.", "D. J là bài viết thứ nhất được biên tập."], correctIndex: 0 },
                { id: "q93", text: "Câu 93: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Thứ tự biên tập có thể được xác định hoàn toàn nếu như:", options: ["A. H là bài viết thứ tư được biên tập.", "B. R là bài viết thứ bảy được biên tập.", "C. H là bài viết thứ sáu được biên tập.", "D. R là bài viết thứ tư được biên tập."], correctIndex: 0 }
            ]
        },

        // Reading Group 94-96
        {
            id: "reading_94_96_d2",
            section: "PHẦN 3. TƯ DUY KHOA HỌC",
            type: "reading_group",
            passage: "<strong>Dựa vào đoạn thông tin sau trả lời từ câu 94 đến câu 96</strong><br><br>Một công ty sắp xếp cho 5 nhân viên M, N, P, Q, R tham gia các khóa huấn luyện trong 7 ngày từ ngày thứ nhất đến ngày thứ bảy. Mỗi nhân viên sẽ được huấn luyện trong một ngày, hai nhân viên khác nhau sẽ được huấn luyện trong hai ngày khác nhau. Ngoài ra việc tổ chức tuân thủ theo các điều kiện sau đây:<br>- Không có nhân viên nào tham gia huấn luyện ở ngày thứ sáu.<br>- R được tham gia huấn luyện trước N.<br>- M phải được huấn luyện ở ngày ngay trước ngày mà Q được huấn luyện.<br>- P là người thứ ba được huấn luyện.",
            subQuestions: [
                { id: "q94", text: "Câu 94: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Nếu P được huấn luyện vào ngày thứ tư, điều nào sau đây phải đúng?", options: ["A. M được huấn luyện ở ngày thứ nhất.", "B. Không có ai huấn luyện vào ngày thứ ba.", "C. M được huấn luyện vào ngày thứ hai.", "D. R được huấn luyện vào ngày thứ năm."], correctIndex: 1 },
                { id: "q95", text: "Câu 95: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Nhân viên R có thể được huấn luyện vào ngày thứ mấy dưới đây?", options: ["A. Ngày thứ bảy.", "B. Ngày thứ hai.", "C. Ngày thứ ba.", "D. Ngày thứ tư."], correctIndex: 3 },
                { id: "q96", text: "Câu 96: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Ngày nào dưới đây bắt buộc phải có một nhân viên được huấn luyện?", options: ["A. Ngày thứ hai.", "B. Ngày thứ ba.", "C. Ngày thứ tư.", "D. Ngày thứ nhất."], correctIndex: 1 }
            ]
        },

        // Reading Group 97-99
        {
            id: "reading_97_99_d2",
            section: "PHẦN 3. TƯ DUY KHOA HỌC",
            type: "reading_group",
            passage: "<strong>Dựa vào đoạn thông tin sau trả lời từ câu 97 đến câu 99</strong><br><br>Bảng sau thể hiện sản lượng mía của một công ty mía có 6 nông trường M, N, P, Q, R, S.<br><table class=\"table table-bordered text-center\" style=\"width:auto; margin:10px auto\"><tr><th>Nông trường / Năm</th><th>M</th><th>N</th><th>P</th><th>Q</th><th>R</th><th>S</th></tr><tr><td>2016</td><td>150</td><td>75</td><td>58</td><td>48</td><td>49</td><td>32</td></tr><tr><td>2017</td><td>137</td><td>68</td><td>67</td><td>61</td><td>45</td><td>28</td></tr><tr><td>2018</td><td>160</td><td>65</td><td>82</td><td>59</td><td>46</td><td>37</td></tr><tr><td>2019</td><td>168</td><td>70</td><td>45</td><td>75</td><td>43</td><td>35</td></tr><tr><td>2020</td><td>180</td><td>55</td><td>80</td><td>67</td><td>47</td><td>28</td></tr></table>",
            subQuestions: [
                { id: "q97", text: "Câu 97: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Trong giai đoạn 2016-2020, năm nào có tổng sản lượng cao nhất?", options: ["A. 2016.", "B. 2018.", "C. 2019.", "D. 2020."], correctIndex: 3 },
                { id: "q98", text: "Câu 98: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Tổng sản lượng của công ty năm 2020 tăng bao nhiêu phần trăm so với năm 2016?", options: ["A. 7%.", "B. 9,1%.", "C. 10,9%.", "D. 13,3%."], correctIndex: 2 },
                { id: "q99", text: "Câu 99: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Từ năm 2016 đến 2020, nông trường nào tỷ lệ sản lượng tăng cao nhất?", options: ["A. M.", "B. S.", "C. Q.", "D. P."], correctIndex: 2 }
            ]
        },

        // Reading Group 100-102
        {
            id: "reading_100_102_d2",
            section: "PHẦN 3. TƯ DUY KHOA HỌC",
            type: "reading_group",
            passage: "<strong>Dựa vào đoạn thông tin sau trả lời từ câu 100 đến câu 102</strong><br><br>Biểu đồ dưới đây cho biết giá trị xuất nhập khẩu của công ty X trong giai đoạn từ 1995-2000 (đơn vị: triệu USD).<br><table class=\"table table-bordered text-center\" style=\"width:auto; margin:10px auto\"><tr><th>Năm</th><th>Nhập khẩu (triệu USD)</th><th>Xuất khẩu (triệu USD)</th></tr><tr><td>1995</td><td>120</td><td>200</td></tr><tr><td>1996</td><td>225</td><td>300</td></tr><tr><td>1997</td><td>375</td><td>500</td></tr><tr><td>1998</td><td>330</td><td>400</td></tr><tr><td>1999</td><td>525</td><td>610</td></tr><tr><td>2000</td><td>420</td><td>460</td></tr></table>",
            subQuestions: [
                { id: "q100", text: "Câu 100: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Trong các năm 1995, 1996, 1998, 1999, năm nào có độ chênh lệch giữa giá trị xuất khẩu và nhập khẩu lớn nhất?", options: ["A. 1995.", "B. 1996.", "C. 1998.", "D. 1999."], correctIndex: 3 },
                { id: "q101", text: "Câu 101: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Tổng trị giá xuất khẩu trong năm 1999 xấp xỉ bao nhiêu phần trăm tổng trị giá hàng nhập khẩu trong các năm 1997, 1998 và 1999?", options: ["A. 33%.", "B. 35%.", "C. 47,5%.", "D. 49%."], correctIndex: 3 },
                { id: "q102", text: "Câu 102: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Trong các năm từ 1996 đến năm 1999, tổng trị giá xuất - nhập khẩu của năm nào có tỷ lệ phần trăm tăng nhiều nhất so với năm trước đó?", options: ["A. 1996.", "B. 1997.", "C. 1998.", "D. 1999."], correctIndex: 1 }
            ]
        },

        // Reading Group 103-105
        {
            id: "reading_103_105_d2",
            section: "PHẦN 3. TƯ DUY KHOA HỌC",
            type: "reading_group",
            passage: "<strong>3.2. SUY LUẬN KHOA HỌC</strong><br><strong>Dựa vào đoạn thông tin sau trả lời từ câu 103 đến câu 105</strong><br><br>Trong quá trình truyền tải điện năng đi xa, hiện tượng tỏa nhiệt trên đường dây gây ra sự hao hụt một lượng lớn điện năng. Để giải quyết vấn đề này một cách hiệu quả và tiết kiệm, biện pháp tốt nhất là dùng máy biến áp nhằm nâng cao điện áp trước lúc truyền tải. Nguyên tắc hoạt động của máy biến áp dựa trên hiện tượng cảm ứng điện từ. Mối liên hệ giữa điện áp ở cuộn thứ cấp U₂ và cuộn sơ cấp U₁ được thể hiện qua tỷ lệ: U₂/U₁ = N₂/N₁, trong đó N₁ và N₂ tương ứng là số vòng dây của cuộn sơ cấp và thứ cấp.<br><br>Mặc dù vậy, khi hoạt động, nhiệt lượng phát sinh có nguy cơ làm thiết bị quá nhiệt và dẫn đến cháy nổ. Do đó, thay vì dùng lõi thép khối đặc, người ta chế tạo lõi máy biến áp bằng cách ghép nhiều lá thép mỏng cách điện với nhau. Cấu tạo này giúp thiết bị vận hành an toàn và gia tăng tuổi thọ. Khi truyền tải điện, máy biến áp thường được đặt ở trạm phát để tăng áp. Ở điều kiện lý tưởng, nếu điện áp tăng n lần thì công suất hao phí sẽ giảm n² lần. Tuy nhiên, trong thực tế, do điện trở của đường dây dài và sự thất thoát nhiệt ra môi trường, hiệu suất truyền tải không thể nào đạt tới mức 100%.<br><br>Xét một hệ thống thực tế đang sử dụng một máy biến áp với cuộn sơ cấp gồm 10.000 vòng và cuộn thứ cấp gồm 50.000 vòng.",
            subQuestions: [
                { id: "q103", text: "Câu 103: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Giả sử hiệu điện thế đặt vào hai đầu cuộn sơ cấp là 1500V, hỏi điện áp thu được ở hai đầu cuộn thứ cấp bằng bao nhiêu?", options: ["A. 7500V.", "B. 5000V.", "C. 750V.", "D. 300V."], correctIndex: 0 },
                { id: "q104", text: "Câu 104: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Nếu hiệu suất truyền tải ban đầu (khi chưa qua máy biến áp) đạt 80%, thì sau khi được tăng áp bằng máy biến áp nói trên, hiệu suất truyền tải mới sẽ đạt mức:", options: ["A. 96,0%.", "B. 99,2%.", "C. 92,0%.", "D. 99,6%."], correctIndex: 1 },
                { id: "q105", text: "Câu 105: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Nhận định nào dưới đây không phải là tác dụng của việc sử dụng lõi thép ghép từ nhiều lá mỏng?", options: ["A. Làm giảm điện áp truyền tải trên đường dây.", "B. Kéo dài tuổi thọ hoạt động của thiết bị.", "C. Hạn chế rủi ro biến dạng và cháy nổ.", "D. Giảm bớt phần năng lượng hao hụt do tỏa nhiệt bên trong lõi."], correctIndex: 0 }
            ]
        },

        // Reading Group 106-108
        {
            id: "reading_106_108_d2",
            section: "PHẦN 3. TƯ DUY KHOA HỌC",
            type: "reading_group",
            passage: "<strong>Dựa vào đoạn thông tin sau trả lời từ câu 106 đến câu 108</strong><br><br>Theo các nghiên cứu sinh thái học, sự tăng trưởng của mọi quần thể đều chịu sự chi phối và giới hạn bởi sức chứa của môi trường. Giới hạn này được quyết định trực tiếp bởi các nhân tố như không gian sinh tồn, điều kiện khí hậu và nguồn dinh dưỡng. Khi kích thước quần thể đạt tới sức chứa tối đa (ngưỡng K), đà tăng trưởng mạnh sẽ chững lại, và số lượng cá thể chuyển sang duy trì trạng thái biến động nhẹ xung quanh mức cân bằng sinh thái.",
            subQuestions: [
                { id: "q106", text: "Câu 106: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Trong giai đoạn từ 1820 đến 1940, số lượng cá thể tối đa của quần thể là:", options: ["A. 1.900.000.", "B. 2.200.000.", "C. 2.300.000.", "D. 1.800.000."], correctIndex: 1 },
                { id: "q107", text: "Câu 107: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Trong giai đoạn ổn định, số lượng cá thể dao động quanh khoảng nào?", options: ["A. 1.000.000 đến 1.300.000.", "B. 2.000.000 đến 2.200.000.", "C. 1.600.000 đến 1.700.000.", "D. 1.300.000 đến 1.600.000."], correctIndex: 3 },
                { id: "q108", text: "Câu 108: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Dựa vào biểu đồ, nhận định nào dưới đây là đúng?", options: ["A. Trong suốt giai đoạn từ 1850 đến 1920, kích thước quần thể luôn duy trì ở mức thấp hơn ngưỡng cân bằng sinh thái.", "B. Kể từ năm 1820 đến năm 1850, số lượng cá thể của quần thể liên tục có xu hướng gia tăng.", "C. Điều kiện thời tiết, khí hậu và nguồn dinh dưỡng là những nhân tố quyết định sức chứa K của môi trường.", "D. Quần thể ghi nhận sự biến động số lượng cá thể theo chiều hướng đi lên trong khoảng thời gian từ năm 1820 đến 1880."], correctIndex: 2 }
            ]
        },

        // Reading Group 109-111
        {
            id: "reading_109_111_d2",
            section: "PHẦN 3. TƯ DUY KHOA HỌC",
            type: "reading_group",
            passage: "<strong>Dựa vào thông tin dưới đây để trả lời các câu từ 109 đến 111</strong><br><br>Báo cáo của UBND tỉnh Quảng Ngãi cho biết, tốc độ tăng trưởng GRDP năm 2025 (tính theo giá so sánh 2010) đã bứt phá đạt mức 10,02% so với năm liền trước. Với quy mô nền kinh tế (GRDP) theo giá hiện hành chạm mốc 192.000 tỷ đồng, địa phương này không chỉ vượt chỉ tiêu tăng trưởng do Chính phủ giao phó mà còn vươn lên dẫn đầu toàn khu vực miền Trung và vinh dự xếp thứ 6/34 tỉnh thành trên cả nước về tốc độ tăng GRDP.<br><br>Việc góp mặt trong nhóm 6 địa phương có mức tăng GRDP vượt 10% đã tạo bước đệm vững chắc để tỉnh hiện thực hóa mục tiêu duy trì đà tăng trưởng hai chữ số trong nhiều năm liên tiếp theo định hướng của Trung ương. Nếu như năm 2024, mức tăng trưởng của Quảng Ngãi chỉ khiêm tốn ở mức 4,07% (nằm dưới mức bình quân 8,02% của cả nước), thì bước sang năm 2025, sự trỗi dậy mạnh mẽ của các lĩnh vực sản xuất công nghiệp, dịch vụ và xây dựng đã đưa địa phương bứt tốc lọt vào nhóm dẫn đầu. Đóng vai trò động lực chính là ngành luyện thép (giá trị sản xuất tăng gần 35%) và lọc hóa dầu (tăng 20%), hai lĩnh vực hạt nhân đóng góp tới hơn 73% giá trị của toàn ngành công nghiệp.",
            subQuestions: [
                { id: "q109", text: "Câu 109: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Động lực tăng trưởng kinh tế của tỉnh Quảng Ngãi là:", options: ["A. Thu hút nguồn vốn đầu tư trực tiếp từ nước ngoài.", "B. Sự phát triển mạnh mẽ của sản xuất công nghiệp, xây dựng và dịch vụ.", "C. Chú trọng đầu tư vào hệ thống cơ sở hạ tầng trọng điểm.", "D. Mở rộng thị trường tiêu thụ cho các sản phẩm địa phương."], correctIndex: 1 },
                { id: "q110", text: "Câu 110: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Tình hình kinh tế của tỉnh Quảng Ngãi trong năm 2025 so với năm 2024 như thế nào?", options: ["A. Giữ vị trí thấp nhất về tăng trưởng tại khu vực miền Trung.", "B. Có mức tăng trưởng kinh tế thấp hơn trung bình chung của cả nước.", "C. Vươn lên trở thành một trong những địa phương dẫn đầu cả nước về tốc độ tăng trưởng.", "D. Tiếp tục duy trì tốc độ tăng trưởng kinh tế ở mức ổn định như cũ."], correctIndex: 2 },
                { id: "q111", text: "Câu 111: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Mục tiêu được Trung ương đặt ra là:", options: ["A. Đạt mức tăng trưởng kinh tế từ hai con số trở lên trong nhiều năm liên tiếp.", "B. Gia tăng tỷ trọng ngành công nghiệp và kéo giảm tỷ trọng ngành dịch vụ.", "C. Đưa quảng ngãi lọt top sáu tỉnh, thành có quy mô nền kinh tế (grdp) lớn nhất.", "D. Dồn trọng tâm đầu tư cho hai ngành mũi nhọn là luyện thép và lọc dầu."], correctIndex: 0 }
            ]
        },

        // Reading Group 112-114
        {
            id: "reading_112_114_d2",
            section: "PHẦN 3. TƯ DUY KHOA HỌC",
            type: "reading_group",
            passage: "<strong>Dựa vào đoạn thông tin sau trả lời từ câu 112 đến câu 114</strong><br><br>Là một doanh nghiệp hoạt động trong ngành sản xuất công nghiệp, Công ty A đã vi phạm quy định khi không đưa nước thải vào hệ thống xử lý tập trung của khu vực. Thay vào đó, doanh nghiệp này đã bí mật chôn lấp các đường ống ngầm nhằm xả trực tiếp lượng nước chưa qua xử lý ra hệ thống sông ngòi. Hậu quả là môi trường nước khu vực lân cận bị ô nhiễm nặng nề, thủy sản chết trắng hàng loạt, đồng thời đe dọa nghiêm trọng đến sức khỏe và tình hình canh tác nông nghiệp của cư dân xung quanh. Phát hiện những dấu hiệu bất thường, người dân địa phương đã chủ động theo dõi và tố giác sự việc lên cơ quan chức năng. Sau khi tiến hành xác minh tại hiện trường, chính quyền đã lập biên bản và ban hành quyết định phạt vi phạm hành chính 250 triệu đồng đối với Công ty A.",
            subQuestions: [
                { id: "q112", text: "Câu 112: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Căn cứ vào các quy định pháp luật, nguyên nhân chính dẫn đến việc Công ty A chịu án phạt là hành vi nào sau đây?", options: ["A. Thiếu minh bạch trong việc công khai các báo cáo về môi trường và quá trình xả thải.", "B. Trực tiếp xả nguồn nước chưa qua hệ thống xử lý đạt chuẩn ra môi trường tự nhiên.", "C. Không tuân thủ các quy định về đảm bảo an toàn lao động tại cơ sở sản xuất.", "D. Trốn tránh nghĩa vụ nộp các khoản phí bảo vệ môi trường đối với hoạt động xả thải."], correctIndex: 1 },
                { id: "q113", text: "Câu 113: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Mức tiền phạt 250 triệu đồng được cơ quan nhà nước căn cứ chủ yếu vào yếu tố nào?", options: ["A. Dựa trên doanh thu hằng năm của công ty A và lợi nhuận của công ty có được từ việc xả nước thải trực tiếp thay cho việc xây dựng hệ thống xử lý nước thải.", "B. Đánh giá tác động của hành vi xả nước thải đối sức khỏe cộng đồng và môi trường.", "C. Lượng nước thải không qua xử lý đã được công ty A xả ra môi trường.", "D. Thời gian hoạt động của công ty và khoảng thời gian công ty xả nước thải trái quy định."], correctIndex: 1 },
                { id: "q114", text: "Câu 114: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Cơ quan quản lý nhà nước chủ yếu dựa trên cơ sở nào để đưa ra mức phạt hành chính 250 triệu đồng?", options: ["A. Khối lượng nước thải chưa được xử lý đạt chuẩn mà doanh nghiệp này đã xả ra môi trường.", "B. Quá trình hoạt động của doanh nghiệp và tổng thời gian diễn ra hành vi xả thải trái phép.", "C. Mức doanh thu hàng năm của doanh nghiệp kết hợp với những hậu quả do việc xả thải gây ra.", "D. Mức độ tác động tiêu cực của hành vi xả thải đối với hệ sinh thái môi trường và sức khỏe cộng đồng."], correctIndex: 3 }
            ]
        },

        // Reading Group 115-117
        {
            id: "reading_115_117_d2",
            section: "PHẦN 3. TƯ DUY KHOA HỌC",
            type: "reading_group",
            passage: "<strong>Dựa vào đoạn thông tin sau trả lời từ câu 115 đến câu 117</strong><br><br>Thời kỳ trị vì của vua Lê Thánh Tông được xem là một trong những giai đoạn cường thịnh bậc nhất, mở ra kỷ nguyên vàng son của nhà nước phong kiến Việt Nam. Nền tảng then chốt tạo nên sự phồn vinh này nằm ở các chính sách cải tổ mạnh mẽ về cơ cấu chính quyền và hệ thống pháp luật. Suốt thời gian cầm quyền (1460 – 1497), ông đã xây dựng nên một mạng lưới hành chính quy củ, chặt chẽ từ cấp trung ương xuống tận cơ sở, kết hợp với việc ban hành các luật lệ đậm đà bản sắc dân tộc và giàu giá trị nhân đạo. Qua những bước đi đột phá đó, triều đình đã kiến tạo một nền chính trị vững chắc, thúc đẩy nền kinh tế thăng hoa và bảo vệ trọn vẹn chủ quyền lãnh thổ quốc gia.",
            subQuestions: [
                { id: "q115", text: "Câu 115: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Vua Lê Thánh Tông là vị quân vương trị vì trong giai đoạn nào của lịch sử nước ta?", options: ["A. Lê Trung Hưng.", "B. Lê sơ.", "C. Tiền Lê.", "D. Lê Mạt."], correctIndex: 1 },
                { id: "q116", text: "Câu 116: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Yếu tố cốt lõi nào đã dẫn đến sự phồn vinh dưới thời vua Lê Thánh Tông?", options: ["A. Những bước đột phá trong lĩnh vực văn hóa và đời sống xã hội.", "B. Việc thay đổi, kiện toàn lại cơ cấu chính quyền và đội ngũ quan lại.", "C. Các chính sách cải tổ sâu rộng đối với cơ cấu bộ máy nhà nước và luật pháp.", "D. Những cải tổ nhằm xây dựng một hệ thống pháp luật hoàn chỉnh nhất."], correctIndex: 2 },
                { id: "q117", text: "Câu 117: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Đâu là tên của bộ luật được soạn thảo và ban hành dưới thời kỳ trị vì của vị vua này?", options: ["A. Bộ luật Hình Luật.", "B. Bộ luật Hình thư.", "C. Bộ luật Gia Long.", "D. Bộ luật Hồng Đức."], correctIndex: 3 }
            ]
        },

        // Reading Group 118-120
        {
            id: "reading_118_120_d2",
            section: "PHẦN 3. TƯ DUY KHOA HỌC",
            type: "reading_group",
            passage: "<strong>Dựa vào đoạn thông tin sau trả lời từ câu 118 đến câu 120</strong><br><br>Khi tốc độ bay hơi của các phân tử chất lỏng cân bằng chính xác với tốc độ ngưng tụ của các phân tử từ dạng hơi quay trở lại pha lỏng, một trạng thái cân bằng động sẽ được thiết lập. Lúc này, lớp hơi tích tụ ở phía trên bề mặt chất lỏng được gọi là hơi bão hòa, và áp suất do nó tác dụng lên hệ thống đạt đến một giá trị cực đại, được gọi là áp suất hơi bão hòa. Đại lượng này là thước đo đặc trưng cho tính dễ bay hơi của chất lỏng và tỉ lệ thuận với nhiệt độ. Tại điểm mà áp suất hơi bão hòa bằng áp suất khí quyển thì điểm đó chính là nhiệt độ sôi của chất đó. Đối với một hỗn hợp dung dịch tại điều kiện lý tưởng, áp suất hơi bão hòa của hỗn hợp dung dịch sẽ được tính bằng tổng các áp suất hơi riêng phần của từng cấu tử thành phần tạo nên dung dịch đó.<br><br><table class=\"table table-bordered text-center\" style=\"width:auto; margin:10px auto\"><tr><th>Dung dịch</th><th>n-heptane (mol)</th><th>n-octane (mol)</th><th>Áp suất hơi bão hòa ở 25°C (mmHg)</th></tr><tr><td>1</td><td>0,2</td><td>0,8</td><td>20,4</td></tr><tr><td>2</td><td>0,3</td><td>0,7</td><td>23,6</td></tr><tr><td>3</td><td>0,4</td><td>0,6</td><td>26,8</td></tr><tr><td>4</td><td>0,5</td><td>0,5</td><td>30,0</td></tr><tr><td>5</td><td>0,6</td><td>0,4</td><td>33,2</td></tr><tr><td>6</td><td>0,8</td><td>0,2</td><td>39,6</td></tr><tr><td>7</td><td>0,9</td><td>0,1</td><td>42,8</td></tr></table>",
            subQuestions: [
                { id: "q118", text: "Câu 118: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Xét một dung dịch lý tưởng được pha trộn từ 0,6 mol octan và 0,5 mol heptan, giá trị áp suất hơi bão hòa của dung dịch này sẽ rơi vào khoảng:", options: ["A. Từ 30 đến 33,2.", "B. Trên 33,2.", "C. Dưới 26,8.", "D. Từ 26,8 đến 30."], correctIndex: 3 },
                { id: "q119", text: "Câu 119: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Phát biểu nào sau đây là sai khi đánh giá về tính chất áp suất hơi bão hòa của hệ hỗn hợp chứa n-heptane và n-octane?", options: ["A. Giá trị áp suất hơi bão hòa của hỗn hợp luôn nằm ở mức trung gian: cao hơn của n-octane nhưng thấp hơn của n-heptane.", "B. Sự thay đổi tỷ lệ thành phần giữa n-heptane và n-octane hoàn toàn không làm ảnh hưởng đến áp suất hơi bão hòa của hỗn hợp.", "C. Trong hệ hỗn hợp này, n-heptane thể hiện khả năng bay hơi kém hơn so với lúc nó ở trạng thái tinh khiết.", "D. Áp suất hơi bão hòa của toàn hệ thống sẽ tăng lên nếu ta gia tăng số mol của thành phần n-heptane."], correctIndex: 1 },
                { id: "q120", text: "Câu 120: [ĐỀ CHÍNH THỨC ĐỢT 1 - 2026] Phát biểu nào dưới đây mô tả chính xác nhất bản chất quy luật về áp suất hơi bão hòa áp dụng cho các dung dịch?", options: ["A. Ở điều kiện áp suất 760 mmHg, do có áp suất hơi bão hòa thấp hơn và khó bay hơi hơn nên n-heptane có nhiệt độ sôi cao hơn n-octane.", "B. Sự gia tăng tỷ lệ n-octane trong hỗn hợp làm cho áp suất hơi bão hòa của hệ tăng lên, từ đó dẫn đến sự suy giảm nhiệt độ sôi của toàn hỗn hợp.", "C. Khi áp suất khí quyển giảm xuống, chất lỏng trở nên dễ bay hơi hơn do áp suất hơi giảm, kéo theo sự gia tăng nhiệt độ sôi của n-heptane.", "D. Tại mức áp suất khí quyển 760 mmHg, nhiệt độ sôi của hệ hỗn hợp n-heptane và n-octane sẽ mang một giá trị nằm giữa khoảng nhiệt độ sôi của hai chất thành phần."], correctIndex: 3 }
            ]
        }
    ]
};

const dataFilePath = path.join(__dirname, '..', 'js', 'data.js');
let dataContent = fs.readFileSync(dataFilePath, 'utf8');

// Parse mockQuizzes using eval or VM in node to safely append
const quizString = JSON.stringify(quiz2, null, 4);

// We replace the end of mockQuizzes array `];` with `, \n` + quizString + `\n];`
const lastBracketIndex = dataContent.lastIndexOf('];');
if (lastBracketIndex !== -1) {
    const updatedContent = dataContent.slice(0, lastBracketIndex) + ',\n    ' + quizString + '\n];\n';
    fs.writeFileSync(dataFilePath, updatedContent, 'utf8');
    console.log('Successfully added Đề 2 to data.js!');
} else {
    console.error('Could not find ]; in data.js');
}
